### Intro to pandas DataFrame iteration

In [2]:
import pandas as pd
import numpy as np

In [26]:
url = "https://assets.datacamp.com/production/repositories/3581/datasets/779033fb8fb5021aee9ff46253980abcbc5851f3/baseball_stats.csv"


df= pd.read_csv(url)

In [27]:
df

,Team,League,Year,RS,RA,W,OBP,SLG,BA,Playoffs,RankSeason,RankPlayoffs,G,OOBP,OSLG
0,ARI,NL,2012,734,688,81,0.328,0.418,0.259,0,NaN,NaN,162,0.317,0.415
1,ATL,NL,2012,700,600,94,0.320,0.389,0.247,1,4.0,5.0,162,0.306,0.378
2,BAL,AL,2012,712,705,93,0.311,0.417,0.247,1,5.0,4.0,162,0.315,0.403
3,BOS,AL,2012,734,806,69,0.315,0.415,0.260,0,NaN,NaN,162,0.331,0.428
4,CHC,NL,2012,613,759,61,0.302,0.378,0.240,0,NaN,NaN,162,0.335,0.424
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1227,PHI,NL,1962,705,759,81,0.330,0.390,0.260,0,NaN,NaN,161,NaN,NaN
1228,PIT,NL,1962,706,626,93,0.321,0.394,0.268,0,NaN,NaN,161,NaN,NaN
1229,SFG,NL,1962,878,690,103,0.341,0.441,0.278,1,1.0,2.0,165,NaN,NaN
1230,STL,NL,1962,774,664,84,0.335,0.394,0.271,0,NaN,NaN,163,NaN,NaN
1231,WSA,AL,1962,599,716,60,0.308,0.373,0.250,0,NaN,NaN,162,NaN,NaN

In [28]:
def cal_win_perc(wins,games_played):
    win_perch = wins / games_played
    return np.round(win_perch,2)

In [29]:
w=cal_win_perc(50,100)
print(w)

0.5

In [30]:
win_perch_list = []

for i in range(len(df)):
    row = df.iloc[i]
    wins = row['W']
    games_played =row['G']
    w=cal_win_perc(wins,games_played)
    win_perch_list.append(w)
    
df['WP']=win_perch_list

# iloc is not efficient way to use it. iterrow is the best

In [31]:
df

,Team,League,Year,RS,RA,W,OBP,SLG,BA,Playoffs,RankSeason,RankPlayoffs,G,OOBP,OSLG,WP
0,ARI,NL,2012,734,688,81,0.328,0.418,0.259,0,NaN,NaN,162,0.317,0.415,0.50
1,ATL,NL,2012,700,600,94,0.320,0.389,0.247,1,4.0,5.0,162,0.306,0.378,0.58
2,BAL,AL,2012,712,705,93,0.311,0.417,0.247,1,5.0,4.0,162,0.315,0.403,0.57
3,BOS,AL,2012,734,806,69,0.315,0.415,0.260,0,NaN,NaN,162,0.331,0.428,0.43
4,CHC,NL,2012,613,759,61,0.302,0.378,0.240,0,NaN,NaN,162,0.335,0.424,0.38
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1227,PHI,NL,1962,705,759,81,0.330,0.390,0.260,0,NaN,NaN,161,NaN,NaN,0.50
1228,PIT,NL,1962,706,626,93,0.321,0.394,0.268,0,NaN,NaN,161,NaN,NaN,0.58
1229,SFG,NL,1962,878,690,103,0.341,0.441,0.278,1,1.0,2.0,165,NaN,NaN,0.62
1230,STL,NL,1962,774,664,84,0.335,0.394,0.271,0,NaN,NaN,163,NaN,NaN,0.52
1231,WSA,AL,1962,599,716,60,0.308,0.373,0.250,0,NaN,NaN,162,NaN,NaN,0.37

In [32]:
win_perch_list = []

for i,row in df.iterrows():
    wins = row['W']
    games_played =row['G']
    
    w=cal_win_perc(wins,games_played)
    win_perch_list.append(w)


df['WP']=win_perch_list

In [33]:
def calc_run_diff(runs_scored, runs_allowed):

    run_diff = runs_scored - runs_allowed

    return run_diff

In [34]:
# Create an empty list to store run differentials
run_diffs = []

# Write a for loop and collect runs allowed and runs scored for each row
for i,row in df.iterrows():
    runs_scored = row['RS']
    runs_allowed = row['RA']
    
    # Use the provided function to calculate run_diff for each row
    run_diff = calc_run_diff(runs_scored, runs_allowed)
    
    # Append each run differential to the output list
    run_diffs.append(run_diff)

df['RD'] = run_diffs
print(df)

     Team League  Year   RS   RA    W    OBP    SLG     BA  Playoffs  \
0     ARI     NL  2012  734  688   81  0.328  0.418  0.259         0
1     ATL     NL  2012  700  600   94  0.320  0.389  0.247         1
2     BAL     AL  2012  712  705   93  0.311  0.417  0.247         1
3     BOS     AL  2012  734  806   69  0.315  0.415  0.260         0
4     CHC     NL  2012  613  759   61  0.302  0.378  0.240         0
...   ...    ...   ...  ...  ...  ...    ...    ...    ...       ...
1227  PHI     NL  1962  705  759   81  0.330  0.390  0.260         0
1228  PIT     NL  1962  706  626   93  0.321  0.394  0.268         0
1229  SFG     NL  1962  878  690  103  0.341  0.441  0.278         1
1230  STL     NL  1962  774  664   84  0.335  0.394  0.271         0
1231  WSA     AL  1962  599  716   60  0.308  0.373  0.250         0

      RankSeason  RankPlayoffs    G   OOBP   OSLG    WP   RD
0            NaN           NaN  162  0.317  0.415  0.50   46
1            4.0           5.0  162  0.306  0.378  0.58  100
2            5.0           4.0  162  0.315  0.403  0.57    7
3            NaN           NaN  162  0.331  0.428  0.43  -72
4            NaN           NaN  162  0.335  0.424  0.38 -146
...          ...           ...  ...    ...    ...   ...  ...
1227         NaN           NaN  161    NaN    NaN  0.50  -54
1228         NaN           NaN  161    NaN    NaN  0.58   80
1229         1.0           2.0  165    NaN    NaN  0.62  188
1230         NaN           NaN  163    NaN    NaN  0.52  110
1231         NaN           NaN  162    NaN    NaN  0.37 -117

[1232 rows x 17 columns]

In [35]:
for row_tuple in df.iterrows():
    print(row_tuple)
    print(type(row_tuple[1]))
# we see each row values data stored as panda series. dot.iterrows returns each dataframe row as a tuple index panda series  pairs. We have to access to row of values by using []  as a tuple

(0, Team              ARI
League             NL
Year             2012
RS                734
RA                688
W                  81
OBP             0.328
SLG             0.418
BA              0.259
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.317
OSLG            0.415
WP                0.5
RD                 46
Name: 0, dtype: object)
<class 'pandas.core.series.Series'>
(1, Team              ATL
League             NL
Year             2012
RS                700
RA                600
W                  94
OBP              0.32
SLG             0.389
BA              0.247
Playoffs            1
RankSeason          4
RankPlayoffs        5
G                 162
OOBP            0.306
OSLG            0.378
WP               0.58
RD                100
Name: 1, dtype: object)
<class 'pandas.core.series.Series'>
(2, Team              BAL
League             AL
Year             2012
RS                712
RA                705
W                  93
OBP             0.311
SLG             0.417
BA              0.247
Playoffs            1
RankSeason          5
RankPlayoffs        4
G                 162
OOBP            0.315
OSLG            0.403
WP               0.57
RD                  7
Name: 2, dtype: object)
<class 'pandas.core.series.Series'>
(3, Team              BOS
League             AL
Year             2012
RS                734
RA                806
W                  69
OBP             0.315
SLG             0.415
BA               0.26
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.331
OSLG            0.428
WP               0.43
RD                -72
Name: 3, dtype: object)
<class 'pandas.core.series.Series'>
(4, Team              CHC
League             NL
Year             2012
RS                613
RA                759
W                  61
OBP             0.302
SLG             0.378
BA               0.24
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.335
OSLG            0.424
WP               0.38
RD               -146
Name: 4, dtype: object)
<class 'pandas.core.series.Series'>
(5, Team              CHW
League             AL
Year             2012
RS                748
RA                676
W                  85
OBP             0.318
SLG             0.422
BA              0.255
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.319
OSLG            0.405
WP               0.52
RD                 72
Name: 5, dtype: object)
<class 'pandas.core.series.Series'>
(6, Team              CIN
League             NL
Year             2012
RS                669
RA                588
W                  97
OBP             0.315
SLG             0.411
BA              0.251
Playoffs            1
RankSeason          2
RankPlayoffs        4
G                 162
OOBP            0.305
OSLG             0.39
WP                0.6
RD                 81
Name: 6, dtype: object)
<class 'pandas.core.series.Series'>
(7, Team              CLE
League             AL
Year             2012
RS                667
RA                845
W                  68
OBP             0.324
SLG             0.381
BA              0.251
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.336
OSLG             0.43
WP               0.42
RD               -178
Name: 7, dtype: object)
<class 'pandas.core.series.Series'>
(8, Team              COL
League             NL
Year             2012
RS                758
RA                890
W                  64
OBP              0.33
SLG             0.436
BA              0.274
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.357
OSLG             0.47
WP                0.4
RD               -132
Name: 8, dtype: object)
<class 'pandas.core.series.Series'>
(9, Team              DET
League             AL
Year             2012
RS                726
RA                670
W                  88
OBP             0.335
SLG             0.422
BA              0.268
Playoffs            1
RankSeason          6
RankPlayoffs        2
G                 162
OOBP            0.314
OSLG            0.402
WP               0.54
RD                 56
Name: 9, dtype: object)
<class 'pandas.core.series.Series'>
(10, Team              HOU
League             NL
Year             2012
RS                583
RA                794
W                  55
OBP             0.302
SLG             0.371
BA              0.236
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.337
OSLG            0.427
WP               0.34
RD               -211
Name: 10, dtype: object)
<class 'pandas.core.series.Series'>
(11, Team              KCR
League             AL
Year             2012
RS                676
RA                746
W                  72
OBP             0.317
SLG               0.4
BA              0.265
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.339
OSLG            0.423
WP               0.44
RD                -70
Name: 11, dtype: object)
<class 'pandas.core.series.Series'>
(12, Team              LAA
League             AL
Year             2012
RS                767
RA                699
W                  89
OBP             0.332
SLG             0.433
BA              0.274
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP             0.31
OSLG            0.403
WP               0.55
RD                 68
Name: 12, dtype: object)
<class 'pandas.core.series.Series'>
(13, Team              LAD
League             NL
Year             2012
RS                637
RA                597
W                  86
OBP             0.317
SLG             0.374
BA              0.252
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP             0.31
OSLG            0.364
WP               0.53
RD                 40
Name: 13, dtype: object)
<class 'pandas.core.series.Series'>
(14, Team              MIA
League             NL
Year             2012
RS                609
RA                724
W                  69
OBP             0.308
SLG             0.382
BA              0.244
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.327
OSLG            0.399
WP               0.43
RD               -115
Name: 14, dtype: object)
<class 'pandas.core.series.Series'>
(15, Team              MIL
League             NL
Year             2012
RS                776
RA                733
W                  83
OBP             0.325
SLG             0.437
BA              0.259
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.326
OSLG            0.414
WP               0.51
RD                 43
Name: 15, dtype: object)
<class 'pandas.core.series.Series'>
(16, Team              MIN
League             AL
Year             2012
RS                701
RA                832
W                  66
OBP             0.325
SLG              0.39
BA               0.26
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.333
OSLG            0.442
WP               0.41
RD               -131
Name: 16, dtype: object)
<class 'pandas.core.series.Series'>
(17, Team              NYM
League             NL
Year             2012
RS                650
RA                709
W                  74
OBP             0.316
SLG             0.386
BA              0.249
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.315
OSLG            0.401
WP               0.46
RD                -59
Name: 17, dtype: object)
<class 'pandas.core.series.Series'>
(18, Team              NYY
League             AL
Year             2012
RS                804
RA                668
W                  95
OBP             0.337
SLG             0.453
BA              0.265
Playoffs            1
RankSeason          3
RankPlayoffs        3
G                 162
OOBP            0.311
OSLG            0.419
WP               0.59
RD                136
Name: 18, dtype: object)
<class 'pandas.core.series.Series'>
(19, Team              OAK
League             AL
Year             2012
RS                713
RA                614
W                  94
OBP              0.31
SLG             0.404
BA              0.238
Playoffs            1
RankSeason          4
RankPlayoffs        4
G                 162
OOBP            0.306
OSLG            0.378
WP               0.58
RD                 99
Name: 19, dtype: object)
<class 'pandas.core.series.Series'>
(20, Team              PHI
League             NL
Year             2012
RS                684
RA                680
W                  81
OBP             0.317
SLG               0.4
BA              0.255
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.306
OSLG            0.407
WP                0.5
RD                  4
Name: 20, dtype: object)
<class 'pandas.core.series.Series'>
(21, Team              PIT
League             NL
Year             2012
RS                651
RA                674
W                  79
OBP             0.304
SLG             0.395
BA              0.243
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.314
OSLG             0.39
WP               0.49
RD                -23
Name: 21, dtype: object)
<class 'pandas.core.series.Series'>
(22, Team              SDP
League             NL
Year             2012
RS                651
RA                710
W                  76
OBP             0.319
SLG              0.38
BA              0.247
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.319
OSLG            0.398
WP               0.47
RD                -59
Name: 22, dtype: object)
<class 'pandas.core.series.Series'>
(23, Team              SEA
League             AL
Year             2012
RS                619
RA                651
W                  75
OBP             0.296
SLG             0.369
BA              0.234
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.308
OSLG            0.394
WP               0.46
RD                -32
Name: 23, dtype: object)
<class 'pandas.core.series.Series'>
(24, Team              SFG
League             NL
Year             2012
RS                718
RA                649
W                  94
OBP             0.327
SLG             0.397
BA              0.269
Playoffs            1
RankSeason          4
RankPlayoffs        1
G                 162
OOBP            0.313
OSLG            0.393
WP               0.58
RD                 69
Name: 24, dtype: object)
<class 'pandas.core.series.Series'>
(25, Team              STL
League             NL
Year             2012
RS                765
RA                648
W                  88
OBP             0.338
SLG             0.421
BA              0.271
Playoffs            1
RankSeason          6
RankPlayoffs        3
G                 162
OOBP            0.313
OSLG            0.387
WP               0.54
RD                117
Name: 25, dtype: object)
<class 'pandas.core.series.Series'>
(26, Team              TBR
League             AL
Year             2012
RS                697
RA                577
W                  90
OBP             0.317
SLG             0.394
BA               0.24
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.294
OSLG            0.352
WP               0.56
RD                120
Name: 26, dtype: object)
<class 'pandas.core.series.Series'>
(27, Team              TEX
League             AL
Year             2012
RS                808
RA                707
W                  93
OBP             0.334
SLG             0.446
BA              0.273
Playoffs            1
RankSeason          5
RankPlayoffs        5
G                 162
OOBP            0.309
OSLG            0.408
WP               0.57
RD                101
Name: 27, dtype: object)
<class 'pandas.core.series.Series'>
(28, Team              TOR
League             AL
Year             2012
RS                716
RA                784
W                  73
OBP             0.309
SLG             0.407
BA              0.245
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.335
OSLG            0.438
WP               0.45
RD                -68
Name: 28, dtype: object)
<class 'pandas.core.series.Series'>
(29, Team              WSN
League             NL
Year             2012
RS                731
RA                594
W                  98
OBP             0.322
SLG             0.428
BA              0.261
Playoffs            1
RankSeason          1
RankPlayoffs        4
G                 162
OOBP            0.303
OSLG            0.373
WP                0.6
RD                137
Name: 29, dtype: object)
<class 'pandas.core.series.Series'>
(30, Team              ARI
League             NL
Year             2011
RS                731
RA                662
W                  94
OBP             0.322
SLG             0.413
BA               0.25
Playoffs            1
RankSeason          5
RankPlayoffs        4
G                 162
OOBP            0.316
OSLG            0.409
WP               0.58
RD                 69
Name: 30, dtype: object)
<class 'pandas.core.series.Series'>
(31, Team              ATL
League             NL
Year             2011
RS                641
RA                605
W                  89
OBP             0.308
SLG             0.387
BA              0.243
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP             0.31
OSLG            0.361
WP               0.55
RD                 36
Name: 31, dtype: object)
<class 'pandas.core.series.Series'>
(32, Team              BAL
League             AL
Year             2011
RS                708
RA                860
W                  69
OBP             0.316
SLG             0.413
BA              0.257
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.341
OSLG             0.46
WP               0.43
RD               -152
Name: 32, dtype: object)
<class 'pandas.core.series.Series'>
(33, Team              BOS
League             AL
Year             2011
RS                875
RA                737
W                  90
OBP             0.349
SLG             0.461
BA               0.28
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.322
OSLG            0.392
WP               0.56
RD                138
Name: 33, dtype: object)
<class 'pandas.core.series.Series'>
(34, Team              CHC
League             NL
Year             2011
RS                654
RA                756
W                  71
OBP             0.314
SLG             0.401
BA              0.256
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.335
OSLG            0.413
WP               0.44
RD               -102
Name: 34, dtype: object)
<class 'pandas.core.series.Series'>
(35, Team              CHW
League             AL
Year             2011
RS                654
RA                706
W                  79
OBP             0.319
SLG             0.388
BA              0.252
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.317
OSLG            0.397
WP               0.49
RD                -52
Name: 35, dtype: object)
<class 'pandas.core.series.Series'>
(36, Team              CIN
League             NL
Year             2011
RS                735
RA                720
W                  79
OBP             0.326
SLG             0.408
BA              0.256
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.325
OSLG            0.415
WP               0.49
RD                 15
Name: 36, dtype: object)
<class 'pandas.core.series.Series'>
(37, Team              CLE
League             AL
Year             2011
RS                704
RA                760
W                  80
OBP             0.317
SLG             0.396
BA               0.25
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.323
OSLG            0.413
WP               0.49
RD                -56
Name: 37, dtype: object)
<class 'pandas.core.series.Series'>
(38, Team              COL
League             NL
Year             2011
RS                735
RA                774
W                  73
OBP             0.329
SLG              0.41
BA              0.258
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.331
OSLG            0.431
WP               0.45
RD                -39
Name: 38, dtype: object)
<class 'pandas.core.series.Series'>
(39, Team              DET
League             AL
Year             2011
RS                787
RA                711
W                  95
OBP              0.34
SLG             0.434
BA              0.277
Playoffs            1
RankSeason          4
RankPlayoffs        3
G                 162
OOBP            0.321
OSLG            0.396
WP               0.59
RD                 76
Name: 39, dtype: object)
<class 'pandas.core.series.Series'>
(40, Team              FLA
League             NL
Year             2011
RS                625
RA                702
W                  72
OBP             0.318
SLG             0.388
BA              0.247
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.316
OSLG            0.401
WP               0.44
RD                -77
Name: 40, dtype: object)
<class 'pandas.core.series.Series'>
(41, Team              HOU
League             NL
Year             2011
RS                615
RA                796
W                  56
OBP             0.311
SLG             0.374
BA              0.258
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.337
OSLG            0.432
WP               0.35
RD               -181
Name: 41, dtype: object)
<class 'pandas.core.series.Series'>
(42, Team              KCR
League             AL
Year             2011
RS                730
RA                762
W                  71
OBP             0.329
SLG             0.415
BA              0.275
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.337
OSLG            0.425
WP               0.44
RD                -32
Name: 42, dtype: object)
<class 'pandas.core.series.Series'>
(43, Team              LAA
League             AL
Year             2011
RS                667
RA                633
W                  86
OBP             0.313
SLG             0.402
BA              0.253
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.313
OSLG            0.388
WP               0.53
RD                 34
Name: 43, dtype: object)
<class 'pandas.core.series.Series'>
(44, Team              LAD
League             NL
Year             2011
RS                644
RA                612
W                  82
OBP             0.322
SLG             0.375
BA              0.257
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 161
OOBP             0.31
OSLG            0.371
WP               0.51
RD                 32
Name: 44, dtype: object)
<class 'pandas.core.series.Series'>
(45, Team              MIL
League             NL
Year             2011
RS                721
RA                638
W                  96
OBP             0.325
SLG             0.425
BA              0.261

(151, Team              ATL
League             NL
Year             2007
RS                810
RA                733
W                  84
OBP             0.339
SLG             0.435
BA              0.275
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.327
OSLG            0.415
WP               0.52
RD                 77
Name: 151, dtype: object)
<class 'pandas.core.series.Series'>
(152, Team              BAL
League             AL
Year             2007
RS                756
RA                868
W                  69
OBP             0.333
SLG             0.412
BA              0.272
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.354
OSLG            0.412
WP               0.43
RD               -112
Name: 152, dtype: object)
<class 'pandas.core.series.Series'>
(153, Team              BOS
League             AL
Year             2007
RS                867
RA                657
W                  96
OBP             0.362
SLG             0.444
BA              0.279
Playoffs            1
RankSeason          1
RankPlayoffs        1
G                 162
OOBP            0.314
OSLG            0.392
WP               0.59
RD                210
Name: 153, dtype: object)
<class 'pandas.core.series.Series'>
(154, Team              CHC
League             NL
Year             2007
RS                752
RA                690
W                  85
OBP             0.333
SLG             0.422
BA              0.271
Playoffs            1
RankSeason          5
RankPlayoffs        4
G                 162
OOBP            0.322
OSLG            0.399
WP               0.52
RD                 62
Name: 154, dtype: object)
<class 'pandas.core.series.Series'>
(155, Team              CHW
League             AL
Year             2007
RS                693
RA                839
W                  72
OBP             0.318
SLG             0.404
BA              0.246
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.338
OSLG            0.435
WP               0.44
RD               -146
Name: 155, dtype: object)
<class 'pandas.core.series.Series'>
(156, Team              CIN
League             NL
Year             2007
RS                783
RA                853
W                  72
OBP             0.335
SLG             0.436
BA              0.267
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.343
OSLG            0.456
WP               0.44
RD                -70
Name: 156, dtype: object)
<class 'pandas.core.series.Series'>
(157, Team              CLE
League             AL
Year             2007
RS                811
RA                704
W                  96
OBP             0.343
SLG             0.428
BA              0.268
Playoffs            1
RankSeason          1
RankPlayoffs        3
G                 162
OOBP            0.322
OSLG            0.407
WP               0.59
RD                107
Name: 157, dtype: object)
<class 'pandas.core.series.Series'>
(158, Team              COL
League             NL
Year             2007
RS                860
RA                758
W                  90
OBP             0.354
SLG             0.437
BA               0.28
Playoffs            1
RankSeason          3
RankPlayoffs        2
G                 163
OOBP             0.33
OSLG            0.423
WP               0.55
RD                102
Name: 158, dtype: object)
<class 'pandas.core.series.Series'>
(159, Team              DET
League             AL
Year             2007
RS                887
RA                797
W                  88
OBP             0.345
SLG             0.458
BA              0.287
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.338
OSLG            0.427
WP               0.54
RD                 90
Name: 159, dtype: object)
<class 'pandas.core.series.Series'>
(160, Team              FLA
League             NL
Year             2007
RS                790
RA                891
W                  71
OBP             0.336
SLG             0.448
BA              0.267
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.364
OSLG            0.442
WP               0.44
RD               -101
Name: 160, dtype: object)
<class 'pandas.core.series.Series'>
(161, Team              HOU
League             NL
Year             2007
RS                723
RA                813
W                  73
OBP              0.33
SLG             0.412
BA               0.26
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.337
OSLG            0.454
WP               0.45
RD                -90
Name: 161, dtype: object)
<class 'pandas.core.series.Series'>
(162, Team              KCR
League             AL
Year             2007
RS                706
RA                778
W                  69
OBP             0.322
SLG             0.388
BA              0.261
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.339
OSLG            0.445
WP               0.43
RD                -72
Name: 162, dtype: object)
<class 'pandas.core.series.Series'>
(163, Team              LAA
League             AL
Year             2007
RS                822
RA                731
W                  94
OBP             0.345
SLG             0.417
BA              0.284
Playoffs            1
RankSeason          2
RankPlayoffs        4
G                 162
OOBP            0.328
OSLG            0.412
WP               0.58
RD                 91
Name: 163, dtype: object)
<class 'pandas.core.series.Series'>
(164, Team              LAD
League             NL
Year             2007
RS                735
RA                727
W                  82
OBP             0.337
SLG             0.406
BA              0.275
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.326
OSLG            0.399
WP               0.51
RD                  8
Name: 164, dtype: object)
<class 'pandas.core.series.Series'>
(165, Team              MIL
League             NL
Year             2007
RS                801
RA                776
W                  83
OBP             0.329
SLG             0.456
BA              0.262
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.333
OSLG            0.422
WP               0.51
RD                 25
Name: 165, dtype: object)
<class 'pandas.core.series.Series'>
(166, Team              MIN
League             AL
Year             2007
RS                718
RA                725
W                  79
OBP              0.33
SLG             0.391
BA              0.264
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.324
OSLG            0.431
WP               0.49
RD                 -7
Name: 166, dtype: object)
<class 'pandas.core.series.Series'>
(167, Team              NYM
League             NL
Year             2007
RS                804
RA                750
W                  88
OBP             0.342
SLG             0.432
BA              0.275
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.329
OSLG            0.409
WP               0.54
RD                 54
Name: 167, dtype: object)
<class 'pandas.core.series.Series'>
(168, Team              NYY
League             AL
Year             2007
RS                968
RA                777
W                  94
OBP             0.366
SLG             0.463
BA               0.29
Playoffs            1
RankSeason          2
RankPlayoffs        4
G                 162
OOBP             0.34
OSLG            0.417
WP               0.58
RD                191
Name: 168, dtype: object)
<class 'pandas.core.series.Series'>
(169, Team              OAK
League             AL
Year             2007
RS                741
RA                758
W                  76
OBP             0.338
SLG             0.407
BA              0.256
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.329
OSLG            0.404
WP               0.47
RD                -17
Name: 169, dtype: object)
<class 'pandas.core.series.Series'>
(170, Team              PHI
League             NL
Year             2007
RS                892
RA                821
W                  89
OBP             0.354
SLG             0.458
BA              0.274
Playoffs            1
RankSeason          4
RankPlayoffs        4
G                 162
OOBP            0.346
OSLG            0.451
WP               0.55
RD                 71

Name: 170, dtype: object)
<class 'pandas.core.series.Series'>
(171, Team              PIT
League             NL
Year             2007
RS                724
RA                846
W                  68
OBP             0.325
SLG             0.411
BA              0.263
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.352
OSLG            0.447
WP               0.42
RD               -122
Name: 171, dtype: object)
<class 'pandas.core.series.Series'>
(172, Team              SDP
League             NL
Year             2007
RS                741
RA                666
W                  89
OBP             0.322
SLG             0.411
BA              0.251
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 163
OOBP            0.311
OSLG            0.374
WP               0.55
RD                 75
Name: 172, dtype: object)
<class 'pandas.core.series.Series'>
(173, Team              SEA
League             AL
Year             2007
RS                794
RA                813
W                  88
OBP             0.337
SLG             0.425
BA              0.287
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.349
OSLG            0.431
WP               0.54
RD                -19
Name: 173, dtype: object)
<class 'pandas.core.series.Series'>
(174, Team              SFG
League             NL
Year             2007
RS                683
RA                720
W                  71
OBP             0.322
SLG             0.387
BA              0.254
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.334
OSLG            0.405
WP               0.44
RD                -37
Name: 174, dtype: object)
<class 'pandas.core.series.Series'>
(175, Team              STL
League             NL
Year             2007
RS                725
RA                829
W                  78
OBP             0.337
SLG             0.405
BA              0.274
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.336
OSLG            0.431
WP               0.48
RD               -104
Name: 175, dtype: object)
<class 'pandas.core.series.Series'>
(176, Team              TBD
League             AL
Year             2007
RS                782
RA                944
W                  66
OBP             0.336
SLG             0.433
BA              0.268
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.358
OSLG            0.467
WP               0.41
RD               -162
Name: 176, dtype: object)
<class 'pandas.core.series.Series'>
(177, Team              TEX
League             AL
Year             2007
RS                816
RA                844
W                  75
OBP             0.328
SLG             0.426
BA              0.263
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.356
OSLG            0.423
WP               0.46
RD                -28
Name: 177, dtype: object)
<class 'pandas.core.series.Series'>
(178, Team              TOR
League             AL
Year             2007
RS                753
RA                699
W                  83
OBP             0.327
SLG             0.419
BA              0.259
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.315
OSLG            0.391
WP               0.51
RD                 54
Name: 178, dtype: object)
<class 'pandas.core.series.Series'>
(179, Team              WSN
League             NL
Year             2007
RS                673
RA                783
W                  73
OBP             0.325
SLG              0.39
BA              0.256
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.339
OSLG            0.433
WP               0.45
RD               -110
Name: 179, dtype: object)
<class 'pandas.core.series.Series'>
(180, Team              ARI
League             NL
Year             2006
RS                773
RA                788
W                  76
OBP             0.331
SLG             0.424
BA              0.267
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.335
OSLG            0.431
WP               0.47
RD                -15
Name: 180, dtype: object)
<class 'pandas.core.series.Series'>
(181, Team              ATL
League             NL
Year             2006
RS                849
RA                805
W                  79
OBP             0.337
SLG             0.455
BA               0.27
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.343
OSLG            0.438
WP               0.49
RD                 44
Name: 181, dtype: object)
<class 'pandas.core.series.Series'>
(182, Team              BAL
League             AL
Year             2006
RS                768
RA                899
W                  70
OBP             0.339
SLG             0.424
BA              0.277
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.357
OSLG            0.462
WP               0.43
RD               -131
Name: 182, dtype: object)
<class 'pandas.core.series.Series'>
(183, Team              BOS
League             AL
Year             2006
RS                820
RA                825
W                  86
OBP             0.351
SLG             0.435
BA              0.269
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.343
OSLG            0.447
WP               0.53
RD                 -5
Name: 183, dtype: object)
<class 'pandas.core.series.Series'>
(184, Team              CHC
League             NL
Year             2006
RS                716
RA                834
W                  66
OBP             0.319
SLG             0.422
BA              0.268
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.342
OSLG            0.431
WP               0.41
RD               -118
Name: 184, dtype: object)
<class 'pandas.core.series.Series'>
(185, Team              CHW
League             AL
Year             2006
RS                868
RA                794
W                  90
OBP             0.342
SLG             0.464
BA               0.28
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.326
OSLG             0.44
WP               0.56
RD                 74
Name: 185, dtype: object)
<class 'pandas.core.series.Series'>
(186, Team              CIN
League             NL
Year             2006
RS                749
RA                801
W                  80
OBP             0.336
SLG             0.432
BA              0.257
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.337
OSLG            0.457
WP               0.49
RD                -52
Name: 186, dtype: object)
<class 'pandas.core.series.Series'>
(187, Team              CLE
League             AL
Year             2006
RS                870
RA                782
W                  78
OBP             0.349
SLG             0.457
BA               0.28
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.335
OSLG            0.431
WP               0.48
RD                 88
Name: 187, dtype: object)
<class 'pandas.core.series.Series'>
(188, Team              COL
League             NL
Year             2006
RS                813
RA                812
W                  76
OBP             0.341
SLG             0.433
BA               0.27
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.346
OSLG            0.438
WP               0.47
RD                  1
Name: 188, dtype: object)
<class 'pandas.core.series.Series'>
(189, Team              DET
League             AL
Year             2006
RS                822
RA                675
W                  95
OBP             0.329
SLG             0.449
BA              0.274
Playoffs            1
RankSeason          3
RankPlayoffs        2
G                 162
OOBP            0.321
OSLG            0.405
WP               0.59
RD                147
Name: 189, dtype: object)
<class 'pandas.core.series.Series'>
(190, Team              FLA
League             NL
Year             2006
RS                758
RA                772
W                  78
OBP             0.331
SLG             0.435
BA              0.264
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.347
OSLG            0.423
WP               0.48
RD                -14
Name: 190, dtype: object)
<class 'pandas.core.series.Series'>
(191, Team              HOU
League             NL
Year             2006
RS                735
RA                719
W                  82
OBP             0.332
SLG             0.409
BA              0.255
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.319
OSLG            0.421
WP               0.51
RD                 16
Name: 191, dtype: object)
<class 'pandas.core.series.Series'>
(192, Team              KCR
League             AL
Year             2006
RS                757
RA                971
W                  62
OBP             0.332
SLG             0.411
BA              0.271
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.367
OSLG            0.476
WP               0.38
RD               -214
Name: 192, dtype: object)
<class 'pandas.core.series.Series'>
(193, Team              LAA
League             AL
Year             2006
RS                766
RA                732
W                  89
OBP             0.334
SLG             0.425
BA              0.274
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.316
OSLG            0.402
WP               0.55
RD                 34
Name: 193, dtype: object)
<class 'pandas.core.series.Series'>
(194, Team              LAD
League             NL
Year             2006
RS                820
RA                751
W                  88
OBP             0.348
SLG             0.432
BA              0.276
Playoffs            1
RankSeason          5
RankPlayoffs        4
G                 162
OOBP             0.33
OSLG            0.418
WP               0.54
RD                 69
Name: 194, dtype: object)
<class 'pandas.core.series.Series'>
(195, Team              MIL
League             NL
Year             2006
RS                730
RA                833
W                  75
OBP             0.327
SLG              0.42
BA              0.258
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.333
OSLG            0.438
WP               0.46
RD               -103
Name: 195, dtype: object)
<class 'pandas.core.series.Series'>
(196, Team              MIN
League             AL
Year             2006
RS                801
RA                683
W                  96
OBP             0.347
SLG             0.425
BA              0.287
Playoffs            1
RankSeason          2
RankPlayoffs        4
G                 162
OOBP            0.312
OSLG            0.423
WP               0.59
RD                118
Name: 196, dtype: object)
<class 'pandas.core.series.Series'>
(197, Team              NYM
League             NL
Year             2006
RS                834
RA                731
W                  97
OBP             0.334
SLG             0.445
BA              0.264
Playoffs            1
RankSeason          1
RankPlayoffs        3
G                 162
OOBP            0.323
OSLG            0.407
WP                0.6
RD                103
Name: 197, dtype: object)
<class 'pandas.core.series.Series'>
(198, Team              NYY
League             AL
Year             2006
RS                930
RA                767
W                  97
OBP             0.363
SLG             0.461
BA              0.285
Playoffs            1
RankSeason          1
RankPlayoffs        4
G                 162
OOBP            0.326
OSLG            0.413
WP                0.6
RD                163
Name: 198, dtype: object)
<class 'pandas.core.series.Series'>
(199, Team              OAK
League             AL
Year             2006
RS                771
RA                727
W                  93
OBP              0.34
SLG             0.412
BA               0.26
Playoffs            1
RankSeason          4
RankPlayoffs        3
G                 162
OOBP            0.338
OSLG            0.422
WP               0.57
RD                 44
Name: 199, dtype: object)
<class 'pandas.core.series.Series'>
(200, Team              PHI
League             NL
Year             2006
RS                865
RA                812
W                  85
OBP             0.347
SLG             0.447
BA              0.267
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.339
OSLG             0.46
WP               0.52
RD                 53
Name: 200, dtype: object)
<class 'pandas.core.series.Series'>
(201, Team              PIT
League             NL
Year             2006
RS                691
RA                797
W                  67
OBP             0.327
SLG             0.397
BA              0.263
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.357
OSLG            0.431
WP               0.41
RD               -106
Name: 201, dtype: object)
<class 'pandas.core.series.Series'>
(202, Team              SDP
League             NL
Year             2006
RS                731
RA                679
W                  88
OBP             0.332
SLG             0.416
BA              0.263
Playoffs            1
RankSeason          5
RankPlayoffs        4
G                 162
OOBP            0.312
OSLG            0.404
WP               0.54
RD                 52
Name: 202, dtype: object)
<class 'pandas.core.series.Series'>
(203, Team              SEA
League             AL
Year             2006
RS                756
RA                792
W                  78
OBP             0.325
SLG             0.424
BA              0.272
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.337
OSLG            0.432
WP               0.48
RD                -36
Name: 203, dtype: object)
<class 'pandas.core.series.Series'>
(204, Team              SFG
League             NL
Year             2006
RS                746
RA                790
W                  76
OBP             0.324
SLG             0.422
BA              0.259
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 161
OOBP            0.337
OSLG            0.415
WP               0.47
RD                -44
Name: 204, dtype: object)
<class 'pandas.core.series.Series'>
(205, Team              STL
League             NL
Year             2006
RS                781
RA                762
W                  83
OBP             0.337
SLG             0.431
BA              0.269
Playoffs            1
RankSeason          6
RankPlayoffs        1
G                 161
OOBP            0.337
OSLG            0.443
WP               0.52
RD                 19
Name: 205, dtype: object)
<class 'pandas.core.series.Series'>
(206, Team              TBD
League             AL
Year             2006
RS                689
RA                856
W                  61
OBP             0.314
SLG              0.42
BA              0.255
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.358
OSLG            0.452
WP               0.38
RD               -167
Name: 206, dtype: object)
<class 'pandas.core.series.Series'>
(207, Team              TEX
League             AL
Year             2006
RS                835
RA                784
W                  80
OBP             0.338
SLG             0.446
BA              0.278
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.341
OSLG            0.424
WP               0.49
RD                 51
Name: 207, dtype: object)
<class 'pandas.core.series.Series'>
(208, Team              TOR
League             AL
Year             2006
RS                809
RA                754
W                  87
OBP             0.348
SLG             0.463
BA              0.284
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.328
OSLG            0.422
WP               0.54
RD                 55
Name: 208, dtype: object)
<class 'pandas.core.series.Series'>
(209, Team              WSN
League             NL
Year             2006
RS                746
RA                872
W                  71
OBP             0.338
SLG             0.418
BA              0.262
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.349
OSLG            0.447
WP               0.44
RD               -126
Name: 209, dtype: object)
<class 'pandas.core.series.Series'>
(210, Team              ARI
League             NL
Year             2005
RS                696
RA                856
W                  77
OBP             0.332
SLG             0.421
BA              0.256
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.345
OSLG            0.455
WP               0.48
RD               -160
Name: 210, dtype: object)
<class 'pandas.core.series.Series'>
(211, Team              ATL
League             NL
Year             2005
RS                769
RA                674
W                  90
OBP             0.333
SLG             0.435
BA              0.265
Playoffs            1
RankSeason          4
RankPlayoffs        4
G                 162
OOBP            0.333
OSLG            0.406
WP               0.56
RD                 95
Name: 211, dtype: object)
<class 'pandas.core.series.Series'>
(212, Team              BAL
League             AL
Year             2005
RS                729
RA                800
W                  74
OBP             0.327
SLG             0.434
BA              0.269
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.336
OSLG            0.416
WP               0.46
RD                -71
Name: 212, dtype: object)
<class 'pandas.core.series.Series'>
(213, Team              BOS
League             AL
Year             2005
RS                910
RA                805
W                  95
OBP             0.357
SLG             0.454
BA              0.281
Playoffs            1
RankSeason          3
RankPlayoffs        4
G                 162
OOBP            0.335
OSLG            0.441
WP               0.59
RD                105
Name: 213, dtype: object)
<class 'pandas.core.series.Series'>
(214, Team              CHC
League             NL
Year             2005
RS                703
RA                714
W                  79
OBP             0.324
SLG              0.44
BA               0.27
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.325
OSLG            0.407
WP               0.49
RD                -11
Name: 214, dtype: object)
<class 'pandas.core.series.Series'>
(215, Team              CHW
League             AL
Year             2005
RS                741
RA                645
W                  99
OBP             0.322
SLG             0.425
BA              0.262
Playoffs            1
RankSeason          2
RankPlayoffs        1
G                 162
OOBP             0.31
OSLG            0.397
WP               0.61
RD                 96
Name: 215, dtype: object)
<class 'pandas.core.series.Series'>
(216, Team              CIN

<class 'pandas.core.series.Series'>
(316, Team              MIN
League             AL
Year             2002
RS                768
RA                712
W                  94
OBP             0.332
SLG             0.437
BA              0.272
Playoffs            1
RankSeason          7
RankPlayoffs        3
G                 161
OOBP            0.318
OSLG            0.421
WP               0.58
RD                 56
Name: 316, dtype: object)
<class 'pandas.core.series.Series'>
(317, Team              MON
League             NL
Year             2002
RS                735
RA                718
W                  83
OBP             0.334
SLG             0.418
BA              0.261
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.329
OSLG            0.421
WP               0.51
RD                 17
Name: 317, dtype: object)
<class 'pandas.core.series.Series'>
(318, Team              NYM
League             NL
Year             2002
RS                690
RA                703
W                  75
OBP             0.322
SLG             0.395
BA              0.256
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 161
OOBP            0.327
OSLG            0.403
WP               0.47
RD                -13
Name: 318, dtype: object)
<class 'pandas.core.series.Series'>
(319, Team              NYY
League             AL
Year             2002
RS                897
RA                697
W                 103
OBP             0.354
SLG             0.455
BA              0.275
Playoffs            1
RankSeason          1
RankPlayoffs        4
G                 161
OOBP            0.309
OSLG            0.395
WP               0.64
RD                200
Name: 319, dtype: object)
<class 'pandas.core.series.Series'>
(320, Team              OAK
League             AL
Year             2002
RS                800
RA                654
W                 103
OBP             0.339
SLG             0.432
BA              0.261
Playoffs            1
RankSeason          1
RankPlayoffs        4
G                 162
OOBP            0.315
OSLG            0.384
WP               0.64
RD                146
Name: 320, dtype: object)
<class 'pandas.core.series.Series'>
(321, Team              PHI
League             NL
Year             2002
RS                710
RA                724
W                  80
OBP             0.339
SLG             0.422
BA              0.259
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 161
OOBP            0.328
OSLG            0.401
WP                0.5
RD                -14
Name: 321, dtype: object)
<class 'pandas.core.series.Series'>
(322, Team              PIT
League             NL
Year             2002
RS                641
RA                730
W                  72
OBP             0.319
SLG             0.381
BA              0.244
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 161
OOBP            0.342
OSLG            0.423
WP               0.45
RD                -89
Name: 322, dtype: object)
<class 'pandas.core.series.Series'>
(323, Team              SDP
League             NL
Year             2002
RS                662
RA                815
W                  66
OBP             0.321
SLG             0.381
BA              0.253
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.346
OSLG            0.442
WP               0.41
RD               -153
Name: 323, dtype: object)
<class 'pandas.core.series.Series'>
(324, Team              SEA
League             AL
Year             2002
RS                814
RA                699
W                  93
OBP              0.35
SLG             0.419
BA              0.275
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.315
OSLG             0.41
WP               0.57
RD                115
Name: 324, dtype: object)
<class 'pandas.core.series.Series'>
(325, Team              SFG
League             NL
Year             2002
RS                783
RA                616
W                  95
OBP             0.344
SLG             0.442
BA              0.267
Playoffs            1
RankSeason          6
RankPlayoffs        2
G                 162
OOBP            0.319
OSLG            0.372
WP               0.59
RD                167
Name: 325, dtype: object)
<class 'pandas.core.series.Series'>
(326, Team              STL
League             NL
Year             2002
RS                787
RA                648
W                  97
OBP             0.338
SLG             0.425
BA              0.268
Playoffs            1
RankSeason          5
RankPlayoffs        3
G                 162
OOBP            0.323
OSLG            0.386
WP                0.6
RD                139
Name: 326, dtype: object)
<class 'pandas.core.series.Series'>
(327, Team              TBD
League             AL
Year             2002
RS                673
RA                918
W                  55
OBP             0.314
SLG              0.39
BA              0.253
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 161
OOBP            0.357
OSLG            0.463
WP               0.34
RD               -245
Name: 327, dtype: object)
<class 'pandas.core.series.Series'>
(328, Team              TEX
League             AL
Year             2002
RS                843
RA                882
W                  72
OBP             0.338
SLG             0.455
BA              0.269
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.355
OSLG            0.451
WP               0.44
RD                -39
Name: 328, dtype: object)
<class 'pandas.core.series.Series'>
(329, Team              TOR
League             AL
Year             2002
RS                813
RA                828
W                  78
OBP             0.327
SLG              0.43
BA              0.261
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.344
OSLG            0.431
WP               0.48
RD                -15
Name: 329, dtype: object)
<class 'pandas.core.series.Series'>
(330, Team              ANA
League             AL
Year             2001
RS                691
RA                730
W                  75
OBP             0.327
SLG             0.405
BA              0.261
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.331
OSLG            0.412
WP               0.46
RD                -39
Name: 330, dtype: object)
<class 'pandas.core.series.Series'>
(331, Team              ARI
League             NL
Year             2001
RS                818
RA                677
W                  92
OBP             0.341
SLG             0.442
BA              0.267
Playoffs            1
RankSeason          5
RankPlayoffs        1
G                 162
OOBP            0.311
OSLG            0.404
WP               0.57
RD                141
Name: 331, dtype: object)
<class 'pandas.core.series.Series'>
(332, Team              ATL
League             NL
Year             2001
RS                729
RA                643
W                  88
OBP             0.324
SLG             0.412
BA               0.26
Playoffs            1
RankSeason          7
RankPlayoffs        3
G                 162
OOBP            0.314
OSLG            0.384
WP               0.54
RD                 86
Name: 332, dtype: object)
<class 'pandas.core.series.Series'>
(333, Team              BAL
League             AL
Year             2001
RS                687
RA                829
W                  63
OBP             0.319
SLG              0.38
BA              0.248
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.337
OSLG            0.439
WP               0.39
RD               -142
Name: 333, dtype: object)
<class 'pandas.core.series.Series'>
(334, Team              BOS
League             AL
Year             2001
RS                772
RA                745
W                  82
OBP             0.334
SLG             0.439
BA              0.266
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 161
OOBP            0.329
OSLG            0.393
WP               0.51
RD                 27
Name: 334, dtype: object)
<class 'pandas.core.series.Series'>
(335, Team              CHC
League             NL
Year             2001
RS                777
RA                701
W                  88
OBP             0.336
SLG              0.43
BA              0.261
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.321
OSLG            0.398
WP               0.54
RD                 76
Name: 335, dtype: object)
<class 'pandas.core.series.Series'>
(336, Team              CHW
League             AL
Year             2001
RS                798
RA                795
W                  83
OBP             0.334
SLG             0.451
BA              0.268
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.334
OSLG            0.427
WP               0.51
RD                  3
Name: 336, dtype: object)
<class 'pandas.core.series.Series'>
(337, Team              CIN
League             NL
Year             2001
RS                735
RA                850
W                  66
OBP             0.324
SLG             0.419
BA              0.262
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.341
OSLG            0.455
WP               0.41
RD               -115
Name: 337, dtype: object)
<class 'pandas.core.series.Series'>
(338, Team              CLE
League             AL
Year             2001
RS                897
RA                821
W                  91
OBP              0.35
SLG             0.458
BA              0.278
Playoffs            1
RankSeason          6
RankPlayoffs        4
G                 162
OOBP            0.341
OSLG            0.417
WP               0.56
RD                 76
Name: 338, dtype: object)
<class 'pandas.core.series.Series'>
(339, Team              COL
League             NL
Year             2001
RS                923
RA                906
W                  73
OBP             0.354
SLG             0.483
BA              0.292
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP             0.35
OSLG             0.48
WP               0.45
RD                 17
Name: 339, dtype: object)
<class 'pandas.core.series.Series'>
(340, Team              DET
League             AL
Year             2001
RS                724
RA                876
W                  66
OBP              0.32
SLG             0.409
BA               0.26
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.357
OSLG            0.461
WP               0.41
RD               -152
Name: 340, dtype: object)
<class 'pandas.core.series.Series'>
(341, Team              FLA
League             NL
Year             2001
RS                742
RA                744
W                  76
OBP             0.326
SLG             0.423
BA              0.264
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.338
OSLG            0.411
WP               0.47
RD                 -2
Name: 341, dtype: object)
<class 'pandas.core.series.Series'>
(342, Team              HOU
League             NL
Year             2001
RS                847
RA                769
W                  93
OBP             0.347
SLG             0.451
BA              0.271
Playoffs            1
RankSeason          4
RankPlayoffs        4
G                 162
OOBP            0.325
OSLG            0.437
WP               0.57
RD                 78
Name: 342, dtype: object)
<class 'pandas.core.series.Series'>
(343, Team              KCR
League             AL
Year             2001
RS                729
RA                858
W                  65
OBP             0.318
SLG             0.409
BA              0.266
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.348
OSLG             0.45
WP                0.4
RD               -129
Name: 343, dtype: object)
<class 'pandas.core.series.Series'>
(344, Team              LAD
League             NL
Year             2001
RS                758
RA                744
W                  86
OBP             0.323
SLG             0.425
BA              0.255
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.323
OSLG            0.411
WP               0.53
RD                 14
Name: 344, dtype: object)
<class 'pandas.core.series.Series'>
(345, Team              MIL
League             NL
Year             2001
RS                740
RA                806
W                  68
OBP             0.319
SLG             0.426
BA              0.251
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP             0.35
OSLG             0.44
WP               0.42
RD                -66
Name: 345, dtype: object)
<class 'pandas.core.series.Series'>
(346, Team              MIN
League             AL
Year             2001
RS                771
RA                766
W                  85
OBP             0.337
SLG             0.433
BA              0.272
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.325
OSLG            0.437
WP               0.52
RD                  5
Name: 346, dtype: object)
<class 'pandas.core.series.Series'>
(347, Team              MON
League             NL
Year             2001
RS                670
RA                812
W                  68
OBP             0.319
SLG             0.396
BA              0.253
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.339
OSLG            0.441
WP               0.42
RD               -142
Name: 347, dtype: object)
<class 'pandas.core.series.Series'>
(348, Team              NYM
League             NL
Year             2001
RS                642
RA                713
W                  82
OBP             0.323
SLG             0.387
BA              0.249
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.314
OSLG            0.419
WP               0.51
RD                -71
Name: 348, dtype: object)
<class 'pandas.core.series.Series'>
(349, Team              NYY
League             AL
Year             2001
RS                804
RA                713
W                  95
OBP             0.334
SLG             0.435
BA              0.267
Playoffs            1
RankSeason          3
RankPlayoffs        2
G                 161
OOBP            0.318
OSLG            0.398
WP               0.59
RD                 91
Name: 349, dtype: object)
<class 'pandas.core.series.Series'>
(350, Team              OAK
League             AL
Year             2001
RS                884
RA                645
W                 102
OBP             0.345
SLG             0.439
BA              0.264
Playoffs            1
RankSeason          2
RankPlayoffs        4
G                 162
OOBP            0.308
OSLG             0.38
WP               0.63
RD                239
Name: 350, dtype: object)
<class 'pandas.core.series.Series'>
(351, Team              PHI
League             NL
Year             2001
RS                746
RA                719
W                  86
OBP             0.329
SLG             0.414
BA               0.26
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.329
OSLG            0.424
WP               0.53
RD                 27
Name: 351, dtype: object)
<class 'pandas.core.series.Series'>
(352, Team              PIT
League             NL
Year             2001
RS                657
RA                858
W                  62
OBP             0.313
SLG             0.393
BA              0.247
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.344
OSLG            0.433
WP               0.38
RD               -201
Name: 352, dtype: object)
<class 'pandas.core.series.Series'>
(353, Team              SDP
League             NL
Year             2001
RS                789
RA                812
W                  79
OBP             0.336
SLG             0.399
BA              0.252
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP             0.33
OSLG             0.45
WP               0.49
RD                -23
Name: 353, dtype: object)
<class 'pandas.core.series.Series'>
(354, Team              SEA
League             AL
Year             2001
RS                927
RA                627
W                 116
OBP              0.36
SLG             0.445
BA              0.288
Playoffs            1
RankSeason          1
RankPlayoffs        3
G                 162
OOBP            0.301
OSLG            0.378
WP               0.72
RD                300
Name: 354, dtype: object)
<class 'pandas.core.series.Series'>
(355, Team              SFG
League             NL
Year             2001
RS                799
RA                748
W                  90
OBP             0.342
SLG              0.46
BA              0.266
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.329
OSLG            0.404
WP               0.56
RD                 51
Name: 355, dtype: object)
<class 'pandas.core.series.Series'>
(356, Team              STL
League             NL
Year             2001
RS                814
RA                684
W                  93
OBP             0.339
SLG             0.441
BA               0.27
Playoffs            1
RankSeason          4
RankPlayoffs        4
G                 162
OOBP            0.328
OSLG            0.428
WP               0.57
RD                130
Name: 356, dtype: object)
<class 'pandas.core.series.Series'>
(357, Team              TBD
League             AL
Year             2001
RS                672
RA                887
W                  62
OBP              0.32
SLG             0.388
BA              0.258
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.345
OSLG            0.452
WP               0.38
RD               -215
Name: 357, dtype: object)
<class 'pandas.core.series.Series'>
(358, Team              TEX
League             AL
Year             2001
RS                890
RA                968
W                  73
OBP             0.344
SLG             0.471
BA              0.275
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.362
OSLG            0.494
WP               0.45
RD                -78
Name: 358, dtype: object)
<class 'pandas.core.series.Series'>
(359, Team              TOR
League             AL
Year             2001
RS                767
RA                753
W                  80
OBP             0.325
SLG              0.43
BA              0.263
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.339
OSLG            0.435
WP               0.49
RD                 14
Name: 359, dtype: object)
<class 'pandas.core.series.Series'>
(360, Team              ANA
League             AL
Year             2000
RS                864
RA                869
W                  82
OBP             0.352
SLG             0.472
BA               0.28
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.351
OSLG            0.453
WP               0.51
RD                 -5
Name: 360, dtype: object)
<class 'pandas.core.series.Series'>
(361, Team              ARI
League             NL
Year             2000

Name: 390, dtype: object)
<class 'pandas.core.series.Series'>
(391, Team              ARI
League             NL
Year             1999
RS                908
RA                676
W                 100
OBP             0.347
SLG             0.459
BA              0.277
Playoffs            1
RankSeason          2
RankPlayoffs        4
G                 162
OOBP             0.32
OSLG            0.402
WP               0.62
RD                232
Name: 391, dtype: object)
<class 'pandas.core.series.Series'>
(392, Team              ATL
League             NL
Year             1999
RS                840
RA                661
W                 103
OBP             0.341
SLG             0.436
BA              0.266
Playoffs            1
RankSeason          1
RankPlayoffs        2
G                 162
OOBP            0.314
OSLG            0.377
WP               0.64
RD                179
Name: 392, dtype: object)
<class 'pandas.core.series.Series'>
(393, Team              BAL
League             AL
Year             1999
RS                851
RA                815
W                  78
OBP             0.353
SLG             0.447
BA              0.279
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP             0.35
OSLG            0.441
WP               0.48
RD                 36
Name: 393, dtype: object)
<class 'pandas.core.series.Series'>
(394, Team              BOS
League             AL
Year             1999
RS                836
RA                718
W                  94
OBP              0.35
SLG             0.448
BA              0.278
Playoffs            1
RankSeason          6
RankPlayoffs        3
G                 162
OOBP            0.315
OSLG            0.398
WP               0.58
RD                118
Name: 394, dtype: object)
<class 'pandas.core.series.Series'>
(395, Team              CHC
League             NL
Year             1999
RS                747
RA                920
W                  67
OBP             0.329
SLG              0.42
BA              0.257
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.346
OSLG            0.467
WP               0.41
RD               -173
Name: 395, dtype: object)
<class 'pandas.core.series.Series'>
(396, Team              CHW
League             AL
Year             1999
RS                777
RA                870
W                  75
OBP             0.337
SLG             0.429
BA              0.277
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.353
OSLG            0.447
WP               0.46
RD                -93
Name: 396, dtype: object)
<class 'pandas.core.series.Series'>
(397, Team              CIN
League             NL
Year             1999
RS                865
RA                711
W                  96
OBP             0.341
SLG             0.451
BA              0.272
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 163
OOBP            0.324
OSLG            0.411
WP               0.59
RD                154
Name: 397, dtype: object)
<class 'pandas.core.series.Series'>
(398, Team              CLE
League             AL
Year             1999
RS               1009
RA                860
W                  97
OBP             0.373
SLG             0.467
BA              0.289
Playoffs            1
RankSeason          4
RankPlayoffs        4
G                 162
OOBP            0.347
OSLG            0.439
WP                0.6
RD                149
Name: 398, dtype: object)
<class 'pandas.core.series.Series'>
(399, Team              COL
League             NL
Year             1999
RS                906
RA               1028
W                  72
OBP             0.348
SLG             0.472
BA              0.288
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.384
OSLG            0.499
WP               0.44
RD               -122
Name: 399, dtype: object)
<class 'pandas.core.series.Series'>
(400, Team              DET
League             AL
Year             1999
RS                747
RA                882
W                  69
OBP             0.326
SLG             0.443
BA              0.261
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 161
OOBP            0.349
OSLG            0.451
WP               0.43
RD               -135
Name: 400, dtype: object)
<class 'pandas.core.series.Series'>
(401, Team              FLA
League             NL
Year             1999
RS                691
RA                852
W                  64
OBP             0.325
SLG             0.395
BA              0.263
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.359
OSLG             0.44
WP                0.4
RD               -161
Name: 401, dtype: object)
<class 'pandas.core.series.Series'>
(402, Team              HOU
League             NL
Year             1999
RS                823
RA                675
W                  97
OBP             0.355
SLG              0.42
BA              0.267
Playoffs            1
RankSeason          4
RankPlayoffs        4
G                 162
OOBP            0.326
OSLG            0.397
WP                0.6
RD                148
Name: 402, dtype: object)
<class 'pandas.core.series.Series'>
(403, Team              KCR
League             AL
Year             1999
RS                856
RA                921
W                  64
OBP             0.348
SLG             0.433
BA              0.282
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 161
OOBP            0.365
OSLG            0.454
WP                0.4
RD                -65
Name: 403, dtype: object)
<class 'pandas.core.series.Series'>
(404, Team              LAD
League             NL
Year             1999
RS                793
RA                787
W                  77
OBP             0.339
SLG              0.42
BA              0.266
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.336
OSLG            0.422
WP               0.48
RD                  6
Name: 404, dtype: object)
<class 'pandas.core.series.Series'>
(405, Team              MIL
League             NL
Year             1999
RS                815
RA                886
W                  74
OBP             0.353
SLG             0.426
BA              0.273
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 161
OOBP            0.356
OSLG            0.457
WP               0.46
RD                -71
Name: 405, dtype: object)
<class 'pandas.core.series.Series'>
(406, Team              MIN
League             AL
Year             1999
RS                686
RA                845
W                  63
OBP             0.328
SLG             0.384
BA              0.264
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 161
OOBP            0.342
OSLG            0.465
WP               0.39
RD               -159
Name: 406, dtype: object)
<class 'pandas.core.series.Series'>
(407, Team              MON
League             NL
Year             1999
RS                718
RA                853
W                  68
OBP             0.323
SLG             0.427
BA              0.265
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.342
OSLG            0.418
WP               0.42
RD               -135
Name: 407, dtype: object)
<class 'pandas.core.series.Series'>
(408, Team              NYM
League             NL
Year             1999
RS                853
RA                711
W                  97
OBP             0.363
SLG             0.434
BA              0.279
Playoffs            1
RankSeason          4
RankPlayoffs        3
G                 163
OOBP            0.331
OSLG            0.418
WP                0.6
RD                142
Name: 408, dtype: object)
<class 'pandas.core.series.Series'>
(409, Team              NYY
League             AL
Year             1999
RS                900
RA                731
W                  98
OBP             0.366
SLG             0.453
BA              0.282
Playoffs            1
RankSeason          3
RankPlayoffs        1
G                 162
OOBP            0.329
OSLG              0.4
WP                0.6
RD                169
Name: 409, dtype: object)
<class 'pandas.core.series.Series'>
(410, Team              OAK
League             AL
Year             1999
RS                893
RA                846
W                  87
OBP             0.355
SLG             0.446
BA              0.259
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.344
OSLG            0.428
WP               0.54
RD                 47
Name: 410, dtype: object)
<class 'pandas.core.series.Series'>
(411, Team              PHI
League             NL
Year             1999
RS                841
RA                846
W                  77
OBP             0.351
SLG             0.431
BA              0.275
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.347
OSLG            0.447
WP               0.48
RD                 -5
Name: 411, dtype: object)
<class 'pandas.core.series.Series'>
(412, Team              PIT
League             NL
Year             1999
RS                775
RA                782
W                  78
OBP             0.334
SLG             0.419
BA              0.259
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 161
OOBP            0.343
OSLG             0.42
WP               0.48
RD                 -7
Name: 412, dtype: object)
<class 'pandas.core.series.Series'>
(413, Team              SDP
League             NL
Year             1999
RS                710
RA                781
W                  74
OBP             0.332
SLG             0.393
BA              0.252
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.333
OSLG             0.43
WP               0.46
RD                -71
Name: 413, dtype: object)
<class 'pandas.core.series.Series'>
(414, Team              SEA
League             AL
Year             1999
RS                859
RA                905
W                  79
OBP             0.343
SLG             0.455
BA              0.269
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.368
OSLG            0.454
WP               0.49
RD                -46
Name: 414, dtype: object)
<class 'pandas.core.series.Series'>
(415, Team              SFG
League             NL
Year             1999
RS                872
RA                831
W                  86
OBP             0.356
SLG             0.434
BA              0.271
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.345
OSLG            0.423
WP               0.53
RD                 41
Name: 415, dtype: object)
<class 'pandas.core.series.Series'>
(416, Team              STL
League             NL
Year             1999
RS                809
RA                838
W                  75
OBP             0.338
SLG             0.426
BA              0.262
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 161
OOBP            0.355
OSLG            0.427
WP               0.47
RD                -29
Name: 416, dtype: object)
<class 'pandas.core.series.Series'>
(417, Team              TBD
League             AL
Year             1999
RS                772
RA                913
W                  69
OBP             0.343
SLG             0.411
BA              0.274
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.371
OSLG            0.448
WP               0.43
RD               -141
Name: 417, dtype: object)
<class 'pandas.core.series.Series'>
(418, Team              TEX
League             AL
Year             1999
RS                945
RA                859
W                  95
OBP             0.361
SLG             0.479
BA              0.293
Playoffs            1
RankSeason          5
RankPlayoffs        4
G                 162
OOBP            0.346
OSLG            0.459
WP               0.59
RD                 86
Name: 418, dtype: object)
<class 'pandas.core.series.Series'>
(419, Team              TOR
League             AL
Year             1999
RS                883
RA                862
W                  84
OBP             0.352
SLG             0.457
BA               0.28
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP            0.353
OSLG            0.456
WP               0.52
RD                 21
Name: 419, dtype: object)
<class 'pandas.core.series.Series'>
(420, Team              ANA
League             AL
Year             1998
RS                787
RA                783
W                  85
OBP             0.335
SLG             0.415
BA              0.272
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.52
RD                  4
Name: 420, dtype: object)
<class 'pandas.core.series.Series'>
(421, Team              ARI
League             NL
Year             1998
RS                665
RA                812
W                  65
OBP             0.314
SLG             0.393
BA              0.246
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP                0.4
RD               -147
Name: 421, dtype: object)
<class 'pandas.core.series.Series'>
(422, Team              ATL
League             NL
Year             1998
RS                826
RA                581
W                 106
OBP             0.342
SLG             0.453
BA              0.272
Playoffs            1
RankSeason          2
RankPlayoffs        3
G                 162
OOBP              NaN
OSLG              NaN
WP               0.65
RD                245
Name: 422, dtype: object)
<class 'pandas.core.series.Series'>
(423, Team              BAL
League             AL
Year             1998
RS                817
RA                785
W                  79
OBP             0.347
SLG             0.447
BA              0.273
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.49
RD                 32
Name: 423, dtype: object)
<class 'pandas.core.series.Series'>
(424, Team              BOS
League             AL
Year             1998
RS                876
RA                729
W                  92
OBP             0.348
SLG             0.463
BA               0.28
Playoffs            1
RankSeason          5
RankPlayoffs        4
G                 162
OOBP              NaN
OSLG              NaN
WP               0.57
RD                147
Name: 424, dtype: object)
<class 'pandas.core.series.Series'>
(425, Team              CHC
League             NL
Year             1998
RS                831
RA                792
W                  90
OBP             0.337
SLG             0.433
BA              0.264
Playoffs            1
RankSeason          6
RankPlayoffs        4
G                 163
OOBP              NaN
OSLG              NaN
WP               0.55
RD                 39
Name: 425, dtype: object)
<class 'pandas.core.series.Series'>
(426, Team              CHW
League             AL
Year             1998
RS                861
RA                931
W                  80
OBP             0.339
SLG             0.444
BA              0.271
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 163
OOBP              NaN
OSLG              NaN
WP               0.49
RD                -70
Name: 426, dtype: object)
<class 'pandas.core.series.Series'>
(427, Team              CIN
League             NL
Year             1998
RS                750
RA                760
W                  77
OBP             0.337
SLG             0.402
BA              0.262
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.48
RD                -10
Name: 427, dtype: object)
<class 'pandas.core.series.Series'>
(428, Team              CLE
League             AL
Year             1998
RS                850
RA                779
W                  89
OBP             0.347
SLG             0.448
BA              0.272
Playoffs            1
RankSeason          7
RankPlayoffs        3
G                 162
OOBP              NaN
OSLG              NaN
WP               0.55
RD                 71
Name: 428, dtype: object)
<class 'pandas.core.series.Series'>
(429, Team              COL
League             NL
Year             1998
RS                826
RA                855
W                  77
OBP             0.347
SLG             0.461
BA              0.291
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.48
RD                -29
Name: 429, dtype: object)
<class 'pandas.core.series.Series'>
(430, Team              DET
League             AL
Year             1998
RS                722
RA                863
W                  65
OBP             0.323
SLG             0.415
BA              0.264
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP                0.4
RD               -141
Name: 430, dtype: object)
<class 'pandas.core.series.Series'>
(431, Team              FLA
League             NL
Year             1998
RS                667
RA                923
W                  54
OBP             0.317
SLG             0.373
BA              0.248
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.33
RD               -256
Name: 431, dtype: object)
<class 'pandas.core.series.Series'>
(432, Team              HOU
League             NL
Year             1998
RS                874
RA                620
W                 102
OBP             0.356
SLG             0.436
BA               0.28
Playoffs            1
RankSeason          3
RankPlayoffs        4
G                 162
OOBP              NaN
OSLG              NaN
WP               0.63
RD                254
Name: 432, dtype: object)
<class 'pandas.core.series.Series'>
(433, Team              KCR
League             AL
Year             1998
RS                714
RA                899
W                  72
OBP             0.324
SLG             0.399
BA              0.263
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 161
OOBP              NaN
OSLG              NaN
WP               0.45
RD               -185
Name: 433, dtype: object)
<class 'pandas.core.series.Series'>
(434, Team              LAD
League             NL
Year             1998
RS                669
RA                678
W                  83
OBP              0.31
SLG             0.387
BA              0.252
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.51
RD                 -9
Name: 434, dtype: object)
<class 'pandas.core.series.Series'>
(435, Team              MIL
League             NL
Year             1998
RS                707
RA                812
W                  74
OBP              0.33
SLG             0.396
BA               0.26
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.46
RD               -105
Name: 435, dtype: object)
<class 'pandas.core.series.Series'>
(436, Team              MIN

(565, Team              CHW
League             AL
Year             1991
RS                758
RA                681
W                  87
OBP             0.336
SLG             0.391
BA              0.262
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.54
RD                 77
Name: 565, dtype: object)
<class 'pandas.core.series.Series'>
(566, Team              CIN
League             NL
Year             1991
RS                689
RA                691
W                  74
OBP              0.32
SLG             0.403
BA              0.258
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.46
RD                 -2
Name: 566, dtype: object)
<class 'pandas.core.series.Series'>
(567, Team              CLE
League             AL
Year             1991
RS                576
RA                759
W                  57
OBP             0.313
SLG              0.35
BA              0.254
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.35
RD               -183
Name: 567, dtype: object)
<class 'pandas.core.series.Series'>
(568, Team              DET
League             AL
Year             1991
RS                817
RA                794
W                  84
OBP             0.333
SLG             0.416
BA              0.247
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.52
RD                 23
Name: 568, dtype: object)
<class 'pandas.core.series.Series'>
(569, Team              HOU
League             NL
Year             1991
RS                605
RA                717
W                  65
OBP             0.309
SLG             0.347
BA              0.244
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP                0.4
RD               -112
Name: 569, dtype: object)
<class 'pandas.core.series.Series'>
(570, Team              KCR
League             AL
Year             1991
RS                727
RA                722
W                  82
OBP             0.328
SLG             0.394
BA              0.264
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.51
RD                  5
Name: 570, dtype: object)
<class 'pandas.core.series.Series'>
(571, Team              LAD
League             NL
Year             1991
RS                665
RA                565
W                  93
OBP             0.326
SLG             0.359
BA              0.253
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.57
RD                100
Name: 571, dtype: object)
<class 'pandas.core.series.Series'>
(572, Team              MIL
League             AL
Year             1991
RS                799
RA                744
W                  83
OBP             0.336
SLG             0.396
BA              0.271
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.51
RD                 55
Name: 572, dtype: object)
<class 'pandas.core.series.Series'>
(573, Team              MIN
League             AL
Year             1991
RS                776
RA                652
W                  95
OBP             0.344
SLG              0.42
BA               0.28
Playoffs            1
RankSeason          2
RankPlayoffs        1
G                 162
OOBP              NaN
OSLG              NaN
WP               0.59
RD                124
Name: 573, dtype: object)
<class 'pandas.core.series.Series'>
(574, Team              MON
League             NL
Year             1991
RS                579
RA                655
W                  71
OBP             0.308
SLG             0.357
BA              0.246
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 161
OOBP              NaN
OSLG              NaN
WP               0.44
RD                -76
Name: 574, dtype: object)
<class 'pandas.core.series.Series'>
(575, Team              NYM
League             NL
Year             1991
RS                640
RA                646
W                  77
OBP             0.317
SLG             0.365
BA              0.244
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 161
OOBP              NaN
OSLG              NaN
WP               0.48
RD                 -6
Name: 575, dtype: object)
<class 'pandas.core.series.Series'>
(576, Team              NYY
League             AL
Year             1991
RS                674
RA                777
W                  71
OBP             0.316
SLG             0.387
BA              0.256
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.44
RD               -103
Name: 576, dtype: object)
<class 'pandas.core.series.Series'>
(577, Team              OAK
League             AL
Year             1991
RS                760
RA                776
W                  84
OBP             0.331
SLG             0.389
BA              0.248
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.52
RD                -16
Name: 577, dtype: object)
<class 'pandas.core.series.Series'>
(578, Team              PHI
League             NL
Year             1991
RS                629
RA                680
W                  78
OBP             0.303
SLG             0.358
BA              0.241
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.48
RD                -51
Name: 578, dtype: object)
<class 'pandas.core.series.Series'>
(579, Team              PIT
League             NL
Year             1991
RS                768
RA                632
W                  98
OBP             0.338
SLG             0.398
BA              0.263
Playoffs            1
RankSeason          1
RankPlayoffs        3
G                 162
OOBP              NaN
OSLG              NaN
WP                0.6
RD                136
Name: 579, dtype: object)
<class 'pandas.core.series.Series'>
(580, Team              SDP
League             NL
Year             1991
RS                636
RA                646
W                  84
OBP              0.31
SLG             0.362
BA              0.244
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.52
RD                -10
Name: 580, dtype: object)
<class 'pandas.core.series.Series'>
(581, Team              SEA
League             AL
Year             1991
RS                702
RA                674
W                  83
OBP             0.328
SLG             0.383
BA              0.255
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.51
RD                 28
Name: 581, dtype: object)
<class 'pandas.core.series.Series'>
(582, Team              SFG
League             NL
Year             1991
RS                649
RA                697
W                  75
OBP             0.309
SLG             0.381
BA              0.246
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.46
RD                -48
Name: 582, dtype: object)
<class 'pandas.core.series.Series'>
(583, Team              STL
League             NL
Year             1991
RS                651
RA                648
W                  84
OBP             0.322
SLG             0.357
BA              0.255
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.52
RD                  3
Name: 583, dtype: object)
<class 'pandas.core.series.Series'>
(584, Team              TEX
League             AL
Year             1991
RS                829
RA                814
W                  85
OBP             0.341
SLG             0.424
BA               0.27
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.52
RD                 15
Name: 584, dtype: object)
<class 'pandas.core.series.Series'>
(585, Team              TOR
League             AL
Year             1991
RS                684
RA                622
W                  91
OBP             0.322
SLG               0.4
BA              0.257
Playoffs            1
RankSeason          4
RankPlayoffs        3
G                 162
OOBP              NaN
OSLG              NaN
WP               0.56
RD                 62
Name: 585, dtype: object)
<class 'pandas.core.series.Series'>
(586, Team              ATL
League             NL
Year             1990
RS                682
RA                821
W                  65
OBP             0.311
SLG             0.396
BA               0.25
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP                0.4
RD               -139
Name: 586, dtype: object)
<class 'pandas.core.series.Series'>
(587, Team              BAL
League             AL
Year             1990
RS                669
RA                698
W                  76
OBP              0.33
SLG              0.37
BA              0.245
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 161
OOBP              NaN
OSLG              NaN
WP               0.47
RD                -29
Name: 587, dtype: object)
<class 'pandas.core.series.Series'>
(588, Team              BOS
League             AL
Year             1990
RS                699
RA                664
W                  88
OBP             0.344
SLG             0.395
BA              0.272
Playoffs            1
RankSeason          4
RankPlayoffs        3
G                 162
OOBP              NaN
OSLG              NaN
WP               0.54
RD                 35
Name: 588, dtype: object)
<class 'pandas.core.series.Series'>
(589, Team              CAL
League             AL
Year             1990
RS                690
RA                706
W                  80
OBP             0.329
SLG             0.391
BA               0.26
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.49
RD                -16
Name: 589, dtype: object)
<class 'pandas.core.series.Series'>
(590, Team              CHC
League             NL
Year             1990
RS                690
RA                774
W                  77
OBP             0.314
SLG             0.392
BA              0.263
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.48
RD                -84
Name: 590, dtype: object)
<class 'pandas.core.series.Series'>
(591, Team              CHW
League             AL
Year             1990
RS                682
RA                633
W                  94
OBP              0.32
SLG             0.379
BA              0.258
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.58
RD                 49
Name: 591, dtype: object)
<class 'pandas.core.series.Series'>
(592, Team              CIN
League             NL
Year             1990
RS                693
RA                597
W                  91
OBP             0.325
SLG             0.399
BA              0.265
Playoffs            1
RankSeason          3
RankPlayoffs        1
G                 162
OOBP              NaN
OSLG              NaN
WP               0.56
RD                 96
Name: 592, dtype: object)
<class 'pandas.core.series.Series'>
(593, Team              CLE
League             AL
Year             1990
RS                732
RA                737
W                  77
OBP             0.324
SLG             0.391
BA              0.267
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.48
RD                 -5
Name: 593, dtype: object)
<class 'pandas.core.series.Series'>
(594, Team              DET
League             AL
Year             1990
RS                750
RA                754
W                  79
OBP             0.337
SLG             0.409
BA              0.259
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.49
RD                 -4
Name: 594, dtype: object)
<class 'pandas.core.series.Series'>
(595, Team              HOU
League             NL
Year             1990
RS                573
RA                656
W                  75
OBP             0.313
SLG             0.345
BA              0.242
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.46
RD                -83
Name: 595, dtype: object)
<class 'pandas.core.series.Series'>
(596, Team              KCR
League             AL
Year             1990
RS                707
RA                709
W                  75
OBP             0.328
SLG             0.395
BA              0.267
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 161
OOBP              NaN
OSLG              NaN
WP               0.47
RD                 -2
Name: 596, dtype: object)
<class 'pandas.core.series.Series'>
(597, Team              LAD
League             NL
Year             1990
RS                728
RA                685
W                  86
OBP             0.328
SLG             0.382
BA              0.262
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.53
RD                 43
Name: 597, dtype: object)
<class 'pandas.core.series.Series'>
(598, Team              MIL
League             AL
Year             1990
RS                732
RA                760
W                  74
OBP              0.32
SLG             0.384
BA              0.256
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.46
RD                -28
Name: 598, dtype: object)
<class 'pandas.core.series.Series'>
(599, Team              MIN
League             AL
Year             1990
RS                666
RA                729
W                  74
OBP             0.324
SLG             0.385
BA              0.265
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.46
RD                -63
Name: 599, dtype: object)
<class 'pandas.core.series.Series'>
(600, Team              MON
League             NL
Year             1990
RS                662
RA                598
W                  85
OBP             0.322
SLG              0.37
BA               0.25
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.52
RD                 64
Name: 600, dtype: object)
<class 'pandas.core.series.Series'>
(601, Team              NYM
League             NL
Year             1990
RS                775
RA                613
W                  91
OBP             0.323
SLG             0.408
BA              0.256
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.56
RD                162
Name: 601, dtype: object)
<class 'pandas.core.series.Series'>
(602, Team              NYY
League             AL
Year             1990
RS                603
RA                749
W                  67
OBP               0.3
SLG             0.366
BA              0.241
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.41
RD               -146
Name: 602, dtype: object)
<class 'pandas.core.series.Series'>
(603, Team              OAK
League             AL
Year             1990
RS                733
RA                570
W                 103
OBP             0.336
SLG             0.391
BA              0.254
Playoffs            1
RankSeason          1
RankPlayoffs        2
G                 162
OOBP              NaN
OSLG              NaN
WP               0.64
RD                163
Name: 603, dtype: object)
<class 'pandas.core.series.Series'>
(604, Team              PHI
League             NL
Year             1990
RS                646
RA                729
W                  77
OBP             0.327
SLG             0.363
BA              0.255
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.48
RD                -83
Name: 604, dtype: object)
<class 'pandas.core.series.Series'>
(605, Team              PIT
League             NL
Year             1990
RS                733
RA                619
W                  95
OBP              0.33
SLG             0.405
BA              0.259
Playoffs            1
RankSeason          2
RankPlayoffs        3
G                 162
OOBP              NaN
OSLG              NaN
WP               0.59
RD                114
Name: 605, dtype: object)
<class 'pandas.core.series.Series'>
(606, Team              SDP
League             NL
Year             1990
RS                673
RA                673
W                  75
OBP              0.32
SLG              0.38
BA              0.257
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.46
RD                  0
Name: 606, dtype: object)
<class 'pandas.core.series.Series'>
(607, Team              SEA
League             AL
Year             1990
RS                640
RA                680
W                  77
OBP             0.333
SLG             0.373
BA              0.259
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.48
RD                -40
Name: 607, dtype: object)
<class 'pandas.core.series.Series'>
(608, Team              SFG
League             NL
Year             1990
RS                719
RA                710
W                  85
OBP             0.323
SLG             0.396
BA              0.262
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.52
RD                  9
Name: 608, dtype: object)
<class 'pandas.core.series.Series'>
(609, Team              STL
League             NL
Year             1990
RS                599
RA                698
W                  70
OBP              0.32
SLG             0.358
BA              0.256
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.43
RD                -99
Name: 609, dtype: object)
<class 'pandas.core.series.Series'>
(610, Team              TEX
League             AL
Year             1990
RS                676

Name: 629, dtype: object)
<class 'pandas.core.series.Series'>
(630, Team              PHI
League             NL
Year             1989
RS                629
RA                735
W                  67
OBP             0.314
SLG             0.364
BA              0.243
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 163
OOBP              NaN
OSLG              NaN
WP               0.41
RD               -106
Name: 630, dtype: object)
<class 'pandas.core.series.Series'>
(631, Team              PIT
League             NL
Year             1989
RS                637
RA                680
W                  74
OBP             0.311
SLG             0.359
BA              0.241
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 164
OOBP              NaN
OSLG              NaN
WP               0.45
RD                -43
Name: 631, dtype: object)
<class 'pandas.core.series.Series'>
(632, Team              SDP
League             NL
Year             1989
RS                642
RA                626
W                  89
OBP             0.319
SLG             0.369
BA              0.251
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.55
RD                 16
Name: 632, dtype: object)
<class 'pandas.core.series.Series'>
(633, Team              SEA
League             AL
Year             1989
RS                694
RA                728
W                  73
OBP              0.32
SLG             0.384
BA              0.257
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.45
RD                -34
Name: 633, dtype: object)
<class 'pandas.core.series.Series'>
(634, Team              SFG
League             NL
Year             1989
RS                699
RA                600
W                  92
OBP             0.316
SLG              0.39
BA               0.25
Playoffs            1
RankSeason          3
RankPlayoffs        2
G                 162
OOBP              NaN
OSLG              NaN
WP               0.57
RD                 99
Name: 634, dtype: object)
<class 'pandas.core.series.Series'>
(635, Team              STL
League             NL
Year             1989
RS                632
RA                608
W                  86
OBP             0.321
SLG             0.363
BA              0.258
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 164
OOBP              NaN
OSLG              NaN
WP               0.52
RD                 24
Name: 635, dtype: object)
<class 'pandas.core.series.Series'>
(636, Team              TEX
League             AL
Year             1989
RS                695
RA                714
W                  83
OBP             0.326
SLG             0.394
BA              0.263
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.51
RD                -19
Name: 636, dtype: object)
<class 'pandas.core.series.Series'>
(637, Team              TOR
League             AL
Year             1989
RS                731
RA                651
W                  89
OBP             0.323
SLG             0.398
BA               0.26
Playoffs            1
RankSeason          4
RankPlayoffs        3
G                 162
OOBP              NaN
OSLG              NaN
WP               0.55
RD                 80
Name: 637, dtype: object)
<class 'pandas.core.series.Series'>
(638, Team              ATL
League             NL
Year             1988
RS                555
RA                741
W                  54
OBP             0.298
SLG             0.348
BA              0.242
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 160
OOBP              NaN
OSLG              NaN
WP               0.34
RD               -186
Name: 638, dtype: object)
<class 'pandas.core.series.Series'>
(639, Team              BAL
League             AL
Year             1988
RS                550
RA                789
W                  54
OBP             0.305
SLG             0.359
BA              0.238
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 161
OOBP              NaN
OSLG              NaN
WP               0.34
RD               -239
Name: 639, dtype: object)
<class 'pandas.core.series.Series'>
(640, Team              BOS
League             AL
Year             1988
RS                813
RA                689
W                  89
OBP             0.357
SLG              0.42
BA              0.283
Playoffs            1
RankSeason          4
RankPlayoffs        3
G                 162
OOBP              NaN
OSLG              NaN
WP               0.55
RD                124
Name: 640, dtype: object)
<class 'pandas.core.series.Series'>
(641, Team              CAL
League             AL
Year             1988
RS                714
RA                771
W                  75
OBP             0.321
SLG             0.385
BA              0.261
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.46
RD                -57
Name: 641, dtype: object)
<class 'pandas.core.series.Series'>
(642, Team              CHC
League             NL
Year             1988
RS                660
RA                694
W                  77
OBP              0.31
SLG             0.383
BA              0.261
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 163
OOBP              NaN
OSLG              NaN
WP               0.47
RD                -34
Name: 642, dtype: object)
<class 'pandas.core.series.Series'>
(643, Team              CHW
League             AL
Year             1988
RS                631
RA                757
W                  71
OBP             0.303
SLG              0.37
BA              0.244
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 161
OOBP              NaN
OSLG              NaN
WP               0.44
RD               -126
Name: 643, dtype: object)
<class 'pandas.core.series.Series'>
(644, Team              CIN
League             NL
Year             1988
RS                641
RA                596
W                  87
OBP             0.309
SLG             0.368
BA              0.246
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 161
OOBP              NaN
OSLG              NaN
WP               0.54
RD                 45
Name: 644, dtype: object)
<class 'pandas.core.series.Series'>
(645, Team              CLE
League             AL
Year             1988
RS                666
RA                731
W                  78
OBP             0.314
SLG             0.387
BA              0.261
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.48
RD                -65
Name: 645, dtype: object)
<class 'pandas.core.series.Series'>
(646, Team              DET
League             AL
Year             1988
RS                703
RA                658
W                  88
OBP             0.324
SLG             0.378
BA               0.25
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.54
RD                 45
Name: 646, dtype: object)
<class 'pandas.core.series.Series'>
(647, Team              HOU
League             NL
Year             1988
RS                617
RA                631
W                  82
OBP             0.306
SLG             0.351
BA              0.244
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.51
RD                -14
Name: 647, dtype: object)
<class 'pandas.core.series.Series'>
(648, Team              KCR
League             AL
Year             1988
RS                704
RA                648
W                  84
OBP             0.321
SLG             0.391
BA              0.259
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 161
OOBP              NaN
OSLG              NaN
WP               0.52
RD                 56
Name: 648, dtype: object)
<class 'pandas.core.series.Series'>
(649, Team              LAD
League             NL
Year             1988
RS                628
RA                544
W                  94
OBP             0.305
SLG             0.352
BA              0.248
Playoffs            1
RankSeason          3
RankPlayoffs        1
G                 162
OOBP              NaN
OSLG              NaN
WP               0.58
RD                 84
Name: 649, dtype: object)
<class 'pandas.core.series.Series'>
(650, Team              MIL
League             AL
Year             1988
RS                682
RA                616
W                  87
OBP             0.314
SLG             0.375
BA              0.257
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.54
RD                 66
Name: 650, dtype: object)
<class 'pandas.core.series.Series'>
(651, Team              MIN
League             AL
Year             1988
RS                759
RA                672
W                  91
OBP              0.34
SLG             0.421
BA              0.274
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.56
RD                 87
Name: 651, dtype: object)
<class 'pandas.core.series.Series'>
(652, Team              MON
League             NL
Year             1988
RS                628
RA                592
W                  81
OBP             0.309
SLG             0.373
BA              0.251
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 163
OOBP              NaN
OSLG              NaN
WP                0.5
RD                 36
Name: 652, dtype: object)
<class 'pandas.core.series.Series'>
(653, Team              NYM
League             NL
Year             1988
RS                703
RA                532
W                 100
OBP             0.325
SLG             0.396
BA              0.256
Playoffs            1
RankSeason          2
RankPlayoffs        3
G                 160
OOBP              NaN
OSLG              NaN
WP               0.62
RD                171
Name: 653, dtype: object)
<class 'pandas.core.series.Series'>
(654, Team              NYY
League             AL
Year             1988
RS                772
RA                748
W                  85
OBP             0.333
SLG             0.395
BA              0.263
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 161
OOBP              NaN
OSLG              NaN
WP               0.53
RD                 24
Name: 654, dtype: object)
<class 'pandas.core.series.Series'>
(655, Team              OAK
League             AL
Year             1988
RS                800
RA                620
W                 104
OBP             0.336
SLG             0.399
BA              0.263
Playoffs            1
RankSeason          1
RankPlayoffs        2
G                 162
OOBP              NaN
OSLG              NaN
WP               0.64
RD                180
Name: 655, dtype: object)
<class 'pandas.core.series.Series'>
(656, Team              PHI
League             NL
Year             1988
RS                597
RA                734
W                  65
OBP             0.306
SLG             0.355
BA              0.239
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP                0.4
RD               -137
Name: 656, dtype: object)
<class 'pandas.core.series.Series'>
(657, Team              PIT
League             NL
Year             1988
RS                651
RA                616
W                  85
OBP             0.317
SLG             0.369
BA              0.247
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 160
OOBP              NaN
OSLG              NaN
WP               0.53
RD                 35
Name: 657, dtype: object)
<class 'pandas.core.series.Series'>
(658, Team              SDP
League             NL
Year             1988
RS                594
RA                583
W                  83
OBP              0.31
SLG             0.351
BA              0.247
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 161
OOBP              NaN
OSLG              NaN
WP               0.52
RD                 11
Name: 658, dtype: object)
<class 'pandas.core.series.Series'>
(659, Team              SEA
League             AL
Year             1988
RS                664
RA                744
W                  68
OBP             0.317
SLG             0.398
BA              0.257
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 161
OOBP              NaN
OSLG              NaN
WP               0.42
RD                -80
Name: 659, dtype: object)
<class 'pandas.core.series.Series'>
(660, Team              SFG
League             NL
Year             1988
RS                670
RA                626
W                  83
OBP             0.318
SLG             0.368
BA              0.248
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.51
RD                 44
Name: 660, dtype: object)
<class 'pandas.core.series.Series'>
(661, Team              STL
League             NL
Year             1988
RS                578
RA                633
W                  76
OBP             0.309
SLG             0.337
BA              0.249
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.47
RD                -55
Name: 661, dtype: object)
<class 'pandas.core.series.Series'>
(662, Team              TEX
League             AL
Year             1988
RS                637
RA                735
W                  70
OBP              0.32
SLG             0.368
BA              0.252
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 161
OOBP              NaN
OSLG              NaN
WP               0.43
RD                -98
Name: 662, dtype: object)
<class 'pandas.core.series.Series'>
(663, Team              TOR
League             AL
Year             1988
RS                763
RA                680
W                  87
OBP             0.332
SLG             0.419
BA              0.268
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.54
RD                 83
Name: 663, dtype: object)
<class 'pandas.core.series.Series'>
(664, Team              ATL
League             NL
Year             1987
RS                747
RA                829
W                  69
OBP             0.339
SLG             0.403
BA              0.258
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 161
OOBP              NaN
OSLG              NaN
WP               0.43
RD                -82
Name: 664, dtype: object)
<class 'pandas.core.series.Series'>
(665, Team              BAL
League             AL
Year             1987
RS                729
RA                880
W                  67
OBP             0.322
SLG             0.418
BA              0.258
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.41
RD               -151
Name: 665, dtype: object)
<class 'pandas.core.series.Series'>
(666, Team              BOS
League             AL
Year             1987
RS                842
RA                825
W                  78
OBP             0.352
SLG              0.43
BA              0.278
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.48
RD                 17
Name: 666, dtype: object)
<class 'pandas.core.series.Series'>
(667, Team              CAL
League             AL
Year             1987
RS                770
RA                803
W                  75
OBP             0.326
SLG             0.401
BA              0.252
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.46
RD                -33
Name: 667, dtype: object)
<class 'pandas.core.series.Series'>
(668, Team              CHC
League             NL
Year             1987
RS                720
RA                801
W                  76
OBP             0.326
SLG             0.432
BA              0.264
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 161
OOBP              NaN
OSLG              NaN
WP               0.47
RD                -81
Name: 668, dtype: object)
<class 'pandas.core.series.Series'>
(669, Team              CHW
League             AL
Year             1987
RS                748
RA                746
W                  77
OBP             0.319
SLG             0.415
BA              0.258
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.48
RD                  2
Name: 669, dtype: object)
<class 'pandas.core.series.Series'>
(670, Team              CIN
League             NL
Year             1987
RS                783
RA                752
W                  84
OBP              0.33
SLG             0.427
BA              0.266
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.52
RD                 31
Name: 670, dtype: object)
<class 'pandas.core.series.Series'>
(671, Team              CLE
League             AL
Year             1987
RS                742
RA                957
W                  61
OBP             0.324
SLG             0.422
BA              0.263
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.38
RD               -215
Name: 671, dtype: object)
<class 'pandas.core.series.Series'>
(672, Team              DET
League             AL
Year             1987
RS                896
RA                735
W                  98
OBP             0.349
SLG             0.451
BA              0.272
Playoffs            1
RankSeason          1
RankPlayoffs        3
G                 162
OOBP              NaN
OSLG              NaN
WP                0.6
RD                161
Name: 672, dtype: object)
<class 'pandas.core.series.Series'>
(673, Team              HOU
League             NL
Year             1987
RS                648
RA                678
W                  76
OBP             0.318
SLG             0.373
BA              0.253
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.47
RD                -30
Name: 673, dtype: object)
<class 'pandas.core.series.Series'>
(674, Team              KCR
League             AL
Year             1987
RS                715
RA                691
W                  83
OBP             0.328
SLG             0.412
BA              0.262
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.51
RD                 24
Name: 674, dtype: object)
<class 'pandas.core.series.Series'>
(675, Team              LAD

<class 'pandas.core.series.Series'>
(815, Team              SEA
League             AL
Year             1982
RS                651
RA                712
W                  76
OBP             0.311
SLG             0.381
BA              0.254
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.47
RD                -61
Name: 815, dtype: object)
<class 'pandas.core.series.Series'>
(816, Team              SFG
League             NL
Year             1982
RS                673
RA                687
W                  87
OBP             0.327
SLG             0.376
BA              0.253
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.54
RD                -14
Name: 816, dtype: object)
<class 'pandas.core.series.Series'>
(817, Team              STL
League             NL
Year             1982
RS                685
RA                609
W                  92
OBP             0.334
SLG             0.364
BA              0.264
Playoffs            1
RankSeason          3
RankPlayoffs        1
G                 162
OOBP              NaN
OSLG              NaN
WP               0.57
RD                 76
Name: 817, dtype: object)
<class 'pandas.core.series.Series'>
(818, Team              TEX
League             AL
Year             1982
RS                590
RA                749
W                  64
OBP             0.308
SLG             0.359
BA              0.249
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP                0.4
RD               -159
Name: 818, dtype: object)
<class 'pandas.core.series.Series'>
(819, Team              TOR
League             AL
Year             1982
RS                651
RA                701
W                  78
OBP             0.314
SLG             0.383
BA              0.262
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.48
RD                -50
Name: 819, dtype: object)
<class 'pandas.core.series.Series'>
(820, Team              ATL
League             NL
Year             1980
RS                630
RA                660
W                  81
OBP             0.307
SLG              0.38
BA               0.25
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 161
OOBP              NaN
OSLG              NaN
WP                0.5
RD                -30
Name: 820, dtype: object)
<class 'pandas.core.series.Series'>
(821, Team              BAL
League             AL
Year             1980
RS                805
RA                640
W                 100
OBP             0.342
SLG             0.413
BA              0.273
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.62
RD                165
Name: 821, dtype: object)
<class 'pandas.core.series.Series'>
(822, Team              BOS
League             AL
Year             1980
RS                757
RA                767
W                  83
OBP              0.34
SLG             0.436
BA              0.283
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 160
OOBP              NaN
OSLG              NaN
WP               0.52
RD                -10
Name: 822, dtype: object)
<class 'pandas.core.series.Series'>
(823, Team              CAL
League             AL
Year             1980
RS                698
RA                797
W                  65
OBP             0.332
SLG             0.378
BA              0.265
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 160
OOBP              NaN
OSLG              NaN
WP               0.41
RD                -99
Name: 823, dtype: object)
<class 'pandas.core.series.Series'>
(824, Team              CHC
League             NL
Year             1980
RS                614
RA                728
W                  64
OBP             0.309
SLG             0.365
BA              0.251
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP                0.4
RD               -114
Name: 824, dtype: object)
<class 'pandas.core.series.Series'>
(825, Team              CHW
League             AL
Year             1980
RS                587
RA                722
W                  70
OBP             0.311
SLG              0.37
BA              0.259
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.43
RD               -135
Name: 825, dtype: object)
<class 'pandas.core.series.Series'>
(826, Team              CIN
League             NL
Year             1980
RS                707
RA                670
W                  89
OBP             0.327
SLG             0.386
BA              0.262
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 163
OOBP              NaN
OSLG              NaN
WP               0.55
RD                 37
Name: 826, dtype: object)
<class 'pandas.core.series.Series'>
(827, Team              CLE
League             AL
Year             1980
RS                738
RA                807
W                  79
OBP              0.35
SLG             0.381
BA              0.277
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 160
OOBP              NaN
OSLG              NaN
WP               0.49
RD                -69
Name: 827, dtype: object)
<class 'pandas.core.series.Series'>
(828, Team              DET
League             AL
Year             1980
RS                830
RA                757
W                  84
OBP             0.348
SLG             0.409
BA              0.273
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 163
OOBP              NaN
OSLG              NaN
WP               0.52
RD                 73
Name: 828, dtype: object)
<class 'pandas.core.series.Series'>
(829, Team              HOU
League             NL
Year             1980
RS                637
RA                589
W                  93
OBP             0.326
SLG             0.367
BA              0.261
Playoffs            1
RankSeason          3
RankPlayoffs        3
G                 163
OOBP              NaN
OSLG              NaN
WP               0.57
RD                 48
Name: 829, dtype: object)
<class 'pandas.core.series.Series'>
(830, Team              KCR
League             AL
Year             1980
RS                809
RA                694
W                  97
OBP             0.345
SLG             0.413
BA              0.286
Playoffs            1
RankSeason          2
RankPlayoffs        2
G                 162
OOBP              NaN
OSLG              NaN
WP                0.6
RD                115
Name: 830, dtype: object)
<class 'pandas.core.series.Series'>
(831, Team              LAD
League             NL
Year             1980
RS                663
RA                591
W                  92
OBP             0.323
SLG             0.388
BA              0.263
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 163
OOBP              NaN
OSLG              NaN
WP               0.56
RD                 72
Name: 831, dtype: object)
<class 'pandas.core.series.Series'>
(832, Team              MIL
League             AL
Year             1980
RS                811
RA                682
W                  86
OBP             0.329
SLG             0.448
BA              0.275
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.53
RD                129
Name: 832, dtype: object)
<class 'pandas.core.series.Series'>
(833, Team              MIN
League             AL
Year             1980
RS                670
RA                724
W                  77
OBP             0.319
SLG             0.381
BA              0.265
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 161
OOBP              NaN
OSLG              NaN
WP               0.48
RD                -54
Name: 833, dtype: object)
<class 'pandas.core.series.Series'>
(834, Team              MON
League             NL
Year             1980
RS                694
RA                629
W                  90
OBP             0.324
SLG             0.388
BA              0.257
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.56
RD                 65
Name: 834, dtype: object)
<class 'pandas.core.series.Series'>
(835, Team              NYM
League             NL
Year             1980
RS                611
RA                702
W                  67
OBP             0.319
SLG             0.345
BA              0.257
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.41
RD                -91
Name: 835, dtype: object)
<class 'pandas.core.series.Series'>
(836, Team              NYY
League             AL
Year             1980
RS                820
RA                662
W                 103
OBP             0.343
SLG             0.425
BA              0.267
Playoffs            1
RankSeason          1
RankPlayoffs        3
G                 162
OOBP              NaN
OSLG              NaN
WP               0.64
RD                158
Name: 836, dtype: object)
<class 'pandas.core.series.Series'>
(837, Team              OAK
League             AL
Year             1980
RS                686
RA                642
W                  83
OBP             0.322
SLG             0.385
BA              0.259
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.51
RD                 44
Name: 837, dtype: object)
<class 'pandas.core.series.Series'>
(838, Team              PHI
League             NL
Year             1980
RS                728
RA                639
W                  91
OBP             0.327
SLG               0.4
BA               0.27
Playoffs            1
RankSeason          4
RankPlayoffs        1
G                 162
OOBP              NaN
OSLG              NaN
WP               0.56
RD                 89
Name: 838, dtype: object)
<class 'pandas.core.series.Series'>
(839, Team              PIT
League             NL
Year             1980
RS                666
RA                646
W                  83
OBP             0.322
SLG             0.388
BA              0.266
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.51
RD                 20
Name: 839, dtype: object)
<class 'pandas.core.series.Series'>
(840, Team              SDP
League             NL
Year             1980
RS                591
RA                654
W                  73
OBP             0.324
SLG             0.342
BA              0.255
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 163
OOBP              NaN
OSLG              NaN
WP               0.45
RD                -63
Name: 840, dtype: object)
<class 'pandas.core.series.Series'>
(841, Team              SEA
League             AL
Year             1980
RS                610
RA                793
W                  59
OBP             0.308
SLG             0.356
BA              0.248
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 163
OOBP              NaN
OSLG              NaN
WP               0.36
RD               -183
Name: 841, dtype: object)
<class 'pandas.core.series.Series'>
(842, Team              SFG
League             NL
Year             1980
RS                573
RA                634
W                  75
OBP             0.308
SLG             0.342
BA              0.244
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 161
OOBP              NaN
OSLG              NaN
WP               0.47
RD                -61
Name: 842, dtype: object)
<class 'pandas.core.series.Series'>
(843, Team              STL
League             NL
Year             1980
RS                738
RA                710
W                  74
OBP             0.328
SLG               0.4
BA              0.275
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.46
RD                 28
Name: 843, dtype: object)
<class 'pandas.core.series.Series'>
(844, Team              TEX
League             AL
Year             1980
RS                756
RA                752
W                  76
OBP             0.339
SLG             0.405
BA              0.284
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 163
OOBP              NaN
OSLG              NaN
WP               0.47
RD                  4
Name: 844, dtype: object)
<class 'pandas.core.series.Series'>
(845, Team              TOR
League             AL
Year             1980
RS                624
RA                762
W                  67
OBP             0.309
SLG             0.383
BA              0.251
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.41
RD               -138
Name: 845, dtype: object)
<class 'pandas.core.series.Series'>
(846, Team              ATL
League             NL
Year             1979
RS                669
RA                763
W                  66
OBP             0.318
SLG             0.377
BA              0.256
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 160
OOBP              NaN
OSLG              NaN
WP               0.41
RD                -94
Name: 846, dtype: object)
<class 'pandas.core.series.Series'>
(847, Team              BAL
League             AL
Year             1979
RS                757
RA                582
W                 102
OBP             0.336
SLG             0.419
BA              0.261
Playoffs            1
RankSeason          1
RankPlayoffs        2
G                 159
OOBP              NaN
OSLG              NaN
WP               0.64
RD                175
Name: 847, dtype: object)
<class 'pandas.core.series.Series'>
(848, Team              BOS
League             AL
Year             1979
RS                841
RA                711
W                  91
OBP             0.344
SLG             0.456
BA              0.283
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 160
OOBP              NaN
OSLG              NaN
WP               0.57
RD                130
Name: 848, dtype: object)
<class 'pandas.core.series.Series'>
(849, Team              CAL
League             AL
Year             1979
RS                866
RA                768
W                  88
OBP             0.351
SLG             0.429
BA              0.282
Playoffs            1
RankSeason          4
RankPlayoffs        3
G                 162
OOBP              NaN
OSLG              NaN
WP               0.54
RD                 98
Name: 849, dtype: object)
<class 'pandas.core.series.Series'>
(850, Team              CHC
League             NL
Year             1979
RS                706
RA                707
W                  80
OBP             0.329
SLG             0.403
BA              0.269
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.49
RD                 -1
Name: 850, dtype: object)
<class 'pandas.core.series.Series'>
(851, Team              CHW
League             AL
Year             1979
RS                730
RA                748
W                  73
OBP             0.333
SLG              0.41
BA              0.275
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 160
OOBP              NaN
OSLG              NaN
WP               0.46
RD                -18
Name: 851, dtype: object)
<class 'pandas.core.series.Series'>
(852, Team              CIN
League             NL
Year             1979
RS                731
RA                644
W                  90
OBP             0.338
SLG             0.396
BA              0.264
Playoffs            1
RankSeason          3
RankPlayoffs        3
G                 161
OOBP              NaN
OSLG              NaN
WP               0.56
RD                 87
Name: 852, dtype: object)
<class 'pandas.core.series.Series'>
(853, Team              CLE
League             AL
Year             1979
RS                760
RA                805
W                  81
OBP              0.34
SLG             0.384
BA              0.258
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 161
OOBP              NaN
OSLG              NaN
WP                0.5
RD                -45
Name: 853, dtype: object)
<class 'pandas.core.series.Series'>
(854, Team              DET
League             AL
Year             1979
RS                770
RA                738
W                  84
OBP             0.339
SLG             0.415
BA              0.269
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 161
OOBP              NaN
OSLG              NaN
WP               0.52
RD                 32
Name: 854, dtype: object)
<class 'pandas.core.series.Series'>
(855, Team              HOU
League             NL
Year             1979
RS                583
RA                582
W                  89
OBP             0.315
SLG             0.344
BA              0.256
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.55
RD                  1
Name: 855, dtype: object)
<class 'pandas.core.series.Series'>
(856, Team              KCR
League             AL
Year             1979
RS                851
RA                816
W                  85
OBP             0.343
SLG             0.422
BA              0.282
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.52
RD                 35
Name: 856, dtype: object)
<class 'pandas.core.series.Series'>
(857, Team              LAD
League             NL
Year             1979
RS                739
RA                717
W                  79
OBP             0.331
SLG             0.412
BA              0.263
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.49
RD                 22
Name: 857, dtype: object)
<class 'pandas.core.series.Series'>
(858, Team              MIL
League             AL
Year             1979
RS                807
RA                722
W                  95
OBP             0.345
SLG             0.448
BA               0.28
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 161
OOBP              NaN
OSLG              NaN
WP               0.59
RD                 85

Name: 858, dtype: object)
<class 'pandas.core.series.Series'>
(859, Team              MIN
League             AL
Year             1979
RS                764
RA                725
W                  82
OBP             0.341
SLG             0.402
BA              0.278
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.51
RD                 39
Name: 859, dtype: object)
<class 'pandas.core.series.Series'>
(860, Team              MON
League             NL
Year             1979
RS                701
RA                581
W                  95
OBP             0.319
SLG             0.408
BA              0.264
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 160
OOBP              NaN
OSLG              NaN
WP               0.59
RD                120
Name: 860, dtype: object)
<class 'pandas.core.series.Series'>
(861, Team              NYM
League             NL
Year             1979
RS                593
RA                706
W                  63
OBP             0.313
SLG              0.35
BA               0.25
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 163
OOBP              NaN
OSLG              NaN
WP               0.39
RD               -113
Name: 861, dtype: object)
<class 'pandas.core.series.Series'>
(862, Team              NYY
League             AL
Year             1979
RS                734
RA                672
W                  89
OBP             0.328
SLG             0.406
BA              0.266
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 160
OOBP              NaN
OSLG              NaN
WP               0.56
RD                 62
Name: 862, dtype: object)
<class 'pandas.core.series.Series'>
(863, Team              OAK
League             AL
Year             1979
RS                573
RA                860
W                  54
OBP             0.302
SLG             0.346
BA              0.239
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.33
RD               -287
Name: 863, dtype: object)
<class 'pandas.core.series.Series'>
(864, Team              PHI
League             NL
Year             1979
RS                683
RA                718
W                  84
OBP              0.34
SLG             0.396
BA              0.266
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 163
OOBP              NaN
OSLG              NaN
WP               0.52
RD                -35
Name: 864, dtype: object)
<class 'pandas.core.series.Series'>
(865, Team              PIT
League             NL
Year             1979
RS                775
RA                643
W                  98
OBP              0.33
SLG             0.416
BA              0.272
Playoffs            1
RankSeason          2
RankPlayoffs        1
G                 163
OOBP              NaN
OSLG              NaN
WP                0.6
RD                132
Name: 865, dtype: object)
<class 'pandas.core.series.Series'>
(866, Team              SDP
League             NL
Year             1979
RS                603
RA                681
W                  68
OBP             0.311
SLG             0.348
BA              0.242
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 161
OOBP              NaN
OSLG              NaN
WP               0.42
RD                -78
Name: 866, dtype: object)
<class 'pandas.core.series.Series'>
(867, Team              SEA
League             AL
Year             1979
RS                711
RA                820
W                  67
OBP             0.331
SLG             0.404
BA              0.269
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.41
RD               -109
Name: 867, dtype: object)
<class 'pandas.core.series.Series'>
(868, Team              SFG
League             NL
Year             1979
RS                672
RA                751
W                  71
OBP             0.319
SLG             0.365
BA              0.246
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.44
RD                -79
Name: 868, dtype: object)
<class 'pandas.core.series.Series'>
(869, Team              STL
League             NL
Year             1979
RS                731
RA                693
W                  86
OBP             0.331
SLG             0.401
BA              0.278
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 163
OOBP              NaN
OSLG              NaN
WP               0.53
RD                 38
Name: 869, dtype: object)
<class 'pandas.core.series.Series'>
(870, Team              TEX
League             AL
Year             1979
RS                750
RA                698
W                  83
OBP             0.334
SLG             0.409
BA              0.278
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.51
RD                 52
Name: 870, dtype: object)
<class 'pandas.core.series.Series'>
(871, Team              TOR
League             AL
Year             1979
RS                613
RA                862
W                  53
OBP             0.311
SLG             0.363
BA              0.251
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.33
RD               -249
Name: 871, dtype: object)
<class 'pandas.core.series.Series'>
(872, Team              ATL
League             NL
Year             1978
RS                600
RA                750
W                  69
OBP             0.315
SLG             0.363
BA              0.244
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.43
RD               -150
Name: 872, dtype: object)
<class 'pandas.core.series.Series'>
(873, Team              BAL
League             AL
Year             1978
RS                659
RA                633
W                  90
OBP             0.326
SLG             0.396
BA              0.258
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 161
OOBP              NaN
OSLG              NaN
WP               0.56
RD                 26
Name: 873, dtype: object)
<class 'pandas.core.series.Series'>
(874, Team              BOS
League             AL
Year             1978
RS                796
RA                657
W                  99
OBP             0.336
SLG             0.424
BA              0.267
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 163
OOBP              NaN
OSLG              NaN
WP               0.61
RD                139
Name: 874, dtype: object)
<class 'pandas.core.series.Series'>
(875, Team              CAL
League             AL
Year             1978
RS                691
RA                666
W                  87
OBP              0.33
SLG              0.37
BA              0.259
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.54
RD                 25
Name: 875, dtype: object)
<class 'pandas.core.series.Series'>
(876, Team              CHC
League             NL
Year             1978
RS                664
RA                724
W                  79
OBP             0.331
SLG             0.361
BA              0.264
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.49
RD                -60
Name: 876, dtype: object)
<class 'pandas.core.series.Series'>
(877, Team              CHW
League             AL
Year             1978
RS                634
RA                731
W                  71
OBP             0.317
SLG             0.379
BA              0.264
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 161
OOBP              NaN
OSLG              NaN
WP               0.44
RD                -97
Name: 877, dtype: object)
<class 'pandas.core.series.Series'>
(878, Team              CIN
League             NL
Year             1978
RS                710
RA                688
W                  92
OBP             0.334
SLG             0.393
BA              0.256
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 161
OOBP              NaN
OSLG              NaN
WP               0.57
RD                 22
Name: 878, dtype: object)
<class 'pandas.core.series.Series'>
(879, Team              CLE
League             AL
Year             1978
RS                639
RA                694
W                  69
OBP             0.323
SLG             0.379
BA              0.261
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 159
OOBP              NaN
OSLG              NaN
WP               0.43
RD                -55
Name: 879, dtype: object)
<class 'pandas.core.series.Series'>
(880, Team              DET
League             AL
Year             1978
RS                714
RA                653
W                  86
OBP             0.339
SLG             0.392
BA              0.271
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.53
RD                 61
Name: 880, dtype: object)
<class 'pandas.core.series.Series'>
(881, Team              HOU
League             NL
Year             1978
RS                605
RA                634
W                  74
OBP             0.313
SLG             0.355
BA              0.258
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.46
RD                -29
Name: 881, dtype: object)
<class 'pandas.core.series.Series'>
(882, Team              KCR
League             AL
Year             1978
RS                743
RA                634
W                  92
OBP             0.329
SLG             0.399
BA              0.268
Playoffs            1
RankSeason          3
RankPlayoffs        3
G                 162
OOBP              NaN
OSLG              NaN
WP               0.57
RD                109
Name: 882, dtype: object)
<class 'pandas.core.series.Series'>
(883, Team              LAD
League             NL
Year             1978
RS                727
RA                573
W                  95
OBP             0.338
SLG             0.402
BA              0.264
Playoffs            1
RankSeason          2
RankPlayoffs        2
G                 162
OOBP              NaN
OSLG              NaN
WP               0.59
RD                154
Name: 883, dtype: object)
<class 'pandas.core.series.Series'>
(884, Team              MIL
League             AL
Year             1978
RS                804
RA                650
W                  93
OBP             0.339
SLG             0.432
BA              0.276
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.57
RD                154
Name: 884, dtype: object)
<class 'pandas.core.series.Series'>
(885, Team              MIN
League             AL
Year             1978
RS                666
RA                678
W                  73
OBP             0.339
SLG             0.375
BA              0.267
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.45
RD                -12
Name: 885, dtype: object)
<class 'pandas.core.series.Series'>
(886, Team              MON
League             NL
Year             1978
RS                633
RA                611
W                  76
OBP             0.306
SLG             0.379
BA              0.254
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.47
RD                 22
Name: 886, dtype: object)
<class 'pandas.core.series.Series'>
(887, Team              NYM
League             NL
Year             1978
RS                607
RA                690
W                  66
OBP             0.314
SLG             0.352
BA              0.245
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.41
RD                -83
Name: 887, dtype: object)
<class 'pandas.core.series.Series'>
(888, Team              NYY
League             AL
Year             1978
RS                735
RA                582
W                 100
OBP             0.329
SLG             0.388
BA              0.267
Playoffs            1
RankSeason          1
RankPlayoffs        1
G                 163
OOBP              NaN
OSLG              NaN
WP               0.61
RD                153
Name: 888, dtype: object)
<class 'pandas.core.series.Series'>
(889, Team              OAK
League             AL
Year             1978
RS                532
RA                690
W                  69
OBP             0.303
SLG             0.351
BA              0.245
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.43
RD               -158
Name: 889, dtype: object)
<class 'pandas.core.series.Series'>
(890, Team              PHI
League             NL
Year             1978
RS                708
RA                586
W                  90
OBP             0.328
SLG             0.388
BA              0.258
Playoffs            1
RankSeason          4
RankPlayoffs        3
G                 162
OOBP              NaN
OSLG              NaN
WP               0.56
RD                122
Name: 890, dtype: object)
<class 'pandas.core.series.Series'>
(891, Team              PIT
League             NL
Year             1978
RS                684
RA                637
W                  88
OBP              0.32
SLG             0.385
BA              0.257
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 161
OOBP              NaN
OSLG              NaN
WP               0.55
RD                 47
Name: 891, dtype: object)
<class 'pandas.core.series.Series'>
(892, Team              SDP
League             NL
Year             1978
RS                591
RA                598
W                  84
OBP             0.321
SLG             0.348
BA              0.252
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.52
RD                 -7
Name: 892, dtype: object)
<class 'pandas.core.series.Series'>
(893, Team              SEA
League             AL
Year             1978
RS                614
RA                834
W                  56
OBP             0.314
SLG             0.359
BA              0.248
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 160
OOBP              NaN
OSLG              NaN
WP               0.35
RD               -220
Name: 893, dtype: object)
<class 'pandas.core.series.Series'>
(894, Team              SFG
League             NL
Year             1978
RS                613
RA                594
W                  89
OBP             0.318
SLG             0.374
BA              0.248
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.55
RD                 19
Name: 894, dtype: object)
<class 'pandas.core.series.Series'>
(895, Team              STL
League             NL
Year             1978
RS                600
RA                657
W                  69
OBP             0.303
SLG             0.358
BA              0.249
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.43
RD                -57
Name: 895, dtype: object)
<class 'pandas.core.series.Series'>
(896, Team              TEX
League             AL
Year             1978
RS                692
RA                632
W                  87
OBP             0.332
SLG             0.381
BA              0.253
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.54
RD                 60
Name: 896, dtype: object)
<class 'pandas.core.series.Series'>
(897, Team              TOR
League             AL
Year             1978
RS                590
RA                775
W                  59
OBP             0.308
SLG             0.359
BA               0.25
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 161
OOBP              NaN
OSLG              NaN
WP               0.37
RD               -185
Name: 897, dtype: object)
<class 'pandas.core.series.Series'>
(898, Team              ATL
League             NL
Year             1977
RS                678
RA                895
W                  61
OBP              0.32
SLG             0.376
BA              0.254
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.38
RD               -217
Name: 898, dtype: object)
<class 'pandas.core.series.Series'>
(899, Team              BAL
League             AL
Year             1977
RS                719
RA                653
W                  97
OBP             0.329
SLG             0.393
BA              0.261
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 161
OOBP              NaN
OSLG              NaN
WP                0.6
RD                 66
Name: 899, dtype: object)
<class 'pandas.core.series.Series'>
(900, Team              BOS
League             AL
Year             1977
RS                859
RA                712
W                  97
OBP             0.345
SLG             0.465
BA              0.281
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 161
OOBP              NaN
OSLG              NaN
WP                0.6
RD                147
Name: 900, dtype: object)
<class 'pandas.core.series.Series'>
(901, Team              CAL
League             AL
Year             1977
RS                675
RA                695
W                  74
OBP             0.324
SLG             0.386
BA              0.255
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.46
RD                -20
Name: 901, dtype: object)
<class 'pandas.core.series.Series'>
(902, Team              CHC
League             NL
Year             1977
RS                692
RA                739
W                  81
OBP              0.33
SLG             0.387
BA              0.266
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP                0.5
RD                -47
Name: 902, dtype: object)
<class 'pandas.core.series.Series'>
(903, Team              CHW
League             AL
Year             1977
RS                844
RA                771
W                  90
OBP             0.344
SLG             0.444
BA              0.278
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.56
RD                 73
Name: 903, dtype: object)
<class 'pandas.core.series.Series'>
(904, Team              CIN

Name: 985, dtype: object)
<class 'pandas.core.series.Series'>
(986, Team              MON
League             NL
Year             1974
RS                662
RA                657
W                  79
OBP             0.335
SLG              0.35
BA              0.254
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 161
OOBP              NaN
OSLG              NaN
WP               0.49
RD                  5
Name: 986, dtype: object)
<class 'pandas.core.series.Series'>
(987, Team              NYM
League             NL
Year             1974
RS                572
RA                646
W                  71
OBP             0.311
SLG             0.329
BA              0.235
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.44
RD                -74
Name: 987, dtype: object)
<class 'pandas.core.series.Series'>
(988, Team              NYY
League             AL
Year             1974
RS                671
RA                623
W                  89
OBP             0.324
SLG             0.368
BA              0.263
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.55
RD                 48
Name: 988, dtype: object)
<class 'pandas.core.series.Series'>
(989, Team              OAK
League             AL
Year             1974
RS                689
RA                551
W                  90
OBP             0.321
SLG             0.373
BA              0.247
Playoffs            1
RankSeason          3
RankPlayoffs        1
G                 162
OOBP              NaN
OSLG              NaN
WP               0.56
RD                138
Name: 989, dtype: object)
<class 'pandas.core.series.Series'>
(990, Team              PHI
League             NL
Year             1974
RS                676
RA                701
W                  80
OBP              0.32
SLG             0.373
BA              0.261
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.49
RD                -25
Name: 990, dtype: object)
<class 'pandas.core.series.Series'>
(991, Team              PIT
League             NL
Year             1974
RS                751
RA                657
W                  88
OBP             0.335
SLG             0.391
BA              0.274
Playoffs            1
RankSeason          4
RankPlayoffs        3
G                 162
OOBP              NaN
OSLG              NaN
WP               0.54
RD                 94
Name: 991, dtype: object)
<class 'pandas.core.series.Series'>
(992, Team              SDP
League             NL
Year             1974
RS                541
RA                830
W                  60
OBP             0.302
SLG              0.33
BA              0.229
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.37
RD               -289
Name: 992, dtype: object)
<class 'pandas.core.series.Series'>
(993, Team              SFG
League             NL
Year             1974
RS                634
RA                723
W                  72
OBP             0.322
SLG             0.358
BA              0.252
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.44
RD                -89
Name: 993, dtype: object)
<class 'pandas.core.series.Series'>
(994, Team              STL
League             NL
Year             1974
RS                677
RA                643
W                  86
OBP             0.331
SLG             0.365
BA              0.265
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 161
OOBP              NaN
OSLG              NaN
WP               0.53
RD                 34
Name: 994, dtype: object)
<class 'pandas.core.series.Series'>
(995, Team              TEX
League             AL
Year             1974
RS                690
RA                698
W                  83
OBP             0.336
SLG             0.377
BA              0.272
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 161
OOBP              NaN
OSLG              NaN
WP               0.52
RD                 -8
Name: 995, dtype: object)
<class 'pandas.core.series.Series'>
(996, Team              ATL
League             NL
Year             1973
RS                799
RA                774
W                  76
OBP             0.339
SLG             0.427
BA              0.266
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.47
RD                 25
Name: 996, dtype: object)
<class 'pandas.core.series.Series'>
(997, Team              BAL
League             AL
Year             1973
RS                754
RA                561
W                  97
OBP             0.345
SLG             0.389
BA              0.266
Playoffs            1
RankSeason          2
RankPlayoffs        3
G                 162
OOBP              NaN
OSLG              NaN
WP                0.6
RD                193
Name: 997, dtype: object)
<class 'pandas.core.series.Series'>
(998, Team              BOS
League             AL
Year             1973
RS                738
RA                647
W                  89
OBP             0.338
SLG             0.401
BA              0.267
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.55
RD                 91
Name: 998, dtype: object)
<class 'pandas.core.series.Series'>
(999, Team              CAL
League             AL
Year             1973
RS                629
RA                657
W                  79
OBP             0.318
SLG             0.348
BA              0.253
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.49
RD                -28
Name: 999, dtype: object)
<class 'pandas.core.series.Series'>
(1000, Team              CHC
League             NL
Year             1973
RS                614
RA                655
W                  77
OBP              0.32
SLG             0.357
BA              0.247
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 161
OOBP              NaN
OSLG              NaN
WP               0.48
RD                -41
Name: 1000, dtype: object)
<class 'pandas.core.series.Series'>
(1001, Team              CHW
League             AL
Year             1973
RS                652
RA                705
W                  77
OBP             0.324
SLG             0.372
BA              0.256
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.48
RD                -53
Name: 1001, dtype: object)
<class 'pandas.core.series.Series'>
(1002, Team              CIN
League             NL
Year             1973
RS                741
RA                621
W                  99
OBP             0.332
SLG             0.383
BA              0.254
Playoffs            1
RankSeason          1
RankPlayoffs        3
G                 162
OOBP              NaN
OSLG              NaN
WP               0.61
RD                120
Name: 1002, dtype: object)
<class 'pandas.core.series.Series'>
(1003, Team              CLE
League             AL
Year             1973
RS                680
RA                826
W                  71
OBP             0.315
SLG             0.387
BA              0.256
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.44
RD               -146
Name: 1003, dtype: object)
<class 'pandas.core.series.Series'>
(1004, Team              DET
League             AL
Year             1973
RS                642
RA                674
W                  85
OBP              0.32
SLG              0.39
BA              0.254
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.52
RD                -32
Name: 1004, dtype: object)
<class 'pandas.core.series.Series'>
(1005, Team              HOU
League             NL
Year             1973
RS                681
RA                672
W                  82
OBP             0.312
SLG             0.376
BA              0.251
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.51
RD                  9
Name: 1005, dtype: object)
<class 'pandas.core.series.Series'>
(1006, Team              KCR
League             AL
Year             1973
RS                755
RA                752
W                  88
OBP             0.339
SLG             0.381
BA              0.261
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.54
RD                  3
Name: 1006, dtype: object)
<class 'pandas.core.series.Series'>
(1007, Team              LAD
League             NL
Year             1973
RS                675
RA                565
W                  95
OBP             0.323
SLG             0.371
BA              0.263
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.59
RD                110
Name: 1007, dtype: object)
<class 'pandas.core.series.Series'>
(1008, Team              MIL
League             AL
Year             1973
RS                708
RA                731
W                  74
OBP             0.325
SLG             0.388
BA              0.253
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.46
RD                -23
Name: 1008, dtype: object)
<class 'pandas.core.series.Series'>
(1009, Team              MIN
League             AL
Year             1973
RS                738
RA                692
W                  81
OBP             0.342
SLG             0.393
BA               0.27
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP                0.5
RD                 46
Name: 1009, dtype: object)
<class 'pandas.core.series.Series'>
(1010, Team              MON
League             NL
Year             1973
RS                668
RA                702
W                  79
OBP              0.34
SLG             0.364
BA              0.251
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.49
RD                -34
Name: 1010, dtype: object)
<class 'pandas.core.series.Series'>
(1011, Team              NYM
League             NL
Year             1973
RS                608
RA                588
W                  82
OBP             0.315
SLG             0.338
BA              0.246
Playoffs            1
RankSeason          4
RankPlayoffs        2
G                 161
OOBP              NaN
OSLG              NaN
WP               0.51
RD                 20
Name: 1011, dtype: object)
<class 'pandas.core.series.Series'>
(1012, Team              NYY
League             AL
Year             1973
RS                641
RA                610
W                  80
OBP             0.322
SLG             0.378
BA              0.261
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.49
RD                 31
Name: 1012, dtype: object)
<class 'pandas.core.series.Series'>
(1013, Team              OAK
League             AL
Year             1973
RS                758
RA                615
W                  94
OBP             0.333
SLG             0.389
BA               0.26
Playoffs            1
RankSeason          3
RankPlayoffs        1
G                 162
OOBP              NaN
OSLG              NaN
WP               0.58
RD                143
Name: 1013, dtype: object)
<class 'pandas.core.series.Series'>
(1014, Team              PHI
League             NL
Year             1973
RS                642
RA                717
W                  71
OBP              0.31
SLG             0.371
BA              0.249
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.44
RD                -75
Name: 1014, dtype: object)
<class 'pandas.core.series.Series'>
(1015, Team              PIT
League             NL
Year             1973
RS                704
RA                693
W                  80
OBP             0.315
SLG             0.405
BA              0.261
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.49
RD                 11
Name: 1015, dtype: object)
<class 'pandas.core.series.Series'>
(1016, Team              SDP
League             NL
Year             1973
RS                548
RA                770
W                  60
OBP             0.296
SLG             0.351
BA              0.244
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.37
RD               -222
Name: 1016, dtype: object)
<class 'pandas.core.series.Series'>
(1017, Team              SFG
League             NL
Year             1973
RS                739
RA                702
W                  88
OBP             0.335
SLG             0.407
BA              0.262
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.54
RD                 37
Name: 1017, dtype: object)
<class 'pandas.core.series.Series'>
(1018, Team              STL
League             NL
Year             1973
RS                643
RA                603
W                  81
OBP             0.325
SLG             0.357
BA              0.259
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP                0.5
RD                 40
Name: 1018, dtype: object)
<class 'pandas.core.series.Series'>
(1019, Team              TEX
League             AL
Year             1973
RS                619
RA                844
W                  57
OBP             0.318
SLG             0.361
BA              0.255
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.35
RD               -225
Name: 1019, dtype: object)
<class 'pandas.core.series.Series'>
(1020, Team              ATL
League             NL
Year             1971
RS                643
RA                699
W                  82
OBP             0.312
SLG             0.385
BA              0.257
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.51
RD                -56
Name: 1020, dtype: object)
<class 'pandas.core.series.Series'>
(1021, Team              BAL
League             AL
Year             1971
RS                742
RA                530
W                 101
OBP             0.347
SLG             0.398
BA              0.261
Playoffs            1
RankSeason          1
RankPlayoffs        2
G                 158
OOBP              NaN
OSLG              NaN
WP               0.64
RD                212
Name: 1021, dtype: object)
<class 'pandas.core.series.Series'>
(1022, Team              BOS
League             AL
Year             1971
RS                691
RA                667
W                  85
OBP             0.322
SLG             0.397
BA              0.252
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.52
RD                 24
Name: 1022, dtype: object)
<class 'pandas.core.series.Series'>
(1023, Team              CAL
League             AL
Year             1971
RS                511
RA                576
W                  76
OBP              0.29
SLG             0.329
BA              0.231
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.47
RD                -65
Name: 1023, dtype: object)
<class 'pandas.core.series.Series'>
(1024, Team              CHC
League             NL
Year             1971
RS                637
RA                648
W                  83
OBP             0.325
SLG             0.378
BA              0.258
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.51
RD                -11
Name: 1024, dtype: object)
<class 'pandas.core.series.Series'>
(1025, Team              CHW
League             AL
Year             1971
RS                617
RA                597
W                  79
OBP             0.325
SLG             0.373
BA               0.25
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.49
RD                 20
Name: 1025, dtype: object)
<class 'pandas.core.series.Series'>
(1026, Team              CIN
League             NL
Year             1971
RS                586
RA                581
W                  79
OBP               0.3
SLG             0.366
BA              0.241
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.49
RD                  5
Name: 1026, dtype: object)
<class 'pandas.core.series.Series'>
(1027, Team              CLE
League             AL
Year             1971
RS                543
RA                747
W                  60
OBP               0.3
SLG             0.342
BA              0.238
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.37
RD               -204
Name: 1027, dtype: object)
<class 'pandas.core.series.Series'>
(1028, Team              DET
League             AL
Year             1971
RS                701
RA                645
W                  91
OBP             0.325
SLG             0.405
BA              0.254
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.56
RD                 56
Name: 1028, dtype: object)
<class 'pandas.core.series.Series'>
(1029, Team              HOU
League             NL
Year             1971
RS                585
RA                567
W                  79
OBP             0.302
SLG              0.34
BA               0.24
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.49
RD                 18
Name: 1029, dtype: object)
<class 'pandas.core.series.Series'>
(1030, Team              KCR
League             AL
Year             1971
RS                603
RA                566
W                  85
OBP             0.313
SLG             0.353
BA               0.25
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 161
OOBP              NaN
OSLG              NaN
WP               0.53
RD                 37
Name: 1030, dtype: object)

(1042, Team              STL
League             NL
Year             1971
RS                739
RA                699
W                  90
OBP             0.338
SLG             0.385
BA              0.275
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 163
OOBP              NaN
OSLG              NaN
WP               0.55
RD                 40
Name: 1042, dtype: object)
<class 'pandas.core.series.Series'>
(1043, Team              WSA
League             AL
Year             1971
RS                537
RA                660
W                  63
OBP             0.307
SLG             0.326
BA               0.23
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 159
OOBP              NaN
OSLG              NaN
WP                0.4
RD               -123
Name: 1043, dtype: object)
<class 'pandas.core.series.Series'>
(1044, Team              ATL
League             NL
Year             1970
RS                736
RA                772
W                  76
OBP             0.334
SLG             0.404
BA               0.27
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.47
RD                -36
Name: 1044, dtype: object)
<class 'pandas.core.series.Series'>
(1045, Team              BAL
League             AL
Year             1970
RS                792
RA                574
W                 108
OBP             0.344
SLG             0.401
BA              0.257
Playoffs            1
RankSeason          1
RankPlayoffs        1
G                 162
OOBP              NaN
OSLG              NaN
WP               0.67
RD                218
Name: 1045, dtype: object)
<class 'pandas.core.series.Series'>
(1046, Team              BOS
League             AL
Year             1970
RS                786
RA                722
W                  87
OBP             0.335
SLG             0.428
BA              0.262
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.54
RD                 64
Name: 1046, dtype: object)
<class 'pandas.core.series.Series'>
(1047, Team              CAL
League             AL
Year             1970
RS                631
RA                630
W                  86
OBP             0.309
SLG             0.363
BA              0.251
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.53
RD                  1
Name: 1047, dtype: object)
<class 'pandas.core.series.Series'>
(1048, Team              CHC
League             NL
Year             1970
RS                806
RA                679
W                  84
OBP             0.333
SLG             0.415
BA              0.259
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.52
RD                127
Name: 1048, dtype: object)
<class 'pandas.core.series.Series'>
(1049, Team              CHW
League             AL
Year             1970
RS                633
RA                822
W                  56
OBP             0.315
SLG             0.362
BA              0.253
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.35
RD               -189
Name: 1049, dtype: object)
<class 'pandas.core.series.Series'>
(1050, Team              CIN
League             NL
Year             1970
RS                775
RA                681
W                 102
OBP             0.336
SLG             0.436
BA               0.27
Playoffs            1
RankSeason          2
RankPlayoffs        2
G                 162
OOBP              NaN
OSLG              NaN
WP               0.63
RD                 94
Name: 1050, dtype: object)
<class 'pandas.core.series.Series'>
(1051, Team              CLE
League             AL
Year             1970
RS                649
RA                675
W                  76
OBP             0.314
SLG             0.394
BA              0.249
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.47
RD                -26
Name: 1051, dtype: object)
<class 'pandas.core.series.Series'>
(1052, Team              DET
League             AL
Year             1970
RS                666
RA                731
W                  79
OBP             0.322
SLG             0.374
BA              0.238
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.49
RD                -65
Name: 1052, dtype: object)
<class 'pandas.core.series.Series'>
(1053, Team              HOU
League             NL
Year             1970
RS                744
RA                763
W                  79
OBP             0.332
SLG             0.391
BA              0.259
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.49
RD                -19
Name: 1053, dtype: object)
<class 'pandas.core.series.Series'>
(1054, Team              KCR
League             AL
Year             1970
RS                611
RA                705
W                  65
OBP             0.309
SLG             0.348
BA              0.244
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP                0.4
RD                -94
Name: 1054, dtype: object)
<class 'pandas.core.series.Series'>
(1055, Team              LAD
League             NL
Year             1970
RS                749
RA                684
W                  87
OBP             0.334
SLG             0.382
BA               0.27
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 161
OOBP              NaN
OSLG              NaN
WP               0.54
RD                 65
Name: 1055, dtype: object)
<class 'pandas.core.series.Series'>
(1056, Team              MIL
League             AL
Year             1970
RS                613
RA                751
W                  65
OBP             0.319
SLG             0.358
BA              0.242
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 163
OOBP              NaN
OSLG              NaN
WP                0.4
RD               -138
Name: 1056, dtype: object)
<class 'pandas.core.series.Series'>
(1057, Team              MIN
League             AL
Year             1970
RS                744
RA                605
W                  98
OBP             0.327
SLG             0.403
BA              0.262
Playoffs            1
RankSeason          3
RankPlayoffs        3
G                 162
OOBP              NaN
OSLG              NaN
WP                0.6
RD                139
Name: 1057, dtype: object)
<class 'pandas.core.series.Series'>
(1058, Team              MON
League             NL
Year             1970
RS                687
RA                807
W                  73
OBP             0.323
SLG             0.365
BA              0.237
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.45
RD               -120
Name: 1058, dtype: object)
<class 'pandas.core.series.Series'>
(1059, Team              NYM
League             NL
Year             1970
RS                695
RA                630
W                  83
OBP             0.333
SLG              0.37
BA              0.249
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.51
RD                 65
Name: 1059, dtype: object)
<class 'pandas.core.series.Series'>
(1060, Team              NYY
League             AL
Year             1970
RS                680
RA                612
W                  93
OBP             0.324
SLG             0.365
BA              0.251
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 163
OOBP              NaN
OSLG              NaN
WP               0.57
RD                 68
Name: 1060, dtype: object)
<class 'pandas.core.series.Series'>
(1061, Team              OAK
League             AL
Year             1970
RS                678
RA                593
W                  89
OBP             0.325
SLG             0.392
BA              0.249
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.55
RD                 85
Name: 1061, dtype: object)
<class 'pandas.core.series.Series'>
(1062, Team              PHI
League             NL
Year             1970
RS                594
RA                730
W                  73
OBP             0.305
SLG             0.356
BA              0.238
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 161
OOBP              NaN
OSLG              NaN
WP               0.45
RD               -136
Name: 1062, dtype: object)
<class 'pandas.core.series.Series'>
(1063, Team              PIT
League             NL
Year             1970
RS                729
RA                664
W                  89
OBP             0.325
SLG             0.406
BA               0.27
Playoffs            1
RankSeason          4
RankPlayoffs        3
G                 162
OOBP              NaN
OSLG              NaN
WP               0.55
RD                 65
Name: 1063, dtype: object)
<class 'pandas.core.series.Series'>
(1064, Team              SDP
League             NL
Year             1970
RS                681
RA                788
W                  63
OBP             0.312
SLG             0.391
BA              0.246
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.39
RD               -107
Name: 1064, dtype: object)
<class 'pandas.core.series.Series'>
(1065, Team              SFG
League             NL
Year             1970
RS                831
RA                826
W                  86
OBP             0.351
SLG             0.409
BA              0.262
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.53
RD                  5
Name: 1065, dtype: object)
<class 'pandas.core.series.Series'>
(1066, Team              STL
League             NL
Year             1970
RS                744
RA                747
W                  76
OBP             0.331
SLG             0.379
BA              0.263
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.47
RD                 -3
Name: 1066, dtype: object)
<class 'pandas.core.series.Series'>
(1067, Team              WSA
League             AL
Year             1970
RS                626
RA                689
W                  70
OBP             0.321
SLG             0.358
BA              0.238
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.43
RD                -63
Name: 1067, dtype: object)
<class 'pandas.core.series.Series'>
(1068, Team              ATL
League             NL
Year             1969
RS                691
RA                631
W                  93
OBP             0.321
SLG              0.38
BA              0.258
Playoffs            1
RankSeason          4
RankPlayoffs        3
G                 162
OOBP              NaN
OSLG              NaN
WP               0.57
RD                 60
Name: 1068, dtype: object)
<class 'pandas.core.series.Series'>
(1069, Team              BAL
League             AL
Year             1969
RS                779
RA                517
W                 109
OBP             0.343
SLG             0.414
BA              0.265
Playoffs            1
RankSeason          1
RankPlayoffs        2
G                 162
OOBP              NaN
OSLG              NaN
WP               0.67
RD                262
Name: 1069, dtype: object)
<class 'pandas.core.series.Series'>
(1070, Team              BOS
League             AL
Year             1969
RS                743
RA                736
W                  87
OBP             0.333
SLG             0.415
BA              0.251
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.54
RD                  7
Name: 1070, dtype: object)
<class 'pandas.core.series.Series'>
(1071, Team              CAL
League             AL
Year             1969
RS                528
RA                652
W                  71
OBP               0.3
SLG             0.319
BA               0.23
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 163
OOBP              NaN
OSLG              NaN
WP               0.44
RD               -124
Name: 1071, dtype: object)
<class 'pandas.core.series.Series'>
(1072, Team              CHC
League             NL
Year             1969
RS                720
RA                611
W                  92
OBP             0.323
SLG             0.384
BA              0.253
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 163
OOBP              NaN
OSLG              NaN
WP               0.56
RD                109
Name: 1072, dtype: object)
<class 'pandas.core.series.Series'>
(1073, Team              CHW
League             AL
Year             1969
RS                625
RA                723
W                  68
OBP              0.32
SLG             0.357
BA              0.247
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.42
RD                -98
Name: 1073, dtype: object)
<class 'pandas.core.series.Series'>
(1074, Team              CIN
League             NL
Year             1969
RS                798
RA                768
W                  89
OBP             0.335
SLG             0.422
BA              0.277
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 163
OOBP              NaN
OSLG              NaN
WP               0.55
RD                 30
Name: 1074, dtype: object)
<class 'pandas.core.series.Series'>
(1075, Team              CLE
League             AL
Year             1969
RS                573
RA                717
W                  62
OBP             0.307
SLG             0.345
BA              0.237
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 161
OOBP              NaN
OSLG              NaN
WP               0.39
RD               -144
Name: 1075, dtype: object)
<class 'pandas.core.series.Series'>
(1076, Team              DET
League             AL
Year             1969
RS                701
RA                601
W                  90
OBP             0.316
SLG             0.387
BA              0.242
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.56
RD                100
Name: 1076, dtype: object)
<class 'pandas.core.series.Series'>
(1077, Team              HOU
League             NL
Year             1969
RS                676
RA                668
W                  81
OBP              0.33
SLG             0.352
BA               0.24
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP                0.5
RD                  8
Name: 1077, dtype: object)
<class 'pandas.core.series.Series'>
(1078, Team              KCR
League             AL
Year             1969
RS                586
RA                688
W                  69
OBP             0.309
SLG             0.338
BA               0.24
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 163
OOBP              NaN
OSLG              NaN
WP               0.42
RD               -102
Name: 1078, dtype: object)
<class 'pandas.core.series.Series'>
(1079, Team              LAD
League             NL
Year             1969
RS                645
RA                561
W                  85
OBP             0.315
SLG             0.359
BA              0.254
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.52
RD                 84
Name: 1079, dtype: object)
<class 'pandas.core.series.Series'>
(1080, Team              MIN
League             AL
Year             1969
RS                790
RA                618
W                  97
OBP              0.34
SLG             0.408
BA              0.268
Playoffs            1
RankSeason          3
RankPlayoffs        3
G                 162
OOBP              NaN
OSLG              NaN
WP                0.6
RD                172
Name: 1080, dtype: object)
<class 'pandas.core.series.Series'>
(1081, Team              MON
League             NL
Year             1969
RS                582
RA                791
W                  52
OBP              0.31
SLG             0.359
BA               0.24
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.32
RD               -209
Name: 1081, dtype: object)
<class 'pandas.core.series.Series'>
(1082, Team              NYM
League             NL
Year             1969
RS                632
RA                541
W                 100
OBP             0.311
SLG             0.351
BA              0.242
Playoffs            1
RankSeason          2
RankPlayoffs        1
G                 162
OOBP              NaN
OSLG              NaN
WP               0.62
RD                 91
Name: 1082, dtype: object)
<class 'pandas.core.series.Series'>
(1083, Team              NYY
League             AL
Year             1969
RS                562
RA                587
W                  80
OBP             0.308
SLG             0.344
BA              0.235
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.49
RD                -25
Name: 1083, dtype: object)
<class 'pandas.core.series.Series'>
(1084, Team              OAK
League             AL
Year             1969
RS                740
RA                678
W                  88
OBP             0.329
SLG             0.376
BA              0.249
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.54
RD                 62
Name: 1084, dtype: object)
<class 'pandas.core.series.Series'>
(1085, Team              PHI
League             NL
Year             1969
RS                645
RA                745
W                  63
OBP             0.312
SLG             0.372
BA              0.241
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.39
RD               -100
Name: 1085, dtype: object)
<class 'pandas.core.series.Series'>
(1086, Team              PIT
League             NL
Year             1969
RS                725
RA                652
W                  88
OBP             0.334
SLG             0.398
BA              0.277
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.54
RD                 73
Name: 1086, dtype: object)
<class 'pandas.core.series.Series'>

Name: 1185, dtype: object)
<class 'pandas.core.series.Series'>
(1186, Team              NYY
League             AL
Year             1964
RS                730
RA                577
W                  99
OBP             0.317
SLG             0.387
BA              0.253
Playoffs            1
RankSeason          1
RankPlayoffs        2
G                 164
OOBP              NaN
OSLG              NaN
WP                0.6
RD                153
Name: 1186, dtype: object)
<class 'pandas.core.series.Series'>
(1187, Team              PHI
League             NL
Year             1964
RS                693
RA                632
W                  92
OBP             0.315
SLG             0.391
BA              0.258
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.57
RD                 61
Name: 1187, dtype: object)
<class 'pandas.core.series.Series'>
(1188, Team              PIT
League             NL
Year             1964
RS                663
RA                636
W                  80
OBP             0.315
SLG             0.389
BA              0.264
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.49
RD                 27
Name: 1188, dtype: object)
<class 'pandas.core.series.Series'>
(1189, Team              SFG
League             NL
Year             1964
RS                656
RA                587
W                  90
OBP              0.31
SLG             0.382
BA              0.246
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.56
RD                 69
Name: 1189, dtype: object)
<class 'pandas.core.series.Series'>
(1190, Team              STL
League             NL
Year             1964
RS                715
RA                652
W                  93
OBP             0.324
SLG             0.392
BA              0.272
Playoffs            1
RankSeason          2
RankPlayoffs        1
G                 162
OOBP              NaN
OSLG              NaN
WP               0.57
RD                 63
Name: 1190, dtype: object)
<class 'pandas.core.series.Series'>
(1191, Team              WSA
League             AL
Year             1964
RS                578
RA                733
W                  62
OBP             0.299
SLG             0.348
BA              0.231
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.38
RD               -155
Name: 1191, dtype: object)
<class 'pandas.core.series.Series'>
(1192, Team              BAL
League             AL
Year             1963
RS                644
RA                621
W                  86
OBP              0.31
SLG              0.38
BA              0.249
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.53
RD                 23
Name: 1192, dtype: object)
<class 'pandas.core.series.Series'>
(1193, Team              BOS
League             AL
Year             1963
RS                666
RA                704
W                  76
OBP             0.312
SLG               0.4
BA              0.252
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 161
OOBP              NaN
OSLG              NaN
WP               0.47
RD                -38
Name: 1193, dtype: object)
<class 'pandas.core.series.Series'>
(1194, Team              CHC
League             NL
Year             1963
RS                570
RA                578
W                  82
OBP             0.297
SLG             0.363
BA              0.238
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.51
RD                 -8
Name: 1194, dtype: object)
<class 'pandas.core.series.Series'>
(1195, Team              CHW
League             AL
Year             1963
RS                683
RA                544
W                  94
OBP             0.323
SLG             0.365
BA               0.25
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.58
RD                139
Name: 1195, dtype: object)
<class 'pandas.core.series.Series'>
(1196, Team              CIN
League             NL
Year             1963
RS                648
RA                594
W                  86
OBP              0.31
SLG             0.371
BA              0.246
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.53
RD                 54
Name: 1196, dtype: object)
<class 'pandas.core.series.Series'>
(1197, Team              CLE
League             AL
Year             1963
RS                635
RA                702
W                  79
OBP             0.301
SLG             0.381
BA              0.239
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.49
RD                -67
Name: 1197, dtype: object)
<class 'pandas.core.series.Series'>
(1198, Team              DET
League             AL
Year             1963
RS                700
RA                703
W                  79
OBP             0.327
SLG             0.382
BA              0.252
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.49
RD                 -3
Name: 1198, dtype: object)
<class 'pandas.core.series.Series'>
(1199, Team              HOU
League             NL
Year             1963
RS                464
RA                640
W                  66
OBP             0.283
SLG             0.301
BA               0.22
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.41
RD               -176
Name: 1199, dtype: object)
<class 'pandas.core.series.Series'>
(1200, Team              KCA
League             AL
Year             1963
RS                615
RA                704
W                  73
OBP             0.313
SLG             0.353
BA              0.247
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.45
RD                -89
Name: 1200, dtype: object)
<class 'pandas.core.series.Series'>
(1201, Team              LAA
League             AL
Year             1963
RS                597
RA                660
W                  70
OBP             0.309
SLG             0.354
BA               0.25
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 161
OOBP              NaN
OSLG              NaN
WP               0.43
RD                -63
Name: 1201, dtype: object)
<class 'pandas.core.series.Series'>
(1202, Team              LAD
League             NL
Year             1963
RS                640
RA                550
W                  99
OBP             0.309
SLG             0.357
BA              0.251
Playoffs            1
RankSeason          2
RankPlayoffs        1
G                 163
OOBP              NaN
OSLG              NaN
WP               0.61
RD                 90
Name: 1202, dtype: object)
<class 'pandas.core.series.Series'>
(1203, Team              MIN
League             AL
Year             1963
RS                767
RA                602
W                  91
OBP             0.325
SLG              0.43
BA              0.255
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 161
OOBP              NaN
OSLG              NaN
WP               0.57
RD                165
Name: 1203, dtype: object)
<class 'pandas.core.series.Series'>
(1204, Team              MLN
League             NL
Year             1963
RS                677
RA                603
W                  84
OBP             0.312
SLG              0.37
BA              0.244
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 163
OOBP              NaN
OSLG              NaN
WP               0.52
RD                 74
Name: 1204, dtype: object)
<class 'pandas.core.series.Series'>
(1205, Team              NYM
League             NL
Year             1963
RS                501
RA                774
W                  51
OBP             0.285
SLG             0.315
BA              0.219
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.31
RD               -273
Name: 1205, dtype: object)
<class 'pandas.core.series.Series'>
(1206, Team              NYY
League             AL
Year             1963
RS                714
RA                547
W                 104
OBP             0.309
SLG             0.403
BA              0.252
Playoffs            1
RankSeason          1
RankPlayoffs        2
G                 161
OOBP              NaN
OSLG              NaN
WP               0.65
RD                167
Name: 1206, dtype: object)
<class 'pandas.core.series.Series'>
(1207, Team              PHI
League             NL
Year             1963
RS                642
RA                578
W                  87
OBP             0.306
SLG             0.381
BA              0.252
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.54
RD                 64
Name: 1207, dtype: object)
<class 'pandas.core.series.Series'>
(1208, Team              PIT
League             NL
Year             1963
RS                567
RA                595
W                  74
OBP             0.309
SLG             0.359
BA               0.25
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.46
RD                -28
Name: 1208, dtype: object)
<class 'pandas.core.series.Series'>
(1209, Team              SFG
League             NL
Year             1963
RS                725
RA                641
W                  88
OBP             0.316
SLG             0.414
BA              0.258
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.54
RD                 84
Name: 1209, dtype: object)
<class 'pandas.core.series.Series'>
(1210, Team              STL
League             NL
Year             1963
RS                747
RA                628
W                  93
OBP             0.326
SLG             0.403
BA              0.271
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.57
RD                119
Name: 1210, dtype: object)
<class 'pandas.core.series.Series'>
(1211, Team              WSA
League             AL
Year             1963
RS                578
RA                812
W                  56
OBP             0.293
SLG             0.351
BA              0.227
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.35
RD               -234
Name: 1211, dtype: object)
<class 'pandas.core.series.Series'>
(1212, Team              BAL
League             AL
Year             1962
RS                652
RA                680
W                  77
OBP             0.314
SLG             0.387
BA              0.248
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.48
RD                -28
Name: 1212, dtype: object)
<class 'pandas.core.series.Series'>
(1213, Team              BOS
League             AL
Year             1962
RS                707
RA                756
W                  76
OBP             0.324
SLG             0.403
BA              0.258
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 160
OOBP              NaN
OSLG              NaN
WP               0.48
RD                -49
Name: 1213, dtype: object)
<class 'pandas.core.series.Series'>
(1214, Team              CHC
League             NL
Year             1962
RS                632
RA                827
W                  59
OBP             0.317
SLG             0.377
BA              0.253
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.36
RD               -195
Name: 1214, dtype: object)
<class 'pandas.core.series.Series'>
(1215, Team              CHW
League             AL
Year             1962
RS                707
RA                658
W                  85
OBP             0.334
SLG             0.372
BA              0.257
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.52
RD                 49
Name: 1215, dtype: object)
<class 'pandas.core.series.Series'>
(1216, Team              CIN
League             NL
Year             1962
RS                802
RA                685
W                  98
OBP             0.332
SLG             0.417
BA               0.27
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP                0.6
RD                117
Name: 1216, dtype: object)
<class 'pandas.core.series.Series'>
(1217, Team              CLE
League             AL
Year             1962
RS                682
RA                745
W                  80
OBP             0.312
SLG             0.388
BA              0.245
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.49
RD                -63
Name: 1217, dtype: object)
<class 'pandas.core.series.Series'>
(1218, Team              DET
League             AL
Year             1962
RS                758
RA                692
W                  85
OBP              0.33
SLG             0.411
BA              0.248
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 161
OOBP              NaN
OSLG              NaN
WP               0.53
RD                 66
Name: 1218, dtype: object)
<class 'pandas.core.series.Series'>
(1219, Team              HOU
League             NL
Year             1962
RS                592
RA                717
W                  64
OBP              0.31
SLG             0.351
BA              0.246
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP                0.4
RD               -125
Name: 1219, dtype: object)
<class 'pandas.core.series.Series'>
(1220, Team              KCA
League             AL
Year             1962
RS                745
RA                837
W                  72
OBP             0.332
SLG             0.386
BA              0.263
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.44
RD                -92
Name: 1220, dtype: object)
<class 'pandas.core.series.Series'>
(1221, Team              LAA
League             AL
Year             1962
RS                718
RA                706
W                  86
OBP             0.325
SLG              0.38
BA               0.25
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.53
RD                 12
Name: 1221, dtype: object)
<class 'pandas.core.series.Series'>
(1222, Team              LAD
League             NL
Year             1962
RS                842
RA                697
W                 102
OBP             0.337
SLG               0.4
BA              0.268
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 165
OOBP              NaN
OSLG              NaN
WP               0.62
RD                145
Name: 1222, dtype: object)
<class 'pandas.core.series.Series'>
(1223, Team              MIN
League             AL
Year             1962
RS                798
RA                713
W                  91
OBP             0.338
SLG             0.412
BA               0.26
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 163
OOBP              NaN
OSLG              NaN
WP               0.56
RD                 85
Name: 1223, dtype: object)
<class 'pandas.core.series.Series'>
(1224, Team              MLN
League             NL
Year             1962
RS                730
RA                665
W                  86
OBP             0.326
SLG             0.403
BA              0.252
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 162
OOBP              NaN
OSLG              NaN
WP               0.53
RD                 65
Name: 1224, dtype: object)
<class 'pandas.core.series.Series'>
(1225, Team              NYM
League             NL
Year             1962
RS                617
RA                948
W                  40
OBP             0.318
SLG             0.361
BA               0.24
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 161
OOBP              NaN
OSLG              NaN
WP               0.25
RD               -331
Name: 1225, dtype: object)
<class 'pandas.core.series.Series'>
(1226, Team              NYY
League             AL
Year             1962
RS                817
RA                680
W                  96
OBP             0.337
SLG             0.426
BA              0.267
Playoffs            1
RankSeason          2
RankPlayoffs        1
G                 162
OOBP              NaN
OSLG              NaN
WP               0.59
RD                137
Name: 1226, dtype: object)
<class 'pandas.core.series.Series'>
(1227, Team             PHI
League            NL
Year            1962
RS               705
RA               759
W                 81
OBP             0.33
SLG             0.39
BA              0.26
Playoffs           0
RankSeason       NaN
RankPlayoffs     NaN
G                161
OOBP             NaN
OSLG             NaN
WP               0.5
RD               -54
Name: 1227, dtype: object)
<class 'pandas.core.series.Series'>
(1228, Team              PIT
League             NL
Year             1962
RS                706
RA                626
W                  93
OBP             0.321
SLG             0.394
BA              0.268
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 161
OOBP              NaN
OSLG              NaN
WP               0.58
RD                 80
Name: 1228, dtype: object)
<class 'pandas.core.series.Series'>
(1229, Team              SFG
League             NL
Year             1962
RS                878
RA                690
W                 103
OBP             0.341
SLG             0.441
BA              0.278
Playoffs            1
RankSeason          1
RankPlayoffs        2
G                 165
OOBP              NaN
OSLG              NaN
WP               0.62
RD                188
Name: 1229, dtype: object)
<class 'pandas.core.series.Series'>
(1230, Team              STL
League             NL
Year             1962
RS                774
RA                664
W                  84
OBP             0.335
SLG             0.394
BA              0.271
Playoffs            0
RankSeason        NaN
RankPlayoffs      NaN
G                 163
OOBP              NaN
OSLG              NaN
WP               0.52
RD                110
Name: 1230, dtype: object)

In [36]:
# we can use .itertuples() to loop over our dataframe rows instead. returns each dataframe row special data type

for row_named_tuple in df.itertuples():
    print(row_named_tuple)
    
# namedtupled is one of the specialied data types that exists in the collection modules. these data types using atribute look up. Index attribute.

Pandas(Index=0, Team='ARI', League='NL', Year=2012, RS=734, RA=688, W=81, OBP=0.32799999999999996, SLG=0.418, BA=0.259, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.317, OSLG=0.415, WP=0.5, RD=46)
Pandas(Index=1, Team='ATL', League='NL', Year=2012, RS=700, RA=600, W=94, OBP=0.32, SLG=0.389, BA=0.247, Playoffs=1, RankSeason=4.0, RankPlayoffs=5.0, G=162, OOBP=0.306, OSLG=0.37799999999999995, WP=0.58, RD=100)
Pandas(Index=2, Team='BAL', League='AL', Year=2012, RS=712, RA=705, W=93, OBP=0.311, SLG=0.41700000000000004, BA=0.247, Playoffs=1, RankSeason=5.0, RankPlayoffs=4.0, G=162, OOBP=0.315, OSLG=0.40299999999999997, WP=0.57, RD=7)
Pandas(Index=3, Team='BOS', League='AL', Year=2012, RS=734, RA=806, W=69, OBP=0.315, SLG=0.415, BA=0.26, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.331, OSLG=0.428, WP=0.43, RD=-72)
Pandas(Index=4, Team='CHC', League='NL', Year=2012, RS=613, RA=759, W=61, OBP=0.302, SLG=0.37799999999999995, BA=0.24, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.335, OSLG=0.424, WP=0.38, RD=-146)
Pandas(Index=5, Team='CHW', League='AL', Year=2012, RS=748, RA=676, W=85, OBP=0.318, SLG=0.42200000000000004, BA=0.255, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.319, OSLG=0.405, WP=0.52, RD=72)
Pandas(Index=6, Team='CIN', League='NL', Year=2012, RS=669, RA=588, W=97, OBP=0.315, SLG=0.41100000000000003, BA=0.251, Playoffs=1, RankSeason=2.0, RankPlayoffs=4.0, G=162, OOBP=0.305, OSLG=0.39, WP=0.6, RD=81)
Pandas(Index=7, Team='CLE', League='AL', Year=2012, RS=667, RA=845, W=68, OBP=0.324, SLG=0.381, BA=0.251, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.336, OSLG=0.43, WP=0.42, RD=-178)
Pandas(Index=8, Team='COL', League='NL', Year=2012, RS=758, RA=890, W=64, OBP=0.33, SLG=0.436, BA=0.27399999999999997, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.35700000000000004, OSLG=0.47, WP=0.4, RD=-132)
Pandas(Index=9, Team='DET', League='AL', Year=2012, RS=726, RA=670, W=88, OBP=0.335, SLG=0.42200000000000004, BA=0.268, Playoffs=1, RankSeason=6.0, RankPlayoffs=2.0, G=162, OOBP=0.314, OSLG=0.402, WP=0.54, RD=56)
Pandas(Index=10, Team='HOU', League='NL', Year=2012, RS=583, RA=794, W=55, OBP=0.302, SLG=0.371, BA=0.23600000000000002, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.337, OSLG=0.42700000000000005, WP=0.34, RD=-211)
Pandas(Index=11, Team='KCR', League='AL', Year=2012, RS=676, RA=746, W=72, OBP=0.317, SLG=0.4, BA=0.265, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.33899999999999997, OSLG=0.423, WP=0.44, RD=-70)
Pandas(Index=12, Team='LAA', League='AL', Year=2012, RS=767, RA=699, W=89, OBP=0.332, SLG=0.433, BA=0.27399999999999997, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.31, OSLG=0.40299999999999997, WP=0.55, RD=68)
Pandas(Index=13, Team='LAD', League='NL', Year=2012, RS=637, RA=597, W=86, OBP=0.317, SLG=0.374, BA=0.252, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.31, OSLG=0.364, WP=0.53, RD=40)
Pandas(Index=14, Team='MIA', League='NL', Year=2012, RS=609, RA=724, W=69, OBP=0.308, SLG=0.382, BA=0.244, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.327, OSLG=0.39899999999999997, WP=0.43, RD=-115)
Pandas(Index=15, Team='MIL', League='NL', Year=2012, RS=776, RA=733, W=83, OBP=0.325, SLG=0.43700000000000006, BA=0.259, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.326, OSLG=0.414, WP=0.51, RD=43)
Pandas(Index=16, Team='MIN', League='AL', Year=2012, RS=701, RA=832, W=66, OBP=0.325, SLG=0.39, BA=0.26, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.33299999999999996, OSLG=0.442, WP=0.41, RD=-131)
Pandas(Index=17, Team='NYM', League='NL', Year=2012, RS=650, RA=709, W=74, OBP=0.316, SLG=0.386, BA=0.249, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.315, OSLG=0.401, WP=0.46, RD=-59)
Pandas(Index=18, Team='NYY', League='AL', Year=2012, RS=804, RA=668, W=95, OBP=0.337, SLG=0.45299999999999996, BA=0.265, Playoffs=1, RankSeason=3.0, RankPlayoffs=3.0, G=162, OOBP=0.311, OSLG=0.419, WP=0.59, RD=136)
Pandas(Index=19, Team='OAK', League='AL', Year=2012, RS=713, RA=614, W=94, OBP=0.31, SLG=0.40399999999999997, BA=0.23800000000000002, Playoffs=1, RankSeason=4.0, RankPlayoffs=4.0, G=162, OOBP=0.306, OSLG=0.37799999999999995, WP=0.58, RD=99)
Pandas(Index=20, Team='PHI', League='NL', Year=2012, RS=684, RA=680, W=81, OBP=0.317, SLG=0.4, BA=0.255, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.306, OSLG=0.40700000000000003, WP=0.5, RD=4)
Pandas(Index=21, Team='PIT', League='NL', Year=2012, RS=651, RA=674, W=79, OBP=0.304, SLG=0.395, BA=0.243, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.314, OSLG=0.39, WP=0.49, RD=-23)
Pandas(Index=22, Team='SDP', League='NL', Year=2012, RS=651, RA=710, W=76, OBP=0.319, SLG=0.38, BA=0.247, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.319, OSLG=0.39799999999999996, WP=0.47, RD=-59)
Pandas(Index=23, Team='SEA', League='AL', Year=2012, RS=619, RA=651, W=75, OBP=0.29600000000000004, SLG=0.369, BA=0.23399999999999999, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.308, OSLG=0.39399999999999996, WP=0.46, RD=-32)
Pandas(Index=24, Team='SFG', League='NL', Year=2012, RS=718, RA=649, W=94, OBP=0.327, SLG=0.397, BA=0.26899999999999996, Playoffs=1, RankSeason=4.0, RankPlayoffs=1.0, G=162, OOBP=0.313, OSLG=0.39299999999999996, WP=0.58, RD=69)
Pandas(Index=25, Team='STL', League='NL', Year=2012, RS=765, RA=648, W=88, OBP=0.33799999999999997, SLG=0.42100000000000004, BA=0.271, Playoffs=1, RankSeason=6.0, RankPlayoffs=3.0, G=162, OOBP=0.313, OSLG=0.387, WP=0.54, RD=117)
Pandas(Index=26, Team='TBR', League='AL', Year=2012, RS=697, RA=577, W=90, OBP=0.317, SLG=0.39399999999999996, BA=0.24, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.294, OSLG=0.35200000000000004, WP=0.56, RD=120)
Pandas(Index=27, Team='TEX', League='AL', Year=2012, RS=808, RA=707, W=93, OBP=0.33399999999999996, SLG=0.446, BA=0.273, Playoffs=1, RankSeason=5.0, RankPlayoffs=5.0, G=162, OOBP=0.309, OSLG=0.408, WP=0.57, RD=101)
Pandas(Index=28, Team='TOR', League='AL', Year=2012, RS=716, RA=784, W=73, OBP=0.309, SLG=0.40700000000000003, BA=0.245, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.335, OSLG=0.43799999999999994, WP=0.45, RD=-68)
Pandas(Index=29, Team='WSN', League='NL', Year=2012, RS=731, RA=594, W=98, OBP=0.322, SLG=0.428, BA=0.261, Playoffs=1, RankSeason=1.0, RankPlayoffs=4.0, G=162, OOBP=0.303, OSLG=0.373, WP=0.6, RD=137)
Pandas(Index=30, Team='ARI', League='NL', Year=2011, RS=731, RA=662, W=94, OBP=0.322, SLG=0.413, BA=0.25, Playoffs=1, RankSeason=5.0, RankPlayoffs=4.0, G=162, OOBP=0.316, OSLG=0.409, WP=0.58, RD=69)
Pandas(Index=31, Team='ATL', League='NL', Year=2011, RS=641, RA=605, W=89, OBP=0.308, SLG=0.387, BA=0.243, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.31, OSLG=0.361, WP=0.55, RD=36)
Pandas(Index=32, Team='BAL', League='AL', Year=2011, RS=708, RA=860, W=69, OBP=0.316, SLG=0.413, BA=0.257, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.341, OSLG=0.46, WP=0.43, RD=-152)
Pandas(Index=33, Team='BOS', League='AL', Year=2011, RS=875, RA=737, W=90, OBP=0.349, SLG=0.461, BA=0.28, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.322, OSLG=0.392, WP=0.56, RD=138)
Pandas(Index=34, Team='CHC', League='NL', Year=2011, RS=654, RA=756, W=71, OBP=0.314, SLG=0.401, BA=0.256, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.335, OSLG=0.413, WP=0.44, RD=-102)
Pandas(Index=35, Team='CHW', League='AL', Year=2011, RS=654, RA=706, W=79, OBP=0.319, SLG=0.38799999999999996, BA=0.252, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.317, OSLG=0.397, WP=0.49, RD=-52)
Pandas(Index=36, Team='CIN', League='NL', Year=2011, RS=735, RA=720, W=79, OBP=0.326, SLG=0.408, BA=0.256, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.325, OSLG=0.415, WP=0.49, RD=15)
Pandas(Index=37, Team='CLE', League='AL', Year=2011, RS=704, RA=760, W=80, OBP=0.317, SLG=0.396, BA=0.25, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.32299999999999995, OSLG=0.413, WP=0.49, RD=-56)
Pandas(Index=38, Team='COL', League='NL', Year=2011, RS=735, RA=774, W=73, OBP=0.32899999999999996, SLG=0.41, BA=0.258, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.331, OSLG=0.431, WP=0.45, RD=-39)
Pandas(Index=39, Team='DET', League='AL', Year=2011, RS=787, RA=711, W=95, OBP=0.34, SLG=0.434, BA=0.27699999999999997, Playoffs=1, RankSeason=4.0, RankPlayoffs=3.0, G=162, OOBP=0.321, OSLG=0.396, WP=0.59, RD=76)
Pandas(Index=40, Team='FLA', League='NL', Year=2011, RS=625, RA=702, W=72, OBP=0.318, SLG=0.38799999999999996, BA=0.247, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.316, OSLG=0.401, WP=0.44, RD=-77)
Pandas(Index=41, Team='HOU', League='NL', Year=2011, RS=615, RA=796, W=56, OBP=0.311, SLG=0.374, BA=0.258, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.337, OSLG=0.43200000000000005, WP=0.35, RD=-181)
Pandas(Index=42, Team='KCR', League='AL', Year=2011, RS=730, RA=762, W=71, OBP=0.32899999999999996, SLG=0.415, BA=0.275, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.337, OSLG=0.425, WP=0.44, RD=-32)
Pandas(Index=43, Team='LAA', League='AL', Year=2011, RS=667, RA=633, W=86, OBP=0.313, SLG=0.402, BA=0.253, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.313, OSLG=0.38799999999999996, WP=0.53, RD=34)
Pandas(Index=44, Team='LAD', League='NL', Year=2011, RS=644, RA=612, W=82, OBP=0.322, SLG=0.375, BA=0.257, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=161, OOBP=0.31, OSLG=0.371, WP=0.51, RD=32)
Pandas(Index=45, Team='MIL', League='NL', Year=2011, RS=721, RA=638, W=96, OBP=0.325, SLG=0.425, BA=0.261, Playoffs=1, RankSeason=3.0, RankPlayoffs=3.0, G=162, OOBP=0.304, OSLG=0.385, WP=0.59, RD=83)
Pandas(Index=46, Team='MIN', League='AL', Year=2011, RS=619, RA=804, W=63, OBP=0.306, SLG=0.36, BA=0.247, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.34, OSLG=0.435, WP=0.39, RD=-185)
Pandas(Index=47, Team='NYM', League='NL', Year=2011, RS=718, RA=742, W=77, OBP=0.335, SLG=0.391, BA=0.264, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.332, OSLG=0.41100000000000003, WP=0.48, RD=-24)
Pandas(Index=48, Team='NYY', League='AL', Year=2011, RS=867, RA=657, W=97, OBP=0.34299999999999997, SLG=0.444, BA=0.263, Playoffs=1, RankSeason=2.0, RankPlayoffs=4.0, G=162, OOBP=0.322, OSLG=0.39899999999999997, WP=0.6, RD=210)
Pandas(Index=49, Team='OAK', League='AL', Year=2011, RS=645, RA=679, W=74, OBP=0.311, SLG=0.369, BA=0.244, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.317, OSLG=0.37799999999999995, WP=0.46, RD=-34)
Pandas(Index=50, Team='PHI', League='NL', Year=2011, RS=713, RA=529, W=102, OBP=0.32299999999999995, SLG=0.395, BA=0.253, Playoffs=1, RankSeason=1.0, RankPlayoffs=4.0, G=162, OOBP=0.29600000000000004, OSLG=0.361, WP=0.63, RD=184)
Pandas(Index=51, Team='PIT', League='NL', Year=2011, RS=610, RA=712, W=72, OBP=0.309, SLG=0.368, BA=0.244, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.33799999999999997, OSLG=0.409, WP=0.44, RD=-102)
Pandas(Index=52, Team='SDP', League='NL', Year=2011, RS=593, RA=611, W=71, OBP=0.305, SLG=0.349, BA=0.237, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.314, OSLG=0.375, WP=0.44, RD=-18)
Pandas(Index=53, Team='SEA', League='AL', Year=2011, RS=556, RA=675, W=67, OBP=0.292, SLG=0.348, BA=0.233, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.31, OSLG=0.386, WP=0.41, RD=-119)
Pandas(Index=54, Team='SFG', League='NL', Year=2011, RS=570, RA=578, W=86, OBP=0.303, SLG=0.368, BA=0.242, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.309, OSLG=0.34600000000000003, WP=0.53, RD=-8)
Pandas(Index=55, Team='STL', League='NL', Year=2011, RS=762, RA=692, W=90, OBP=0.341, SLG=0.425, BA=0.273, Playoffs=1, RankSeason=7.0, RankPlayoffs=1.0, G=162, OOBP=0.319, OSLG=0.39799999999999996, WP=0.56, RD=70)
Pandas(Index=56, Team='TBR', League='AL', Year=2011, RS=707, RA=614, W=91, OBP=0.322, SLG=0.402, BA=0.244, Playoffs=1, RankSeason=6.0, RankPlayoffs=4.0, G=162, OOBP=0.303, OSLG=0.38299999999999995, WP=0.56, RD=93)
Pandas(Index=57, Team='TEX', League='AL', Year=2011, RS=855, RA=677, W=96, OBP=0.34, SLG=0.46, BA=0.28300000000000003, Playoffs=1, RankSeason=3.0, RankPlayoffs=2.0, G=162, OOBP=0.307, OSLG=0.392, WP=0.59, RD=178)
Pandas(Index=58, Team='TOR', League='AL', Year=2011, RS=743, RA=761, W=81, OBP=0.317, SLG=0.413, BA=0.249, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.32799999999999996, OSLG=0.419, WP=0.5, RD=-18)
Pandas(Index=59, Team='WSN', League='NL', Year=2011, RS=624, RA=643, W=80, OBP=0.309, SLG=0.38299999999999995, BA=0.242, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=161, OOBP=0.319, OSLG=0.382, WP=0.5, RD=-19)
Pandas(Index=60, Team='ARI', League='NL', Year=2010, RS=713, RA=836, W=65, OBP=0.325, SLG=0.41600000000000004, BA=0.25, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.34, OSLG=0.44799999999999995, WP=0.4, RD=-123)
Pandas(Index=61, Team='ATL', League='NL', Year=2010, RS=738, RA=629, W=91, OBP=0.33899999999999997, SLG=0.401, BA=0.258, Playoffs=1, RankSeason=6.0, RankPlayoffs=4.0, G=162, OOBP=0.314, OSLG=0.376, WP=0.56, RD=109)
Pandas(Index=62, Team='BAL', League='AL', Year=2010, RS=613, RA=785, W=66, OBP=0.316, SLG=0.386, BA=0.259, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.336, OSLG=0.434, WP=0.41, RD=-172)
Pandas(Index=63, Team='BOS', League='AL', Year=2010, RS=818, RA=744, W=89, OBP=0.33899999999999997, SLG=0.451, BA=0.268, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.327, OSLG=0.39899999999999997, WP=0.55, RD=74)
Pandas(Index=64, Team='CHC', League='NL', Year=2010, RS=685, RA=767, W=75, OBP=0.32, SLG=0.401, BA=0.257, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.33399999999999996, OSLG=0.39799999999999996, WP=0.46, RD=-82)
Pandas(Index=65, Team='CHW', League='AL', Year=2010, RS=752, RA=704, W=88, OBP=0.332, SLG=0.42, BA=0.268, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.325, OSLG=0.395, WP=0.54, RD=48)
Pandas(Index=66, Team='CIN', League='NL', Year=2010, RS=790, RA=685, W=91, OBP=0.33799999999999997, SLG=0.436, BA=0.272, Playoffs=1, RankSeason=6.0, RankPlayoffs=4.0, G=162, OOBP=0.32299999999999995, OSLG=0.396, WP=0.56, RD=105)
Pandas(Index=67, Team='CLE', League='AL', Year=2010, RS=646, RA=752, W=69, OBP=0.322, SLG=0.37799999999999995, BA=0.248, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.342, OSLG=0.41600000000000004, WP=0.43, RD=-106)
Pandas(Index=68, Team='COL', League='NL', Year=2010, RS=770, RA=717, W=83, OBP=0.336, SLG=0.425, BA=0.263, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.326, OSLG=0.397, WP=0.51, RD=53)
Pandas(Index=69, Team='DET', League='AL', Year=2010, RS=751, RA=743, W=81, OBP=0.335, SLG=0.415, BA=0.268, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.332, OSLG=0.4, WP=0.5, RD=8)
Pandas(Index=70, Team='FLA', League='NL', Year=2010, RS=719, RA=717, W=80, OBP=0.321, SLG=0.40299999999999997, BA=0.254, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.331, OSLG=0.39799999999999996, WP=0.49, RD=2)
Pandas(Index=71, Team='HOU', League='NL', Year=2010, RS=611, RA=729, W=76, OBP=0.303, SLG=0.36200000000000004, BA=0.247, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.33, OSLG=0.402, WP=0.47, RD=-118)
Pandas(Index=72, Team='KCR', League='AL', Year=2010, RS=676, RA=845, W=67, OBP=0.331, SLG=0.39899999999999997, BA=0.27399999999999997, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.342, OSLG=0.435, WP=0.41, RD=-169)
Pandas(Index=73, Team='LAA', League='AL', Year=2010, RS=681, RA=702, W=80, OBP=0.311, SLG=0.39, BA=0.248, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.327, OSLG=0.40299999999999997, WP=0.49, RD=-21)
Pandas(Index=74, Team='LAD', League='NL', Year=2010, RS=667, RA=692, W=80, OBP=0.322, SLG=0.379, BA=0.252, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.316, OSLG=0.37799999999999995, WP=0.49, RD=-25)
Pandas(Index=75, Team='MIL', League='NL', Year=2010, RS=750, RA=804, W=77, OBP=0.335, SLG=0.424, BA=0.262, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.33799999999999997, OSLG=0.42700000000000005, WP=0.48, RD=-54)
Pandas(Index=76, Team='MIN', League='AL', Year=2010, RS=781, RA=671, W=94, OBP=0.341, SLG=0.42200000000000004, BA=0.273, Playoffs=1, RankSeason=4.0, RankPlayoffs=4.0, G=162, OOBP=0.317, OSLG=0.41700000000000004, WP=0.58, RD=110)
Pandas(Index=77, Team='NYM', League='NL', Year=2010, RS=656, RA=652, W=79, OBP=0.314, SLG=0.38299999999999995, BA=0.249, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.33, OSLG=0.39399999999999996, WP=0.49, RD=4)
Pandas(Index=78, Team='NYY', League='AL', Year=2010, RS=859, RA=693, W=95, OBP=0.35, SLG=0.436, BA=0.267, Playoffs=1, RankSeason=3.0, RankPlayoffs=3.0, G=162, OOBP=0.322, OSLG=0.39899999999999997, WP=0.59, RD=166)
Pandas(Index=79, Team='OAK', League='AL', Year=2010, RS=663, RA=626, W=81, OBP=0.324, SLG=0.37799999999999995, BA=0.256, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.313, OSLG=0.379, WP=0.5, RD=37)
Pandas(Index=80, Team='PHI', League='NL', Year=2010, RS=772, RA=640, W=97, OBP=0.332, SLG=0.413, BA=0.26, Playoffs=1, RankSeason=1.0, RankPlayoffs=3.0, G=162, OOBP=0.311, OSLG=0.405, WP=0.6, RD=132)
Pandas(Index=81, Team='PIT', League='NL', Year=2010, RS=587, RA=866, W=57, OBP=0.304, SLG=0.373, BA=0.242, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.348, OSLG=0.449, WP=0.35, RD=-279)
Pandas(Index=82, Team='SDP', League='NL', Year=2010, RS=665, RA=581, W=90, OBP=0.317, SLG=0.371, BA=0.24600000000000002, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.308, OSLG=0.368, WP=0.56, RD=84)
Pandas(Index=83, Team='SEA', League='AL', Year=2010, RS=513, RA=698, W=61, OBP=0.298, SLG=0.33899999999999997, BA=0.23600000000000002, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.313, OSLG=0.401, WP=0.38, RD=-185)
Pandas(Index=84, Team='SFG', League='NL', Year=2010, RS=697, RA=583, W=92, OBP=0.321, SLG=0.408, BA=0.257, Playoffs=1, RankSeason=5.0, RankPlayoffs=1.0, G=162, OOBP=0.313, OSLG=0.37, WP=0.57, RD=114)
Pandas(Index=85, Team='STL', League='NL', Year=2010, RS=736, RA=641, W=86, OBP=0.332, SLG=0.402, BA=0.263, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.319, OSLG=0.387, WP=0.53, RD=95)
Pandas(Index=86, Team='TBR', League='AL', Year=2010, RS=802, RA=649, W=96, OBP=0.33299999999999996, SLG=0.40299999999999997, BA=0.247, Playoffs=1, RankSeason=2.0, RankPlayoffs=4.0, G=162, OOBP=0.308, OSLG=0.40399999999999997, WP=0.59, RD=153)
Pandas(Index=87, Team='TEX', League='AL', Year=2010, RS=787, RA=687, W=90, OBP=0.33799999999999997, SLG=0.419, BA=0.276, Playoffs=1, RankSeason=7.0, RankPlayoffs=2.0, G=162, OOBP=0.319, OSLG=0.39, WP=0.56, RD=100)
Pandas(Index=88, Team='TOR', League='AL', Year=2010, RS=755, RA=728, W=85, OBP=0.312, SLG=0.45399999999999996, BA=0.248, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.326, OSLG=0.405, WP=0.52, RD=27)
Pandas(Index=89, Team='WSN', League='NL', Year=2010, RS=655, RA=742, W=69, OBP=0.318, SLG=0.39, BA=0.25, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.33, OSLG=0.41, WP=0.43, RD=-87)
Pandas(Index=90, Team='ARI', League='NL', Year=2009, RS=720, RA=782, W=70, OBP=0.324, SLG=0.418, BA=0.253, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.33, OSLG=0.419, WP=0.43, RD=-62)
Pandas(Index=91, Team='ATL', League='NL', Year=2009, RS=735, RA=641, W=86, OBP=0.33899999999999997, SLG=0.405, BA=0.263, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.32299999999999995, OSLG=0.39, WP=0.53, RD=94)
Pandas(Index=92, Team='BAL', League='AL', Year=2009, RS=741, RA=876, W=64, OBP=0.332, SLG=0.415, BA=0.268, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.353, OSLG=0.47600000000000003, WP=0.4, RD=-135)

Pandas(Index=143, Team='SEA', League='AL', Year=2008, RS=671, RA=811, W=61, OBP=0.318, SLG=0.389, BA=0.265, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.35100000000000003, OSLG=0.433, WP=0.38, RD=-140)
Pandas(Index=144, Team='SFG', League='NL', Year=2008, RS=640, RA=759, W=72, OBP=0.321, SLG=0.382, BA=0.262, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.341, OSLG=0.40399999999999997, WP=0.44, RD=-119)
Pandas(Index=145, Team='STL', League='NL', Year=2008, RS=779, RA=725, W=86, OBP=0.35, SLG=0.433, BA=0.281, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.332, OSLG=0.431, WP=0.53, RD=54)
Pandas(Index=146, Team='TBR', League='AL', Year=2008, RS=774, RA=671, W=97, OBP=0.34, SLG=0.42200000000000004, BA=0.26, Playoffs=1, RankSeason=2.0, RankPlayoffs=2.0, G=162, OOBP=0.314, OSLG=0.4, WP=0.6, RD=103)
Pandas(Index=147, Team='TEX', League='AL', Year=2008, RS=901, RA=967, W=79, OBP=0.354, SLG=0.462, BA=0.28300000000000003, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.36200000000000004, OSLG=0.455, WP=0.49, RD=-66)
Pandas(Index=148, Team='TOR', League='AL', Year=2008, RS=714, RA=610, W=86, OBP=0.331, SLG=0.39899999999999997, BA=0.264, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.309, OSLG=0.38, WP=0.53, RD=104)
Pandas(Index=149, Team='WSN', League='NL', Year=2008, RS=641, RA=825, W=59, OBP=0.32299999999999995, SLG=0.373, BA=0.251, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=161, OOBP=0.34299999999999997, OSLG=0.436, WP=0.37, RD=-184)
Pandas(Index=150, Team='ARI', League='NL', Year=2007, RS=712, RA=732, W=90, OBP=0.321, SLG=0.413, BA=0.25, Playoffs=1, RankSeason=3.0, RankPlayoffs=3.0, G=162, OOBP=0.33399999999999996, OSLG=0.42, WP=0.56, RD=-20)
Pandas(Index=151, Team='ATL', League='NL', Year=2007, RS=810, RA=733, W=84, OBP=0.33899999999999997, SLG=0.435, BA=0.275, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.327, OSLG=0.415, WP=0.52, RD=77)
Pandas(Index=152, Team='BAL', League='AL', Year=2007, RS=756, RA=868, W=69, OBP=0.33299999999999996, SLG=0.41200000000000003, BA=0.272, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.354, OSLG=0.41200000000000003, WP=0.43, RD=-112)
Pandas(Index=153, Team='BOS', League='AL', Year=2007, RS=867, RA=657, W=96, OBP=0.36200000000000004, SLG=0.444, BA=0.27899999999999997, Playoffs=1, RankSeason=1.0, RankPlayoffs=1.0, G=162, OOBP=0.314, OSLG=0.392, WP=0.59, RD=210)
Pandas(Index=154, Team='CHC', League='NL', Year=2007, RS=752, RA=690, W=85, OBP=0.33299999999999996, SLG=0.42200000000000004, BA=0.271, Playoffs=1, RankSeason=5.0, RankPlayoffs=4.0, G=162, OOBP=0.322, OSLG=0.39899999999999997, WP=0.52, RD=62)
Pandas(Index=155, Team='CHW', League='AL', Year=2007, RS=693, RA=839, W=72, OBP=0.318, SLG=0.40399999999999997, BA=0.24600000000000002, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.33799999999999997, OSLG=0.435, WP=0.44, RD=-146)
Pandas(Index=156, Team='CIN', League='NL', Year=2007, RS=783, RA=853, W=72, OBP=0.335, SLG=0.436, BA=0.267, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.34299999999999997, OSLG=0.456, WP=0.44, RD=-70)
Pandas(Index=157, Team='CLE', League='AL', Year=2007, RS=811, RA=704, W=96, OBP=0.34299999999999997, SLG=0.428, BA=0.268, Playoffs=1, RankSeason=1.0, RankPlayoffs=3.0, G=162, OOBP=0.322, OSLG=0.40700000000000003, WP=0.59, RD=107)
Pandas(Index=158, Team='COL', League='NL', Year=2007, RS=860, RA=758, W=90, OBP=0.354, SLG=0.43700000000000006, BA=0.28, Playoffs=1, RankSeason=3.0, RankPlayoffs=2.0, G=163, OOBP=0.33, OSLG=0.423, WP=0.55, RD=102)
Pandas(Index=159, Team='DET', League='AL', Year=2007, RS=887, RA=797, W=88, OBP=0.345, SLG=0.45799999999999996, BA=0.287, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.33799999999999997, OSLG=0.42700000000000005, WP=0.54, RD=90)
Pandas(Index=160, Team='FLA', League='NL', Year=2007, RS=790, RA=891, W=71, OBP=0.336, SLG=0.44799999999999995, BA=0.267, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.364, OSLG=0.442, WP=0.44, RD=-101)
Pandas(Index=161, Team='HOU', League='NL', Year=2007, RS=723, RA=813, W=73, OBP=0.33, SLG=0.41200000000000003, BA=0.26, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.337, OSLG=0.45399999999999996, WP=0.45, RD=-90)
Pandas(Index=162, Team='KCR', League='AL', Year=2007, RS=706, RA=778, W=69, OBP=0.322, SLG=0.38799999999999996, BA=0.261, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.33899999999999997, OSLG=0.445, WP=0.43, RD=-72)
Pandas(Index=163, Team='LAA', League='AL', Year=2007, RS=822, RA=731, W=94, OBP=0.345, SLG=0.41700000000000004, BA=0.284, Playoffs=1, RankSeason=2.0, RankPlayoffs=4.0, G=162, OOBP=0.32799999999999996, OSLG=0.41200000000000003, WP=0.58, RD=91)
Pandas(Index=164, Team='LAD', League='NL', Year=2007, RS=735, RA=727, W=82, OBP=0.337, SLG=0.406, BA=0.275, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.326, OSLG=0.39899999999999997, WP=0.51, RD=8)
Pandas(Index=165, Team='MIL', League='NL', Year=2007, RS=801, RA=776, W=83, OBP=0.32899999999999996, SLG=0.456, BA=0.262, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.33299999999999996, OSLG=0.42200000000000004, WP=0.51, RD=25)
Pandas(Index=166, Team='MIN', League='AL', Year=2007, RS=718, RA=725, W=79, OBP=0.33, SLG=0.391, BA=0.264, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.324, OSLG=0.431, WP=0.49, RD=-7)
Pandas(Index=167, Team='NYM', League='NL', Year=2007, RS=804, RA=750, W=88, OBP=0.342, SLG=0.43200000000000005, BA=0.275, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.32899999999999996, OSLG=0.409, WP=0.54, RD=54)
Pandas(Index=168, Team='NYY', League='AL', Year=2007, RS=968, RA=777, W=94, OBP=0.366, SLG=0.46299999999999997, BA=0.29, Playoffs=1, RankSeason=2.0, RankPlayoffs=4.0, G=162, OOBP=0.34, OSLG=0.41700000000000004, WP=0.58, RD=191)
Pandas(Index=169, Team='OAK', League='AL', Year=2007, RS=741, RA=758, W=76, OBP=0.33799999999999997, SLG=0.40700000000000003, BA=0.256, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.32899999999999996, OSLG=0.40399999999999997, WP=0.47, RD=-17)
Pandas(Index=170, Team='PHI', League='NL', Year=2007, RS=892, RA=821, W=89, OBP=0.354, SLG=0.45799999999999996, BA=0.27399999999999997, Playoffs=1, RankSeason=4.0, RankPlayoffs=4.0, G=162, OOBP=0.34600000000000003, OSLG=0.451, WP=0.55, RD=71)
Pandas(Index=171, Team='PIT', League='NL', Year=2007, RS=724, RA=846, W=68, OBP=0.325, SLG=0.41100000000000003, BA=0.263, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.35200000000000004, OSLG=0.447, WP=0.42, RD=-122)
Pandas(Index=172, Team='SDP', League='NL', Year=2007, RS=741, RA=666, W=89, OBP=0.322, SLG=0.41100000000000003, BA=0.251, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=163, OOBP=0.311, OSLG=0.374, WP=0.55, RD=75)
Pandas(Index=173, Team='SEA', League='AL', Year=2007, RS=794, RA=813, W=88, OBP=0.337, SLG=0.425, BA=0.287, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.349, OSLG=0.431, WP=0.54, RD=-19)
Pandas(Index=174, Team='SFG', League='NL', Year=2007, RS=683, RA=720, W=71, OBP=0.322, SLG=0.387, BA=0.254, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.33399999999999996, OSLG=0.405, WP=0.44, RD=-37)
Pandas(Index=175, Team='STL', League='NL', Year=2007, RS=725, RA=829, W=78, OBP=0.337, SLG=0.405, BA=0.27399999999999997, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.336, OSLG=0.431, WP=0.48, RD=-104)
Pandas(Index=176, Team='TBD', League='AL', Year=2007, RS=782, RA=944, W=66, OBP=0.336, SLG=0.433, BA=0.268, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.358, OSLG=0.467, WP=0.41, RD=-162)
Pandas(Index=177, Team='TEX', League='AL', Year=2007, RS=816, RA=844, W=75, OBP=0.32799999999999996, SLG=0.426, BA=0.263, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.35600000000000004, OSLG=0.423, WP=0.46, RD=-28)
Pandas(Index=178, Team='TOR', League='AL', Year=2007, RS=753, RA=699, W=83, OBP=0.327, SLG=0.419, BA=0.259, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.315, OSLG=0.391, WP=0.51, RD=54)
Pandas(Index=179, Team='WSN', League='NL', Year=2007, RS=673, RA=783, W=73, OBP=0.325, SLG=0.39, BA=0.256, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.33899999999999997, OSLG=0.433, WP=0.45, RD=-110)
Pandas(Index=180, Team='ARI', League='NL', Year=2006, RS=773, RA=788, W=76, OBP=0.331, SLG=0.424, BA=0.267, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.335, OSLG=0.431, WP=0.47, RD=-15)
Pandas(Index=181, Team='ATL', League='NL', Year=2006, RS=849, RA=805, W=79, OBP=0.337, SLG=0.455, BA=0.27, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.34299999999999997, OSLG=0.43799999999999994, WP=0.49, RD=44)
Pandas(Index=182, Team='BAL', League='AL', Year=2006, RS=768, RA=899, W=70, OBP=0.33899999999999997, SLG=0.424, BA=0.27699999999999997, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.35700000000000004, OSLG=0.462, WP=0.43, RD=-131)
Pandas(Index=183, Team='BOS', League='AL', Year=2006, RS=820, RA=825, W=86, OBP=0.35100000000000003, SLG=0.435, BA=0.26899999999999996, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.34299999999999997, OSLG=0.447, WP=0.53, RD=-5)
Pandas(Index=184, Team='CHC', League='NL', Year=2006, RS=716, RA=834, W=66, OBP=0.319, SLG=0.42200000000000004, BA=0.268, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.342, OSLG=0.431, WP=0.41, RD=-118)
Pandas(Index=185, Team='CHW', League='AL', Year=2006, RS=868, RA=794, W=90, OBP=0.342, SLG=0.46399999999999997, BA=0.28, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.326, OSLG=0.44, WP=0.56, RD=74)
Pandas(Index=186, Team='CIN', League='NL', Year=2006, RS=749, RA=801, W=80, OBP=0.336, SLG=0.43200000000000005, BA=0.257, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.337, OSLG=0.457, WP=0.49, RD=-52)
Pandas(Index=187, Team='CLE', League='AL', Year=2006, RS=870, RA=782, W=78, OBP=0.349, SLG=0.457, BA=0.28, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.335, OSLG=0.431, WP=0.48, RD=88)
Pandas(Index=188, Team='COL', League='NL', Year=2006, RS=813, RA=812, W=76, OBP=0.341, SLG=0.433, BA=0.27, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.34600000000000003, OSLG=0.43799999999999994, WP=0.47, RD=1)
Pandas(Index=189, Team='DET', League='AL', Year=2006, RS=822, RA=675, W=95, OBP=0.32899999999999996, SLG=0.449, BA=0.27399999999999997, Playoffs=1, RankSeason=3.0, RankPlayoffs=2.0, G=162, OOBP=0.321, OSLG=0.405, WP=0.59, RD=147)
Pandas(Index=190, Team='FLA', League='NL', Year=2006, RS=758, RA=772, W=78, OBP=0.331, SLG=0.435, BA=0.264, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.34700000000000003, OSLG=0.423, WP=0.48, RD=-14)
Pandas(Index=191, Team='HOU', League='NL', Year=2006, RS=735, RA=719, W=82, OBP=0.332, SLG=0.409, BA=0.255, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.319, OSLG=0.42100000000000004, WP=0.51, RD=16)
Pandas(Index=192, Team='KCR', League='AL', Year=2006, RS=757, RA=971, W=62, OBP=0.332, SLG=0.41100000000000003, BA=0.271, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.36700000000000005, OSLG=0.47600000000000003, WP=0.38, RD=-214)
Pandas(Index=193, Team='LAA', League='AL', Year=2006, RS=766, RA=732, W=89, OBP=0.33399999999999996, SLG=0.425, BA=0.27399999999999997, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.316, OSLG=0.402, WP=0.55, RD=34)
Pandas(Index=194, Team='LAD', League='NL', Year=2006, RS=820, RA=751, W=88, OBP=0.348, SLG=0.43200000000000005, BA=0.276, Playoffs=1, RankSeason=5.0, RankPlayoffs=4.0, G=162, OOBP=0.33, OSLG=0.418, WP=0.54, RD=69)
Pandas(Index=195, Team='MIL', League='NL', Year=2006, RS=730, RA=833, W=75, OBP=0.327, SLG=0.42, BA=0.258, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.33299999999999996, OSLG=0.43799999999999994, WP=0.46, RD=-103)
Pandas(Index=196, Team='MIN', League='AL', Year=2006, RS=801, RA=683, W=96, OBP=0.34700000000000003, SLG=0.425, BA=0.287, Playoffs=1, RankSeason=2.0, RankPlayoffs=4.0, G=162, OOBP=0.312, OSLG=0.423, WP=0.59, RD=118)
Pandas(Index=197, Team='NYM', League='NL', Year=2006, RS=834, RA=731, W=97, OBP=0.33399999999999996, SLG=0.445, BA=0.264, Playoffs=1, RankSeason=1.0, RankPlayoffs=3.0, G=162, OOBP=0.32299999999999995, OSLG=0.40700000000000003, WP=0.6, RD=103)
Pandas(Index=198, Team='NYY', League='AL', Year=2006, RS=930, RA=767, W=97, OBP=0.363, SLG=0.461, BA=0.285, Playoffs=1, RankSeason=1.0, RankPlayoffs=4.0, G=162, OOBP=0.326, OSLG=0.413, WP=0.6, RD=163)
Pandas(Index=199, Team='OAK', League='AL', Year=2006, RS=771, RA=727, W=93, OBP=0.34, SLG=0.41200000000000003, BA=0.26, Playoffs=1, RankSeason=4.0, RankPlayoffs=3.0, G=162, OOBP=0.33799999999999997, OSLG=0.42200000000000004, WP=0.57, RD=44)
Pandas(Index=200, Team='PHI', League='NL', Year=2006, RS=865, RA=812, W=85, OBP=0.34700000000000003, SLG=0.447, BA=0.267, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.33899999999999997, OSLG=0.46, WP=0.52, RD=53)
Pandas(Index=201, Team='PIT', League='NL', Year=2006, RS=691, RA=797, W=67, OBP=0.327, SLG=0.397, BA=0.263, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.35700000000000004, OSLG=0.431, WP=0.41, RD=-106)
Pandas(Index=202, Team='SDP', League='NL', Year=2006, RS=731, RA=679, W=88, OBP=0.332, SLG=0.41600000000000004, BA=0.263, Playoffs=1, RankSeason=5.0, RankPlayoffs=4.0, G=162, OOBP=0.312, OSLG=0.40399999999999997, WP=0.54, RD=52)
Pandas(Index=203, Team='SEA', League='AL', Year=2006, RS=756, RA=792, W=78, OBP=0.325, SLG=0.424, BA=0.272, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.337, OSLG=0.43200000000000005, WP=0.48, RD=-36)
Pandas(Index=204, Team='SFG', League='NL', Year=2006, RS=746, RA=790, W=76, OBP=0.324, SLG=0.42200000000000004, BA=0.259, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=161, OOBP=0.337, OSLG=0.415, WP=0.47, RD=-44)
Pandas(Index=205, Team='STL', League='NL', Year=2006, RS=781, RA=762, W=83, OBP=0.337, SLG=0.431, BA=0.26899999999999996, Playoffs=1, RankSeason=6.0, RankPlayoffs=1.0, G=161, OOBP=0.337, OSLG=0.44299999999999995, WP=0.52, RD=19)
Pandas(Index=206, Team='TBD', League='AL', Year=2006, RS=689, RA=856, W=61, OBP=0.314, SLG=0.42, BA=0.255, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.358, OSLG=0.452, WP=0.38, RD=-167)
Pandas(Index=207, Team='TEX', League='AL', Year=2006, RS=835, RA=784, W=80, OBP=0.33799999999999997, SLG=0.446, BA=0.278, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.341, OSLG=0.424, WP=0.49, RD=51)
Pandas(Index=208, Team='TOR', League='AL', Year=2006, RS=809, RA=754, W=87, OBP=0.348, SLG=0.46299999999999997, BA=0.284, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.32799999999999996, OSLG=0.42200000000000004, WP=0.54, RD=55)
Pandas(Index=209, Team='WSN', League='NL', Year=2006, RS=746, RA=872, W=71, OBP=0.33799999999999997, SLG=0.418, BA=0.262, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.349, OSLG=0.447, WP=0.44, RD=-126)
Pandas(Index=210, Team='ARI', League='NL', Year=2005, RS=696, RA=856, W=77, OBP=0.332, SLG=0.42100000000000004, BA=0.256, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.345, OSLG=0.455, WP=0.48, RD=-160)
Pandas(Index=211, Team='ATL', League='NL', Year=2005, RS=769, RA=674, W=90, OBP=0.33299999999999996, SLG=0.435, BA=0.265, Playoffs=1, RankSeason=4.0, RankPlayoffs=4.0, G=162, OOBP=0.33299999999999996, OSLG=0.406, WP=0.56, RD=95)
Pandas(Index=212, Team='BAL', League='AL', Year=2005, RS=729, RA=800, W=74, OBP=0.327, SLG=0.434, BA=0.26899999999999996, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.336, OSLG=0.41600000000000004, WP=0.46, RD=-71)
Pandas(Index=213, Team='BOS', League='AL', Year=2005, RS=910, RA=805, W=95, OBP=0.35700000000000004, SLG=0.45399999999999996, BA=0.281, Playoffs=1, RankSeason=3.0, RankPlayoffs=4.0, G=162, OOBP=0.335, OSLG=0.441, WP=0.59, RD=105)
Pandas(Index=214, Team='CHC', League='NL', Year=2005, RS=703, RA=714, W=79, OBP=0.324, SLG=0.44, BA=0.27, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.325, OSLG=0.40700000000000003, WP=0.49, RD=-11)
Pandas(Index=215, Team='CHW', League='AL', Year=2005, RS=741, RA=645, W=99, OBP=0.322, SLG=0.425, BA=0.262, Playoffs=1, RankSeason=2.0, RankPlayoffs=1.0, G=162, OOBP=0.31, OSLG=0.397, WP=0.61, RD=96)
Pandas(Index=216, Team='CIN', League='NL', Year=2005, RS=820, RA=889, W=73, OBP=0.33899999999999997, SLG=0.446, BA=0.261, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=163, OOBP=0.35200000000000004, OSLG=0.483, WP=0.45, RD=-69)
Pandas(Index=217, Team='CLE', League='AL', Year=2005, RS=790, RA=642, W=93, OBP=0.33399999999999996, SLG=0.45299999999999996, BA=0.271, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.302, OSLG=0.387, WP=0.57, RD=148)
Pandas(Index=218, Team='COL', League='NL', Year=2005, RS=740, RA=862, W=67, OBP=0.33299999999999996, SLG=0.41100000000000003, BA=0.267, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.36200000000000004, OSLG=0.457, WP=0.41, RD=-122)
Pandas(Index=219, Team='DET', League='AL', Year=2005, RS=723, RA=787, W=71, OBP=0.321, SLG=0.428, BA=0.272, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.33, OSLG=0.436, WP=0.44, RD=-64)
Pandas(Index=220, Team='FLA', League='NL', Year=2005, RS=717, RA=732, W=83, OBP=0.33899999999999997, SLG=0.409, BA=0.272, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.33899999999999997, OSLG=0.402, WP=0.51, RD=-15)
Pandas(Index=221, Team='HOU', League='NL', Year=2005, RS=693, RA=609, W=89, OBP=0.322, SLG=0.408, BA=0.256, Playoffs=1, RankSeason=5.0, RankPlayoffs=2.0, G=163, OOBP=0.308, OSLG=0.389, WP=0.55, RD=84)
Pandas(Index=222, Team='KCR', League='AL', Year=2005, RS=701, RA=935, W=56, OBP=0.32, SLG=0.396, BA=0.263, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.36200000000000004, OSLG=0.46299999999999997, WP=0.35, RD=-234)
Pandas(Index=223, Team='LAA', League='AL', Year=2005, RS=761, RA=643, W=95, OBP=0.325, SLG=0.409, BA=0.27, Playoffs=1, RankSeason=3.0, RankPlayoffs=3.0, G=162, OOBP=0.312, OSLG=0.401, WP=0.59, RD=118)
Pandas(Index=224, Team='LAD', League='NL', Year=2005, RS=685, RA=755, W=71, OBP=0.326, SLG=0.395, BA=0.253, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.327, OSLG=0.429, WP=0.44, RD=-70)
Pandas(Index=225, Team='MIL', League='NL', Year=2005, RS=726, RA=697, W=81, OBP=0.331, SLG=0.423, BA=0.259, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.324, OSLG=0.408, WP=0.5, RD=29)
Pandas(Index=226, Team='MIN', League='AL', Year=2005, RS=688, RA=662, W=83, OBP=0.32299999999999995, SLG=0.391, BA=0.259, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.307, OSLG=0.408, WP=0.51, RD=26)
Pandas(Index=227, Team='NYM', League='NL', Year=2005, RS=722, RA=648, W=83, OBP=0.322, SLG=0.41600000000000004, BA=0.258, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.321, OSLG=0.387, WP=0.51, RD=74)
Pandas(Index=228, Team='NYY', League='AL', Year=2005, RS=886, RA=789, W=95, OBP=0.355, SLG=0.45, BA=0.276, Playoffs=1, RankSeason=3.0, RankPlayoffs=4.0, G=162, OOBP=0.332, OSLG=0.42200000000000004, WP=0.59, RD=97)
Pandas(Index=229, Team='OAK', League='AL', Year=2005, RS=772, RA=658, W=88, OBP=0.33, SLG=0.40700000000000003, BA=0.262, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.311, OSLG=0.382, WP=0.54, RD=114)
Pandas(Index=230, Team='PHI', League='NL', Year=2005, RS=807, RA=726, W=88, OBP=0.348, SLG=0.423, BA=0.27, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.32, OSLG=0.426, WP=0.54, RD=81)
Pandas(Index=231, Team='PIT', League='NL', Year=2005, RS=680, RA=769, W=67, OBP=0.322, SLG=0.4, BA=0.259, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=0.344, OSLG=0.424, WP=0.41, RD=-89)
Pandas(Index=232, Team='SDP', League='NL', Year=2005, RS=684, RA=726, W=82, OBP=0.33299999999999996, SLG=0.391, BA=0.257, Playoffs=1, RankSeason=6.0, RankPlayoffs=4.0, G=162, OOBP=0.322, OSLG=0.408, WP=0.51, RD=-42)

Pandas(Index=1156, Team='CHW', League='AL', Year=1965, RS=647, RA=555, W=95, OBP=0.315, SLG=0.364, BA=0.24600000000000002, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=nan, OSLG=nan, WP=0.59, RD=92)
Pandas(Index=1157, Team='CIN', League='NL', Year=1965, RS=825, RA=704, W=89, OBP=0.33899999999999997, SLG=0.439, BA=0.273, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=nan, OSLG=nan, WP=0.55, RD=121)
Pandas(Index=1158, Team='CLE', League='AL', Year=1965, RS=663, RA=613, W=87, OBP=0.315, SLG=0.379, BA=0.25, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=nan, OSLG=nan, WP=0.54, RD=50)
Pandas(Index=1159, Team='DET', League='AL', Year=1965, RS=680, RA=602, W=89, OBP=0.312, SLG=0.374, BA=0.23800000000000002, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=nan, OSLG=nan, WP=0.55, RD=78)
Pandas(Index=1160, Team='HOU', League='NL', Year=1965, RS=569, RA=711, W=65, OBP=0.305, SLG=0.34, BA=0.237, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=nan, OSLG=nan, WP=0.4, RD=-142)
Pandas(Index=1161, Team='KCA', League='AL', Year=1965, RS=585, RA=755, W=59, OBP=0.309, SLG=0.358, BA=0.24, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=nan, OSLG=nan, WP=0.36, RD=-170)
Pandas(Index=1162, Team='LAD', League='NL', Year=1965, RS=608, RA=521, W=97, OBP=0.312, SLG=0.335, BA=0.245, Playoffs=1, RankSeason=2.0, RankPlayoffs=1.0, G=162, OOBP=nan, OSLG=nan, WP=0.6, RD=87)
Pandas(Index=1163, Team='MIN', League='AL', Year=1965, RS=774, RA=600, W=102, OBP=0.324, SLG=0.39899999999999997, BA=0.254, Playoffs=1, RankSeason=1.0, RankPlayoffs=2.0, G=162, OOBP=nan, OSLG=nan, WP=0.63, RD=174)
Pandas(Index=1164, Team='MLN', League='NL', Year=1965, RS=708, RA=633, W=86, OBP=0.31, SLG=0.41600000000000004, BA=0.256, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=nan, OSLG=nan, WP=0.53, RD=75)
Pandas(Index=1165, Team='NYM', League='NL', Year=1965, RS=495, RA=752, W=50, OBP=0.27699999999999997, SLG=0.327, BA=0.221, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=164, OOBP=nan, OSLG=nan, WP=0.3, RD=-257)
Pandas(Index=1166, Team='NYY', League='AL', Year=1965, RS=611, RA=604, W=77, OBP=0.299, SLG=0.364, BA=0.235, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=nan, OSLG=nan, WP=0.48, RD=7)
Pandas(Index=1167, Team='PHI', League='NL', Year=1965, RS=654, RA=667, W=85, OBP=0.313, SLG=0.384, BA=0.25, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=nan, OSLG=nan, WP=0.52, RD=-13)
Pandas(Index=1168, Team='PIT', League='NL', Year=1965, RS=675, RA=580, W=90, OBP=0.317, SLG=0.382, BA=0.265, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=163, OOBP=nan, OSLG=nan, WP=0.55, RD=95)
Pandas(Index=1169, Team='SFG', League='NL', Year=1965, RS=682, RA=593, W=95, OBP=0.313, SLG=0.385, BA=0.252, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=163, OOBP=nan, OSLG=nan, WP=0.58, RD=89)
Pandas(Index=1170, Team='STL', League='NL', Year=1965, RS=707, RA=674, W=80, OBP=0.314, SLG=0.371, BA=0.254, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=nan, OSLG=nan, WP=0.49, RD=33)
Pandas(Index=1171, Team='WSA', League='AL', Year=1965, RS=591, RA=721, W=70, OBP=0.304, SLG=0.35, BA=0.228, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=nan, OSLG=nan, WP=0.43, RD=-130)
Pandas(Index=1172, Team='BAL', League='AL', Year=1964, RS=679, RA=567, W=97, OBP=0.316, SLG=0.387, BA=0.248, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=163, OOBP=nan, OSLG=nan, WP=0.6, RD=112)
Pandas(Index=1173, Team='BOS', League='AL', Year=1964, RS=688, RA=793, W=72, OBP=0.322, SLG=0.41600000000000004, BA=0.258, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=nan, OSLG=nan, WP=0.44, RD=-105)
Pandas(Index=1174, Team='CHC', League='NL', Year=1964, RS=649, RA=724, W=76, OBP=0.314, SLG=0.39, BA=0.251, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=nan, OSLG=nan, WP=0.47, RD=-75)
Pandas(Index=1175, Team='CHW', League='AL', Year=1964, RS=642, RA=501, W=98, OBP=0.32, SLG=0.353, BA=0.247, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=nan, OSLG=nan, WP=0.6, RD=141)
Pandas(Index=1176, Team='CIN', League='NL', Year=1964, RS=660, RA=566, W=92, OBP=0.308, SLG=0.37200000000000005, BA=0.249, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=163, OOBP=nan, OSLG=nan, WP=0.56, RD=94)
Pandas(Index=1177, Team='CLE', League='AL', Year=1964, RS=689, RA=693, W=79, OBP=0.312, SLG=0.38, BA=0.247, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=164, OOBP=nan, OSLG=nan, WP=0.48, RD=-4)
Pandas(Index=1178, Team='DET', League='AL', Year=1964, RS=699, RA=678, W=85, OBP=0.319, SLG=0.395, BA=0.253, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=163, OOBP=nan, OSLG=nan, WP=0.52, RD=21)
Pandas(Index=1179, Team='HOU', League='NL', Year=1964, RS=495, RA=628, W=66, OBP=0.285, SLG=0.315, BA=0.22899999999999998, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=nan, OSLG=nan, WP=0.41, RD=-133)
Pandas(Index=1180, Team='KCA', League='AL', Year=1964, RS=621, RA=836, W=57, OBP=0.311, SLG=0.379, BA=0.239, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=163, OOBP=nan, OSLG=nan, WP=0.35, RD=-215)
Pandas(Index=1181, Team='LAA', League='AL', Year=1964, RS=544, RA=551, W=82, OBP=0.304, SLG=0.344, BA=0.242, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=nan, OSLG=nan, WP=0.51, RD=-7)
Pandas(Index=1182, Team='LAD', League='NL', Year=1964, RS=614, RA=572, W=80, OBP=0.305, SLG=0.34, BA=0.25, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=164, OOBP=nan, OSLG=nan, WP=0.49, RD=42)
Pandas(Index=1183, Team='MIN', League='AL', Year=1964, RS=737, RA=678, W=79, OBP=0.322, SLG=0.42700000000000005, BA=0.252, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=163, OOBP=nan, OSLG=nan, WP=0.48, RD=59)
Pandas(Index=1184, Team='MLN', League='NL', Year=1964, RS=803, RA=744, W=88, OBP=0.33299999999999996, SLG=0.418, BA=0.272, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=nan, OSLG=nan, WP=0.54, RD=59)
Pandas(Index=1185, Team='NYM', League='NL', Year=1964, RS=569, RA=776, W=53, OBP=0.29600000000000004, SLG=0.348, BA=0.24600000000000002, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=163, OOBP=nan, OSLG=nan, WP=0.33, RD=-207)
Pandas(Index=1186, Team='NYY', League='AL', Year=1964, RS=730, RA=577, W=99, OBP=0.317, SLG=0.387, BA=0.253, Playoffs=1, RankSeason=1.0, RankPlayoffs=2.0, G=164, OOBP=nan, OSLG=nan, WP=0.6, RD=153)
Pandas(Index=1187, Team='PHI', League='NL', Year=1964, RS=693, RA=632, W=92, OBP=0.315, SLG=0.391, BA=0.258, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=nan, OSLG=nan, WP=0.57, RD=61)
Pandas(Index=1188, Team='PIT', League='NL', Year=1964, RS=663, RA=636, W=80, OBP=0.315, SLG=0.389, BA=0.264, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=nan, OSLG=nan, WP=0.49, RD=27)
Pandas(Index=1189, Team='SFG', League='NL', Year=1964, RS=656, RA=587, W=90, OBP=0.31, SLG=0.382, BA=0.24600000000000002, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=nan, OSLG=nan, WP=0.56, RD=69)
Pandas(Index=1190, Team='STL', League='NL', Year=1964, RS=715, RA=652, W=93, OBP=0.324, SLG=0.392, BA=0.272, Playoffs=1, RankSeason=2.0, RankPlayoffs=1.0, G=162, OOBP=nan, OSLG=nan, WP=0.57, RD=63)
Pandas(Index=1191, Team='WSA', League='AL', Year=1964, RS=578, RA=733, W=62, OBP=0.299, SLG=0.348, BA=0.231, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=nan, OSLG=nan, WP=0.38, RD=-155)
Pandas(Index=1192, Team='BAL', League='AL', Year=1963, RS=644, RA=621, W=86, OBP=0.31, SLG=0.38, BA=0.249, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=nan, OSLG=nan, WP=0.53, RD=23)
Pandas(Index=1193, Team='BOS', League='AL', Year=1963, RS=666, RA=704, W=76, OBP=0.312, SLG=0.4, BA=0.252, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=161, OOBP=nan, OSLG=nan, WP=0.47, RD=-38)
Pandas(Index=1194, Team='CHC', League='NL', Year=1963, RS=570, RA=578, W=82, OBP=0.297, SLG=0.363, BA=0.23800000000000002, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=nan, OSLG=nan, WP=0.51, RD=-8)
Pandas(Index=1195, Team='CHW', League='AL', Year=1963, RS=683, RA=544, W=94, OBP=0.32299999999999995, SLG=0.365, BA=0.25, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=nan, OSLG=nan, WP=0.58, RD=139)
Pandas(Index=1196, Team='CIN', League='NL', Year=1963, RS=648, RA=594, W=86, OBP=0.31, SLG=0.371, BA=0.24600000000000002, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=nan, OSLG=nan, WP=0.53, RD=54)
Pandas(Index=1197, Team='CLE', League='AL', Year=1963, RS=635, RA=702, W=79, OBP=0.301, SLG=0.381, BA=0.239, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=nan, OSLG=nan, WP=0.49, RD=-67)
Pandas(Index=1198, Team='DET', League='AL', Year=1963, RS=700, RA=703, W=79, OBP=0.327, SLG=0.382, BA=0.252, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=nan, OSLG=nan, WP=0.49, RD=-3)
Pandas(Index=1199, Team='HOU', League='NL', Year=1963, RS=464, RA=640, W=66, OBP=0.28300000000000003, SLG=0.301, BA=0.22, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=nan, OSLG=nan, WP=0.41, RD=-176)
Pandas(Index=1200, Team='KCA', League='AL', Year=1963, RS=615, RA=704, W=73, OBP=0.313, SLG=0.353, BA=0.247, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=nan, OSLG=nan, WP=0.45, RD=-89)
Pandas(Index=1201, Team='LAA', League='AL', Year=1963, RS=597, RA=660, W=70, OBP=0.309, SLG=0.354, BA=0.25, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=161, OOBP=nan, OSLG=nan, WP=0.43, RD=-63)
Pandas(Index=1202, Team='LAD', League='NL', Year=1963, RS=640, RA=550, W=99, OBP=0.309, SLG=0.35700000000000004, BA=0.251, Playoffs=1, RankSeason=2.0, RankPlayoffs=1.0, G=163, OOBP=nan, OSLG=nan, WP=0.61, RD=90)
Pandas(Index=1203, Team='MIN', League='AL', Year=1963, RS=767, RA=602, W=91, OBP=0.325, SLG=0.43, BA=0.255, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=161, OOBP=nan, OSLG=nan, WP=0.57, RD=165)
Pandas(Index=1204, Team='MLN', League='NL', Year=1963, RS=677, RA=603, W=84, OBP=0.312, SLG=0.37, BA=0.244, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=163, OOBP=nan, OSLG=nan, WP=0.52, RD=74)
Pandas(Index=1205, Team='NYM', League='NL', Year=1963, RS=501, RA=774, W=51, OBP=0.285, SLG=0.315, BA=0.21899999999999997, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=nan, OSLG=nan, WP=0.31, RD=-273)
Pandas(Index=1206, Team='NYY', League='AL', Year=1963, RS=714, RA=547, W=104, OBP=0.309, SLG=0.40299999999999997, BA=0.252, Playoffs=1, RankSeason=1.0, RankPlayoffs=2.0, G=161, OOBP=nan, OSLG=nan, WP=0.65, RD=167)
Pandas(Index=1207, Team='PHI', League='NL', Year=1963, RS=642, RA=578, W=87, OBP=0.306, SLG=0.381, BA=0.252, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=nan, OSLG=nan, WP=0.54, RD=64)
Pandas(Index=1208, Team='PIT', League='NL', Year=1963, RS=567, RA=595, W=74, OBP=0.309, SLG=0.359, BA=0.25, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=nan, OSLG=nan, WP=0.46, RD=-28)
Pandas(Index=1209, Team='SFG', League='NL', Year=1963, RS=725, RA=641, W=88, OBP=0.316, SLG=0.414, BA=0.258, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=nan, OSLG=nan, WP=0.54, RD=84)
Pandas(Index=1210, Team='STL', League='NL', Year=1963, RS=747, RA=628, W=93, OBP=0.326, SLG=0.40299999999999997, BA=0.271, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=nan, OSLG=nan, WP=0.57, RD=119)
Pandas(Index=1211, Team='WSA', League='AL', Year=1963, RS=578, RA=812, W=56, OBP=0.293, SLG=0.35100000000000003, BA=0.22699999999999998, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=nan, OSLG=nan, WP=0.35, RD=-234)
Pandas(Index=1212, Team='BAL', League='AL', Year=1962, RS=652, RA=680, W=77, OBP=0.314, SLG=0.387, BA=0.248, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=nan, OSLG=nan, WP=0.48, RD=-28)
Pandas(Index=1213, Team='BOS', League='AL', Year=1962, RS=707, RA=756, W=76, OBP=0.324, SLG=0.40299999999999997, BA=0.258, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=160, OOBP=nan, OSLG=nan, WP=0.48, RD=-49)
Pandas(Index=1214, Team='CHC', League='NL', Year=1962, RS=632, RA=827, W=59, OBP=0.317, SLG=0.377, BA=0.253, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=nan, OSLG=nan, WP=0.36, RD=-195)
Pandas(Index=1215, Team='CHW', League='AL', Year=1962, RS=707, RA=658, W=85, OBP=0.33399999999999996, SLG=0.37200000000000005, BA=0.257, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=nan, OSLG=nan, WP=0.52, RD=49)
Pandas(Index=1216, Team='CIN', League='NL', Year=1962, RS=802, RA=685, W=98, OBP=0.332, SLG=0.41700000000000004, BA=0.27, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=nan, OSLG=nan, WP=0.6, RD=117)
Pandas(Index=1217, Team='CLE', League='AL', Year=1962, RS=682, RA=745, W=80, OBP=0.312, SLG=0.38799999999999996, BA=0.245, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=nan, OSLG=nan, WP=0.49, RD=-63)
Pandas(Index=1218, Team='DET', League='AL', Year=1962, RS=758, RA=692, W=85, OBP=0.33, SLG=0.41100000000000003, BA=0.248, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=161, OOBP=nan, OSLG=nan, WP=0.53, RD=66)
Pandas(Index=1219, Team='HOU', League='NL', Year=1962, RS=592, RA=717, W=64, OBP=0.31, SLG=0.35100000000000003, BA=0.24600000000000002, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=nan, OSLG=nan, WP=0.4, RD=-125)
Pandas(Index=1220, Team='KCA', League='AL', Year=1962, RS=745, RA=837, W=72, OBP=0.332, SLG=0.386, BA=0.263, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=nan, OSLG=nan, WP=0.44, RD=-92)
Pandas(Index=1221, Team='LAA', League='AL', Year=1962, RS=718, RA=706, W=86, OBP=0.325, SLG=0.38, BA=0.25, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=nan, OSLG=nan, WP=0.53, RD=12)
Pandas(Index=1222, Team='LAD', League='NL', Year=1962, RS=842, RA=697, W=102, OBP=0.337, SLG=0.4, BA=0.268, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=165, OOBP=nan, OSLG=nan, WP=0.62, RD=145)
Pandas(Index=1223, Team='MIN', League='AL', Year=1962, RS=798, RA=713, W=91, OBP=0.33799999999999997, SLG=0.41200000000000003, BA=0.26, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=163, OOBP=nan, OSLG=nan, WP=0.56, RD=85)
Pandas(Index=1224, Team='MLN', League='NL', Year=1962, RS=730, RA=665, W=86, OBP=0.326, SLG=0.40299999999999997, BA=0.252, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=nan, OSLG=nan, WP=0.53, RD=65)
Pandas(Index=1225, Team='NYM', League='NL', Year=1962, RS=617, RA=948, W=40, OBP=0.318, SLG=0.361, BA=0.24, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=161, OOBP=nan, OSLG=nan, WP=0.25, RD=-331)
Pandas(Index=1226, Team='NYY', League='AL', Year=1962, RS=817, RA=680, W=96, OBP=0.337, SLG=0.426, BA=0.267, Playoffs=1, RankSeason=2.0, RankPlayoffs=1.0, G=162, OOBP=nan, OSLG=nan, WP=0.59, RD=137)
Pandas(Index=1227, Team='PHI', League='NL', Year=1962, RS=705, RA=759, W=81, OBP=0.33, SLG=0.39, BA=0.26, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=161, OOBP=nan, OSLG=nan, WP=0.5, RD=-54)
Pandas(Index=1228, Team='PIT', League='NL', Year=1962, RS=706, RA=626, W=93, OBP=0.321, SLG=0.39399999999999996, BA=0.268, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=161, OOBP=nan, OSLG=nan, WP=0.58, RD=80)
Pandas(Index=1229, Team='SFG', League='NL', Year=1962, RS=878, RA=690, W=103, OBP=0.341, SLG=0.441, BA=0.278, Playoffs=1, RankSeason=1.0, RankPlayoffs=2.0, G=165, OOBP=nan, OSLG=nan, WP=0.62, RD=188)
Pandas(Index=1230, Team='STL', League='NL', Year=1962, RS=774, RA=664, W=84, OBP=0.335, SLG=0.39399999999999996, BA=0.271, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=163, OOBP=nan, OSLG=nan, WP=0.52, RD=110)
Pandas(Index=1231, Team='WSA', League='AL', Year=1962, RS=599, RA=716, W=60, OBP=0.308, SLG=0.373, BA=0.25, Playoffs=0, RankSeason=nan, RankPlayoffs=nan, G=162, OOBP=nan, OSLG=nan, WP=0.37, RD=-117)

### Another iterator method: .itertuples()

In [37]:
row_named_tuple.Index

1231

In [38]:
print(row_named_tuple.Team)

WSA

In [39]:
for row_tuple in df.iterrows():
    print (row_tuple[1]['Team'])
    
# for interrow , can use [] but you can t use it for itertuple

ARI
ATL
BAL
BOS
CHC
CHW
CIN
CLE
COL
DET
HOU
KCR
LAA
LAD
MIA
MIL
MIN
NYM
NYY
OAK
PHI
PIT
SDP
SEA
SFG
STL
TBR
TEX
TOR
WSN
ARI
ATL
BAL
BOS
CHC
CHW
CIN
CLE
COL
DET
FLA
HOU
KCR
LAA
LAD
MIL
MIN
NYM
NYY
OAK
PHI
PIT
SDP
SEA
SFG
STL
TBR
TEX
TOR
WSN
ARI
ATL
BAL
BOS
CHC
CHW
CIN
CLE
COL
DET
FLA
HOU
KCR
LAA
LAD
MIL
MIN
NYM
NYY
OAK
PHI
PIT
SDP
SEA
SFG
STL
TBR
TEX
TOR
WSN
ARI
ATL
BAL
BOS
CHC
CHW
CIN
CLE
COL
DET
FLA
HOU
KCR
LAA
LAD
MIL
MIN
NYM
NYY
OAK
PHI
PIT
SDP
SEA
SFG
STL
TBR
TEX
TOR
WSN
ARI
ATL
BAL
BOS
CHC
CHW
CIN
CLE
COL
DET
FLA
HOU
KCR
LAA
LAD
MIL
MIN
NYM
NYY
OAK
PHI
PIT
SDP
SEA
SFG
STL
TBR
TEX
TOR
WSN
ARI
ATL
BAL
BOS
CHC
CHW
CIN
CLE
COL
DET
FLA
HOU
KCR
LAA
LAD
MIL
MIN
NYM
NYY
OAK
PHI
PIT
SDP
SEA
SFG
STL
TBD
TEX
TOR
WSN
ARI
ATL
BAL
BOS
CHC
CHW
CIN
CLE
COL
DET
FLA
HOU
KCR
LAA
LAD
MIL
MIN
NYM
NYY
OAK
PHI
PIT
SDP
SEA
SFG
STL
TBD
TEX
TOR
WSN
ARI
ATL
BAL
BOS
CHC
CHW
CIN
CLE
COL
DET
FLA
HOU
KCR
LAA
LAD
MIL
MIN
NYM
NYY
OAK
PHI
PIT
SDP
SEA
SFG
STL
TBD
TEX
TOR
WSN
ANA
ARI
ATL
BAL
BOS
CHC
CHW
CIN
CLE
COL
DET
FLA
HOU
KCR
LAD
MIL
MIN
MON
NYM
NYY
OAK
PHI
PIT
SDP
SEA
SFG
STL
TBD
TEX
TOR
ANA
ARI
ATL
BAL
BOS
CHC
CHW
CIN
CLE
COL
DET
FLA
HOU
KCR
LAD
MIL
MIN
MON
NYM
NYY
OAK
PHI
PIT
SDP
SEA
SFG
STL
TBD
TEX
TOR
ANA
ARI
ATL
BAL
BOS
CHC
CHW
CIN
CLE
COL
DET
FLA
HOU
KCR
LAD
MIL
MIN
MON
NYM
NYY
OAK
PHI
PIT
SDP
SEA
SFG
STL
TBD
TEX
TOR
ANA
ARI
ATL
BAL
BOS
CHC
CHW
CIN
CLE
COL
DET
FLA
HOU
KCR
LAD
MIL
MIN
MON
NYM
NYY
OAK
PHI
PIT
SDP
SEA
SFG
STL
TBD
TEX
TOR
ANA
ARI
ATL
BAL
BOS
CHC
CHW
CIN
CLE
COL
DET
FLA
HOU
KCR
LAD
MIL
MIN
MON
NYM
NYY
OAK
PHI
PIT
SDP
SEA
SFG
STL
TBD
TEX
TOR
ANA
ARI
ATL
BAL
BOS
CHC
CHW
CIN
CLE
COL
DET
FLA
HOU
KCR
LAD
MIL
MIN
MON
NYM
NYY
OAK
PHI
PIT
SDP
SEA
SFG
STL
TBD
TEX
TOR
ANA
ARI
ATL
BAL
BOS
CHC
CHW
CIN
CLE
COL
DET
FLA
HOU
KCR
LAD
MIL
MIN
MON
NYM
NYY
OAK
PHI
PIT
SDP
SEA
SFG
STL
TBD
TEX
TOR
ANA
ATL
BAL
BOS
CHC
CHW
CIN
CLE
COL
DET
FLA
HOU
KCR
LAD
MIL
MIN
MON
NYM
NYY
OAK
PHI
PIT
SDP
SEA
SFG
STL
TEX
TOR
ATL
BAL
BOS
CAL
CHC
CHW
CIN
CLE
COL
DET
FLA
HOU
KCR
LAD
MIL
MIN
MON
NYM
NYY
OAK
PHI
PIT
SDP
SEA
SFG
STL
TEX
TOR
ATL
BAL
BOS
CAL
CHC
CHW
CIN
CLE
COL
DET
FLA
HOU
KCR
LAD
MIL
MIN
MON
NYM
NYY
OAK
PHI
PIT
SDP
SEA
SFG
STL
TEX
TOR
ATL
BAL
BOS
CAL
CHC
CHW
CIN
CLE
DET
HOU
KCR
LAD
MIL
MIN
MON
NYM
NYY
OAK
PHI
PIT
SDP
SEA
SFG
STL
TEX
TOR
ATL
BAL
BOS
CAL
CHC
CHW
CIN
CLE
DET
HOU
KCR
LAD
MIL
MIN
MON
NYM
NYY
OAK
PHI
PIT
SDP
SEA
SFG
STL
TEX
TOR
ATL
BAL
BOS
CAL
CHC
CHW
CIN
CLE
DET
HOU
KCR
LAD
MIL
MIN
MON
NYM
NYY
OAK
PHI
PIT
SDP
SEA
SFG
STL
TEX
TOR
ATL
BAL
BOS
CAL
CHC
CHW
CIN
CLE
DET
HOU
KCR
LAD
MIL
MIN
MON
NYM
NYY
OAK
PHI
PIT
SDP
SEA
SFG
STL
TEX
TOR
ATL
BAL
BOS
CAL
CHC
CHW
CIN
CLE
DET
HOU
KCR
LAD
MIL
MIN
MON
NYM
NYY
OAK
PHI
PIT
SDP
SEA
SFG
STL
TEX
TOR
ATL
BAL
BOS
CAL
CHC
CHW
CIN
CLE
DET
HOU
KCR
LAD
MIL
MIN
MON
NYM
NYY
OAK
PHI
PIT
SDP
SEA
SFG
STL
TEX
TOR
ATL
BAL
BOS
CAL
CHC
CHW
CIN
CLE
DET
HOU
KCR
LAD
MIL
MIN
MON
NYM
NYY
OAK
PHI
PIT
SDP
SEA
SFG
STL
TEX
TOR
ATL
BAL
BOS
CAL
CHC
CHW
CIN
CLE
DET
HOU
KCR
LAD
MIL
MIN
MON
NYM
NYY
OAK
PHI
PIT
SDP
SEA
SFG
STL
TEX
TOR
ATL
BAL
BOS
CAL
CHC
CHW
CIN
CLE
DET
HOU
KCR
LAD
MIL
MIN
MON
NYM
NYY
OAK
PHI
PIT
SDP
SEA
SFG
STL
TEX
TOR
ATL
BAL
BOS
CAL
CHC
CHW
CIN
CLE
DET
HOU
KCR
LAD
MIL
MIN
MON
NYM
NYY
OAK
PHI
PIT
SDP
SEA
SFG
STL
TEX
TOR
ATL
BAL
BOS
CAL
CHC
CHW
CIN
CLE
DET
HOU
KCR
LAD
MIL
MIN
MON
NYM
NYY
OAK
PHI
PIT
SDP
SEA
SFG
STL
TEX
TOR
ATL
BAL
BOS
CAL
CHC
CHW
CIN
CLE
DET
HOU
KCR
LAD
MIL
MIN
MON
NYM
NYY
OAK
PHI
PIT
SDP
SEA
SFG
STL
TEX
TOR
ATL
BAL
BOS
CAL
CHC
CHW
CIN
CLE
DET
HOU
KCR
LAD
MIL
MIN
MON
NYM
NYY
OAK
PHI
PIT
SDP
SEA
SFG
STL
TEX
TOR
ATL
BAL
BOS
CAL
CHC
CHW
CIN
CLE
DET
HOU
KCR
LAD
MIL
MIN
MON
NYM
NYY
OAK
PHI
PIT
SDP
SEA
SFG
STL
TEX
TOR
ATL
BAL
BOS
CAL
CHC
CHW
CIN
CLE
DET
HOU
KCR
LAD
MIL
MIN
MON
NYM
NYY
OAK
PHI
PIT
SDP
SEA
SFG
STL
TEX
TOR
ATL
BAL
BOS
CAL
CHC
CHW
CIN
CLE
DET
HOU
KCR
LAD
MIL
MIN
MON
NYM
NYY
OAK
PHI
PIT
SDP
SFG
STL
TEX
ATL
BAL
BOS
CAL
CHC
CHW
CIN
CLE
DET
HOU
KCR
LAD
MIL
MIN
MON
NYM
NYY
OAK
PHI
PIT
SDP
SFG
STL
TEX
ATL
BAL
BOS
CAL
CHC
CHW
CIN
CLE
DET
HOU
KCR
LAD
MIL
MIN
MON
NYM
NYY
OAK
PHI
PIT
SDP
SFG
STL
TEX
ATL
BAL
BOS
CAL
CHC
CHW
CIN
CLE
DET
HOU
KCR
LAD
MIL
MIN
MON
NYM
NYY
OAK
PHI
PIT
SDP
SFG
STL
TEX
ATL
BAL
BOS
CAL
CHC
CHW
CIN
CLE
DET
HOU
KCR
LAD
MIL
MIN
MON
NYM
NYY
OAK
PHI
PIT
SDP
SFG
STL
WSA
ATL
BAL
BOS
CAL
CHC
CHW
CIN
CLE
DET
HOU
KCR
LAD
MIL
MIN
MON
NYM
NYY
OAK
PHI
PIT
SDP
SFG
STL
WSA
ATL
BAL
BOS
CAL
CHC
CHW
CIN
CLE
DET
HOU
KCR
LAD
MIN
MON
NYM
NYY
OAK
PHI
PIT
SDP
SEP
SFG
STL
WSA
ATL
BAL
BOS
CAL
CHC
CHW
CIN
CLE
DET
HOU
LAD
MIN
NYM
NYY
OAK
PHI
PIT
SFG
STL
WSA
ATL
BAL
BOS
CAL
CHC
CHW
CIN
CLE
DET
HOU
KCA
LAD
MIN
NYM
NYY
PHI
PIT
SFG
STL
WSA
ATL
BAL
BOS
CAL
CHC
CHW
CIN
CLE
DET
HOU
KCA
LAD
MIN
NYM
NYY
PHI
PIT
SFG
STL
WSA
BAL
BOS
CAL
CHC
CHW
CIN
CLE
DET
HOU
KCA
LAD
MIN
MLN
NYM
NYY
PHI
PIT
SFG
STL
WSA
BAL
BOS
CHC
CHW
CIN
CLE
DET
HOU
KCA
LAA
LAD
MIN
MLN
NYM
NYY
PHI
PIT
SFG
STL
WSA
BAL
BOS
CHC
CHW
CIN
CLE
DET
HOU
KCA
LAA
LAD
MIN
MLN
NYM
NYY
PHI
PIT
SFG
STL
WSA
BAL
BOS
CHC
CHW
CIN
CLE
DET
HOU
KCA
LAA
LAD
MIN
MLN
NYM
NYY
PHI
PIT
SFG
STL
WSA

In [40]:
# run_diffs = []

# Loop over the DataFrame and calculate each row's run differential
#for row in yankees_df.itertuples():
    
#    runs_scored = row.RS
#    runs_allowed = row.RA

#    run_diff = calc_run_diff(runs_scored, runs_allowed)
    
#    run_diffs.append(run_diff)

# Append new column
# yankees_df['RD'] = run_diffs
# print(yankees_df)

### pandas alternative to looping

In [24]:
def calc_run_diff(runs_scored, runs_allowed):

    run_diff = runs_scored - runs_allowed

    return run_diff

In [46]:
run_diffs_iterrows=[]

for i,row in df.iterrows():
    run_diff=calc_run_diff(row['RS'],row['RA'])
    run_diffs_iterrows.append(run_diff)
    
df['RD'] = run_diffs
print(df)

     Team League  Year   RS   RA    W    OBP    SLG     BA  Playoffs  \
0     ARI     NL  2012  734  688   81  0.328  0.418  0.259         0
1     ATL     NL  2012  700  600   94  0.320  0.389  0.247         1
2     BAL     AL  2012  712  705   93  0.311  0.417  0.247         1
3     BOS     AL  2012  734  806   69  0.315  0.415  0.260         0
4     CHC     NL  2012  613  759   61  0.302  0.378  0.240         0
...   ...    ...   ...  ...  ...  ...    ...    ...    ...       ...
1227  PHI     NL  1962  705  759   81  0.330  0.390  0.260         0
1228  PIT     NL  1962  706  626   93  0.321  0.394  0.268         0
1229  SFG     NL  1962  878  690  103  0.341  0.441  0.278         1
1230  STL     NL  1962  774  664   84  0.335  0.394  0.271         0
1231  WSA     AL  1962  599  716   60  0.308  0.373  0.250         0

      RankSeason  RankPlayoffs    G   OOBP   OSLG    WP   RD
0            NaN           NaN  162  0.317  0.415  0.50   46
1            4.0           5.0  162  0.306  0.378  0.58  100
2            5.0           4.0  162  0.315  0.403  0.57    7
3            NaN           NaN  162  0.331  0.428  0.43  -72
4            NaN           NaN  162  0.335  0.424  0.38 -146
...          ...           ...  ...    ...    ...   ...  ...
1227         NaN           NaN  161    NaN    NaN  0.50  -54
1228         NaN           NaN  161    NaN    NaN  0.58   80
1229         1.0           2.0  165    NaN    NaN  0.62  188
1230         NaN           NaN  163    NaN    NaN  0.52  110
1231         NaN           NaN  162    NaN    NaN  0.37 -117

[1232 rows x 17 columns]

### panda.apply function

In [47]:
run_diffs_apply = df.apply(lambda row: calc_run_diff(row['RS'],row['RA']), axis = 1)

df['RD'] = run_diffs_apply

print(df)
# takes less time than iterrows

     Team League  Year   RS   RA    W    OBP    SLG     BA  Playoffs  \
0     ARI     NL  2012  734  688   81  0.328  0.418  0.259         0
1     ATL     NL  2012  700  600   94  0.320  0.389  0.247         1
2     BAL     AL  2012  712  705   93  0.311  0.417  0.247         1
3     BOS     AL  2012  734  806   69  0.315  0.415  0.260         0
4     CHC     NL  2012  613  759   61  0.302  0.378  0.240         0
...   ...    ...   ...  ...  ...  ...    ...    ...    ...       ...
1227  PHI     NL  1962  705  759   81  0.330  0.390  0.260         0
1228  PIT     NL  1962  706  626   93  0.321  0.394  0.268         0
1229  SFG     NL  1962  878  690  103  0.341  0.441  0.278         1
1230  STL     NL  1962  774  664   84  0.335  0.394  0.271         0
1231  WSA     AL  1962  599  716   60  0.308  0.373  0.250         0

      RankSeason  RankPlayoffs    G   OOBP   OSLG    WP   RD
0            NaN           NaN  162  0.317  0.415  0.50   46
1            4.0           5.0  162  0.306  0.378  0.58  100
2            5.0           4.0  162  0.315  0.403  0.57    7
3            NaN           NaN  162  0.331  0.428  0.43  -72
4            NaN           NaN  162  0.335  0.424  0.38 -146
...          ...           ...  ...    ...    ...   ...  ...
1227         NaN           NaN  161    NaN    NaN  0.50  -54
1228         NaN           NaN  161    NaN    NaN  0.58   80
1229         1.0           2.0  165    NaN    NaN  0.62  188
1230         NaN           NaN  163    NaN    NaN  0.52  110
1231         NaN           NaN  162    NaN    NaN  0.37 -117

[1232 rows x 17 columns]

In [48]:
def text_playoffs(num_playoffs): 
    if num_playoffs == 1:
        return 'Yes'
    else:
        return 'No'

In [64]:

# Gather sum of all columns
#stat_totals = df.apply(sum, axis=0)
#print(stat_totals)

# Gather total runs scored in all games per year
#total_runs_scored = rays_df[['RS', 'RA']].apply(sum, axis=1)
#print(total_runs_scored)

# Convert numeric playoffs to text
#textual_playoffs = rays_df.apply(lambda row: text_playoffs(row['Playoffs']), axis=1)
#print(textual_playoffs)

# Optimal Pandas Iterating

In [66]:
df.head()

,Team,League,Year,RS,RA,W,OBP,SLG,BA,Playoffs,RankSeason,RankPlayoffs,G,OOBP,OSLG,WP,RD
0,ARI,NL,2012,734,688,81,0.328,0.418,0.259,0,NaN,NaN,162,0.317,0.415,0.50,46
1,ATL,NL,2012,700,600,94,0.320,0.389,0.247,1,4.0,5.0,162,0.306,0.378,0.58,100
2,BAL,AL,2012,712,705,93,0.311,0.417,0.247,1,5.0,4.0,162,0.315,0.403,0.57,7
3,BOS,AL,2012,734,806,69,0.315,0.415,0.260,0,NaN,NaN,162,0.331,0.428,0.43,-72
4,CHC,NL,2012,613,759,61,0.302,0.378,0.240,0,NaN,NaN,162,0.335,0.424,0.38,-146

In [68]:
wins_np=df['W'].values
wins_np

array([ 81,  94,  93, ..., 103,  84,  60])

In [69]:
print(type(wins_np))

<class 'numpy.ndarray'>

In [72]:
# Power of Vectorization
# Vectorization is extremely efficient
run_diffs_np =df['RS'].values-df['RA'].values
df['RD'] = run_diffs_np
print(df)

     Team League  Year   RS   RA    W    OBP    SLG     BA  Playoffs  \
0     ARI     NL  2012  734  688   81  0.328  0.418  0.259         0
1     ATL     NL  2012  700  600   94  0.320  0.389  0.247         1
2     BAL     AL  2012  712  705   93  0.311  0.417  0.247         1
3     BOS     AL  2012  734  806   69  0.315  0.415  0.260         0
4     CHC     NL  2012  613  759   61  0.302  0.378  0.240         0
...   ...    ...   ...  ...  ...  ...    ...    ...    ...       ...
1227  PHI     NL  1962  705  759   81  0.330  0.390  0.260         0
1228  PIT     NL  1962  706  626   93  0.321  0.394  0.268         0
1229  SFG     NL  1962  878  690  103  0.341  0.441  0.278         1
1230  STL     NL  1962  774  664   84  0.335  0.394  0.271         0
1231  WSA     AL  1962  599  716   60  0.308  0.373  0.250         0

      RankSeason  RankPlayoffs    G   OOBP   OSLG    WP   RD
0            NaN           NaN  162  0.317  0.415  0.50   46
1            4.0           5.0  162  0.306  0.378  0.58  100
2            5.0           4.0  162  0.315  0.403  0.57    7
3            NaN           NaN  162  0.331  0.428  0.43  -72
4            NaN           NaN  162  0.335  0.424  0.38 -146
...          ...           ...  ...    ...    ...   ...  ...
1227         NaN           NaN  161    NaN    NaN  0.50  -54
1228         NaN           NaN  161    NaN    NaN  0.58   80
1229         1.0           2.0  165    NaN    NaN  0.62  188
1230         NaN           NaN  163    NaN    NaN  0.52  110
1231         NaN           NaN  162    NaN    NaN  0.37 -117

[1232 rows x 17 columns]

Using NumPy arrays was the fastest approach, followed by the .itertuples() approach, and the .apply() approach was slowest.

In [75]:


def calc_win_perc(wins, games_played):
    win_perc = wins / games_played
    return np.round(win_perc,2)


win_percs_list = []

for i in range(len(df)):
    row = df.iloc[i]

    wins = row['W']
    games_played = row['G']

    win_perc = calc_win_perc(wins, games_played)

    win_percs_list.append(win_perc)

df['WP'] = win_percs_list

In [77]:
# Another tuple method

def predict_win_perc(RS, RA):
    prediction = RS ** 2 / (RS ** 2 + RA ** 2)
    return np.round(prediction, 2)

win_perc_preds_loop = []

# Use a loop and .itertuples() to collect each row's predicted win percentage
for row in df.itertuples():
    runs_scored = row.RS
    runs_allowed = row.RA
    win_perc_pred = predict_win_perc(runs_scored, runs_allowed)
    win_perc_preds_loop.append(win_perc_pred)

In [80]:
# Apply Method
# predict_win_perc to each row of the DataFrame
win_perc_preds_apply = df.apply(lambda row: predict_win_perc(row['RS'], row['RA']), axis=1)
win_perc_preds_apply

0       0.53
1       0.58
2       0.50
3       0.45
4       0.39
        ...
1227    0.46
1228    0.56
1229    0.62
1230    0.58
1231    0.41
Length: 1232, dtype: float64

In [85]:
def predict_win_perc(RS, RA):
    prediction = RS ** 2 / (RS ** 2 + RA ** 2)
    return np.round(prediction, 2)

# Calculate the win percentage predictions using NumPy arrays
win_perc_preds_np = predict_win_perc(df['RS'].values, df['RA'].values)
df['WP_preds'] = win_perc_preds_np
print(df.head())

  Team League  Year   RS   RA   W    OBP    SLG     BA  Playoffs  RankSeason  \
0  ARI     NL  2012  734  688  81  0.328  0.418  0.259         0         NaN
1  ATL     NL  2012  700  600  94  0.320  0.389  0.247         1         4.0
2  BAL     AL  2012  712  705  93  0.311  0.417  0.247         1         5.0
3  BOS     AL  2012  734  806  69  0.315  0.415  0.260         0         NaN
4  CHC     NL  2012  613  759  61  0.302  0.378  0.240         0         NaN

   RankPlayoffs    G   OOBP   OSLG    WP   RD  WP_preds
0           NaN  162  0.317  0.415  0.50   46      0.53
1           5.0  162  0.306  0.378  0.58  100      0.58
2           4.0  162  0.315  0.403  0.57    7      0.50
3           NaN  162  0.331  0.428  0.43  -72      0.45
4           NaN  162  0.335  0.424  0.38 -146      0.39